packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  msgpackr-extract: true
  prisma: true
minimumReleaseAgeExclude:
  - bullmq@6.1.1
