import { App, ConfigProvider } from 'antd';
import { act, createElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { MemoryRouter } from 'react-router';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { Asset, DirectoryUser, License, LicenseAssignment } from '@uims/shared-types';
import { EmployeesTab } from './EmployeesTab';

(
  globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT?: boolean }
).IS_REACT_ACT_ENVIRONMENT = true;

const mockUser: DirectoryUser = {
  id: 'emp-detail-1',
  employeeCode: '63020099',
  email: 'johndoe@youngonevn.com',
  firstName: 'John',
  lastName: 'Doe',
  fullName: 'John Doe',
  departmentId: 'dept-1',
  department: {
    id: 'dept-1',
    name: 'IT Infrastructure',
    code: 'IT',
    status: 'Active',
    organizationId: 'org-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  positionId: 'pos-1',
  position: {
    id: 'pos-1',
    title: 'Network Specialist',
    code: 'NS',
    status: 'Active',
    departmentId: 'dept-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  organizationId: 'org-1',
  organization: {
    id: 'org-1',
    name: 'BSL Enterprise',
    code: 'BSL',
    status: 'Active',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  status: 'ACTIVE' as DirectoryUser['status'],
  source: 'LOCAL' as DirectoryUser['source'],
  adDomain: 'uims.internal',
  computerName: 'VN-IT-WS01',
  domainJoined: true,
  domainJoinStatus: 'JOINED',
  hasEmailPassword: true,
  assignedAssetsCount: 1,
  assignedLicensesCount: 1,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};

const mockAsset: Asset = {
  id: 'asset-1',
  assetTag: 'AST-NB-001',
  name: 'ThinkPad T14 Gen 4',
  model: 'T14 Gen 4',
  serialNumber: 'SN-TP-12345',
  status: 'IN_USE' as Asset['status'],
  assignedToId: 'emp-detail-1',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const mockLicenseAssignment: LicenseAssignment & { license: License } = {
  id: 'la-1',
  licenseId: 'lic-1',
  userId: 'emp-detail-1',
  assignedAt: new Date().toISOString(),
  license: {
    id: 'lic-1',
    name: 'Microsoft 365 E5',
    publisher: 'Microsoft',
    type: 'SUBSCRIPTION',
    totalSeats: 100,
    usedSeats: 45,
    status: 'ACTIVE' as License['status'],
    autoRenew: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
};

const mockAvailableAsset: Asset = {
  id: 'asset-2',
  assetTag: 'AST-NB-002',
  name: 'Dell Latitude 5540',
  model: 'Latitude 5540',
  serialNumber: 'SN-DELL-67890',
  status: 'AVAILABLE' as Asset['status'],
  assignedToId: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const mockAvailableLicense: License = {
  id: 'lic-2',
  name: 'JetBrains All Products Pack',
  publisher: 'JetBrains',
  type: 'PERPETUAL',
  totalSeats: 50,
  usedSeats: 20,
  status: 'ACTIVE' as License['status'],
  autoRenew: false,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

const mockGetUserAssets = vi.fn().mockResolvedValue([mockAsset]);
const mockGetUserLicenses = vi.fn().mockResolvedValue([mockLicenseAssignment]);
const mockGetAvailableAssets = vi.fn().mockResolvedValue([mockAvailableAsset]);
const mockGetAvailableLicenses = vi.fn().mockResolvedValue([mockAvailableLicense]);
const mockAssignAsset = vi.fn().mockResolvedValue({ ...mockAvailableAsset, status: 'IN_USE' });
const mockUnassignAsset = vi.fn().mockResolvedValue({ success: true });
const mockAssignLicense = vi
  .fn()
  .mockResolvedValue({ id: 'la-2', licenseId: 'lic-2', userId: 'emp-detail-1' });
const mockUnassignLicense = vi.fn().mockResolvedValue({ success: true });
const mockRevealEmailPassword = vi.fn().mockResolvedValue({
  password: 'SuperSecretDecryptedPass123!',
  revealedAt: new Date().toISOString(),
});
const mockCopyEmailPassword = vi
  .fn()
  .mockResolvedValue({ success: true, copiedAt: new Date().toISOString() });
const mockResetEmailPassword = vi
  .fn()
  .mockResolvedValue({ success: true, autoGenerated: true, password: 'GeneratedPass987!' });

vi.mock('../../services/directory.service', () => ({
  directoryService: {
    createEmployee: vi.fn(),
    updateEmployee: vi.fn(),
    deleteEmployee: vi.fn(),
    importEmployees: vi.fn(),
    getUserAssets: (...args: unknown[]) => mockGetUserAssets(...args),
    getUserLicenses: (...args: unknown[]) => mockGetUserLicenses(...args),
    getAvailableAssets: (...args: unknown[]) => mockGetAvailableAssets(...args),
    getAvailableLicenses: (...args: unknown[]) => mockGetAvailableLicenses(...args),
    assignAsset: (...args: unknown[]) => mockAssignAsset(...args),
    unassignAsset: (...args: unknown[]) => mockUnassignAsset(...args),
    assignLicense: (...args: unknown[]) => mockAssignLicense(...args),
    unassignLicense: (...args: unknown[]) => mockUnassignLicense(...args),
    revealEmailPassword: (...args: unknown[]) => mockRevealEmailPassword(...args),
    copyEmailPassword: (...args: unknown[]) => mockCopyEmailPassword(...args),
    resetEmailPassword: (...args: unknown[]) => mockResetEmailPassword(...args),
  },
}));

vi.mock('../../services/organization.service', () => ({
  organizationService: {
    getOrganizations: vi.fn().mockResolvedValue([]),
    getDepartments: vi.fn().mockResolvedValue([]),
    getPositions: vi.fn().mockResolvedValue([]),
    getLocations: vi.fn().mockResolvedValue([]),
  },
}));

describe('DirectoryDetailDrawer Component Tests', () => {
  let container: HTMLDivElement;
  let currentRoot: Root | null = null;

  beforeEach(() => {
    container = document.createElement('div');
    document.body.appendChild(container);
    vi.clearAllMocks();
    mockGetUserAssets.mockResolvedValue([mockAsset]);
    mockGetUserLicenses.mockResolvedValue([mockLicenseAssignment]);
    mockGetAvailableAssets.mockResolvedValue([mockAvailableAsset]);
    mockGetAvailableLicenses.mockResolvedValue([mockAvailableLicense]);
  });

  afterEach(async () => {
    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    if (currentRoot) {
      await act(async () => {
        currentRoot?.unmount();
      });
      currentRoot = null;
    }
    if (container.parentNode) {
      document.body.removeChild(container);
    }
    document
      .querySelectorAll('.ant-modal-root, .ant-modal-wrap, .ant-drawer, .ant-popover')
      .forEach((el) => el.remove());
  });

  const renderComponent = async () => {
    const root = createRoot(container);
    currentRoot = root;
    await act(async () => {
      root.render(
        createElement(
          MemoryRouter,
          null,
          createElement(
            ConfigProvider,
            null,
            createElement(
              App,
              null,
              createElement(EmployeesTab, {
                employees: [mockUser],
                loading: false,
                onRefresh: vi.fn(),
                createModalOpen: false,
                setCreateModalOpen: vi.fn(),
                importModalOpen: false,
                setImportModalOpen: vi.fn(),
              }),
            ),
          ),
        ),
      );
    });

    await act(async () => {
      await new Promise((resolve) => setTimeout(resolve, 60));
    });

    return root;
  };

  it('renders employee table with AD status badge and opens detail drawer upon eye click', async () => {
    await renderComponent();

    // Verify AD tag is visible in table
    expect(container.textContent).toContain('John Doe');
    expect(container.textContent).toContain('AD');

    // Click View Details (eye button)
    const eyeBtn = Array.from(container.querySelectorAll('button .anticon-eye')).map((icon) =>
      icon.closest('button'),
    )[0];
    expect(eyeBtn).toBeDefined();

    await act(async () => {
      eyeBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    // Verify Drawer is open with header and tabs
    const drawer = document.querySelector('.ant-drawer');
    expect(drawer).not.toBeNull();
    expect(drawer?.textContent).toContain('John Doe');
    expect(drawer?.textContent).toContain('#63020099');
    expect(drawer?.textContent).toContain('General Info');
    expect(drawer?.textContent).toContain('AD & Email');
    expect(drawer?.textContent).toContain('Devices');
    expect(drawer?.textContent).toContain('Licenses');

    // Confirm that getUserAssets and getUserLicenses were called
    expect(mockGetUserAssets).toHaveBeenCalledWith('emp-detail-1');
    expect(mockGetUserLicenses).toHaveBeenCalledWith('emp-detail-1');
  });

  it('navigates to AD & Email tab and tests password reveal, copy, and reset modal', async () => {
    await renderComponent();

    // Open Drawer
    const eyeBtn = container.querySelector('button .anticon-eye')?.closest('button');
    await act(async () => {
      eyeBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    // Click 'AD & Email' tab
    const adEmailTab = Array.from(document.querySelectorAll('.ant-tabs-tab')).find((tab) =>
      tab.textContent?.includes('AD & Email'),
    );
    expect(adEmailTab).toBeDefined();

    await act(async () => {
      (adEmailTab as HTMLElement)?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    const drawer = document.querySelector('.ant-drawer');
    // Check AD domain details
    expect(drawer?.textContent).toContain('Active Directory Domain Join');
    expect(drawer?.textContent).toContain('uims.internal');
    expect(drawer?.textContent).toContain('VN-IT-WS01');

    // Check Email credentials section
    expect(drawer?.textContent).toContain('Enterprise Email Account & Credentials');
    expect(drawer?.textContent).toContain('johndoe@youngonevn.com');
    expect(drawer?.textContent).toContain('Encrypted at Rest');

    // Click Reveal button
    const revealBtn = Array.from(document.querySelectorAll('.ant-drawer button')).find((btn) =>
      btn.textContent?.includes('Reveal'),
    ) as HTMLButtonElement | undefined;
    expect(revealBtn).toBeDefined();

    await act(async () => {
      revealBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    expect(mockRevealEmailPassword).toHaveBeenCalledWith('emp-detail-1');
    expect(drawer?.textContent).toContain('SuperSecretDecryptedPass123!');

    // Click Reset button to open password reset modal
    const resetBtn = Array.from(document.querySelectorAll('.ant-drawer button')).find((btn) =>
      btn.textContent?.includes('Reset'),
    ) as HTMLButtonElement | undefined;
    expect(resetBtn).toBeDefined();

    await act(async () => {
      resetBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    const resetModalTitle = document.querySelector('.ant-modal-title');
    expect(resetModalTitle?.textContent).toContain('Reset Email Password');
    expect(resetModalTitle?.textContent).toContain('johndoe@youngonevn.com');
  });

  it('navigates to Devices tab and verifies assigned device listing and assign device modal', async () => {
    await renderComponent();

    // Open Drawer
    const eyeBtn = container.querySelector('button .anticon-eye')?.closest('button');
    await act(async () => {
      eyeBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    // Click 'Devices' tab
    const devicesTab = Array.from(document.querySelectorAll('.ant-tabs-tab')).find((tab) =>
      tab.textContent?.includes('Devices'),
    );
    expect(devicesTab).toBeDefined();

    await act(async () => {
      (devicesTab as HTMLElement)?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    const drawer = document.querySelector('.ant-drawer');
    expect(drawer?.textContent).toContain('AST-NB-001');
    expect(drawer?.textContent).toContain('ThinkPad T14 Gen 4');

    // Click Assign Device button
    const assignDeviceBtn = Array.from(document.querySelectorAll('.ant-drawer button')).find(
      (btn) => btn.textContent?.includes('Assign Device'),
    ) as HTMLButtonElement | undefined;
    expect(assignDeviceBtn).toBeDefined();

    await act(async () => {
      assignDeviceBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    expect(mockGetAvailableAssets).toHaveBeenCalled();
    const modalTitle = document.querySelector('.ant-modal-title');
    expect(modalTitle?.textContent).toContain('Assign Equipment to John Doe');
  });

  it('navigates to Licenses tab and verifies assigned license listing and assign license modal', async () => {
    await renderComponent();

    // Open Drawer
    const eyeBtn = container.querySelector('button .anticon-eye')?.closest('button');
    await act(async () => {
      eyeBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    // Click 'Licenses' tab
    const licensesTab = Array.from(document.querySelectorAll('.ant-tabs-tab')).find((tab) =>
      tab.textContent?.includes('Licenses'),
    );
    expect(licensesTab).toBeDefined();

    await act(async () => {
      (licensesTab as HTMLElement)?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    const drawer = document.querySelector('.ant-drawer');
    expect(drawer?.textContent).toContain('Microsoft 365 E5');

    // Click Assign License button
    const assignLicenseBtn = Array.from(document.querySelectorAll('.ant-drawer button')).find(
      (btn) => btn.textContent?.includes('Assign License'),
    ) as HTMLButtonElement | undefined;
    expect(assignLicenseBtn).toBeDefined();

    await act(async () => {
      assignLicenseBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    expect(mockGetAvailableLicenses).toHaveBeenCalled();
    const modalTitle = document.querySelector('.ant-modal-title');
    expect(modalTitle?.textContent).toContain('Assign Software License to John Doe');
  });

  it('verifies balanced single-column layout in viewer drawer eliminating horizontal scrollbar', async () => {
    await renderComponent();

    // Open Viewer Drawer
    const eyeBtn = container.querySelector('button .anticon-eye')?.closest('button');
    await act(async () => {
      eyeBtn?.click();
      await new Promise((resolve) => setTimeout(resolve, 80));
    });

    const drawer = document.querySelector('.ant-drawer');
    expect(drawer).not.toBeNull();

    // Check that semantic sections are present in General Info
    expect(drawer?.textContent).toContain('Personal & Contact Information');
    expect(drawer?.textContent).toContain('Organizational Hierarchy & Facility');
    expect(drawer?.textContent).toContain('Custody & Assigned Resources');

    // Verify all rows in Descriptions have single-column layout (1 label + 1 content cell, no 4-cell cramped rows)
    const rows = drawer?.querySelectorAll('.ant-descriptions-row');
    expect(rows && rows.length > 0).toBe(true);
    rows?.forEach((row) => {
      const cells = row.children;
      // In a column={1} bordered Descriptions table, each row consists of 1 th and 1 td (2 cells total)
      expect(cells.length).toBe(2);
    });

    // Verify drawer body enforces overflow-x hidden
    const drawerBody = drawer?.querySelector('.ant-drawer-body') as HTMLElement | null;
    expect(drawerBody).not.toBeNull();
    expect(drawerBody?.style.overflowX).toBe('hidden');
  });
});
