import type {
  Asset,
  BatchImportDirectoryResponse,
  BatchImportDirectoryUserItem,
  CreateDirectoryGroupDto,
  CreateDirectoryUserDto,
  DirectoryGroup,
  DirectorySummaryStats,
  DirectoryUser,
  DirectoryUserQueryDto,
  DomainSyncResult,
  License,
  LicenseAssignment,
  ResetEmailPasswordDto,
  RevealEmailPasswordResponseDto,
  UpdateDirectoryGroupDto,
  UpdateDirectoryUserDto,
} from '@uims/shared-types';
import { api } from './api';

export type {
  Asset,
  BatchImportDirectoryResponse,
  BatchImportDirectoryUserItem,
  CreateDirectoryGroupDto,
  CreateDirectoryUserDto,
  DirectoryGroup,
  DirectorySummaryStats,
  DirectoryUser,
  DirectoryUserQueryDto,
  DomainSyncResult,
  License,
  LicenseAssignment,
  ResetEmailPasswordDto,
  RevealEmailPasswordResponseDto,
  UpdateDirectoryGroupDto,
  UpdateDirectoryUserDto,
};

export interface PaginatedDirectoryUsersResponse {
  items: DirectoryUser[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export const directoryService = {
  getStats: async (): Promise<DirectorySummaryStats> => {
    const res = await api.get('/directory/stats');
    return res.data.data || res.data;
  },

  getEmployees: async (
    params?: DirectoryUserQueryDto,
  ): Promise<PaginatedDirectoryUsersResponse> => {
    const res = await api.get('/directory/users', { params });
    const data = res.data.data || res.data;
    if (Array.isArray(data)) {
      return {
        items: data,
        total: data.length,
        page: 1,
        pageSize: data.length,
        totalPages: 1,
      };
    }
    return data;
  },

  getEmployee: async (id: string): Promise<DirectoryUser> => {
    const res = await api.get(`/directory/users/${id}`);
    return res.data.data || res.data;
  },

  createEmployee: async (data: CreateDirectoryUserDto): Promise<DirectoryUser> => {
    const res = await api.post('/directory/users', data);
    return res.data.data || res.data;
  },

  updateEmployee: async (id: string, data: UpdateDirectoryUserDto): Promise<DirectoryUser> => {
    const res = await api.patch(`/directory/users/${id}`, data);
    return res.data.data || res.data;
  },

  deleteEmployee: async (id: string): Promise<void> => {
    await api.delete(`/directory/users/${id}`);
  },

  // --- Audited Email Credential Operations ---

  revealEmailPassword: async (id: string): Promise<RevealEmailPasswordResponseDto> => {
    const res = await api.get(`/directory/users/${id}/email-password`);
    return res.data.data || res.data;
  },

  copyEmailPassword: async (id: string): Promise<{ success: boolean }> => {
    const res = await api.post(`/directory/users/${id}/email-password/copy`);
    return res.data.data || res.data;
  },

  resetEmailPassword: async (
    id: string,
    data?: ResetEmailPasswordDto,
  ): Promise<{ success: boolean; autoGenerated: boolean; password?: string }> => {
    const res = await api.post(`/directory/users/${id}/email-password/reset`, data || {});
    return res.data.data || res.data;
  },

  // --- Hardware Device (Asset) Management ---

  getUserAssets: async (userId: string): Promise<Asset[]> => {
    const res = await api.get(`/directory/users/${userId}/assets`);
    return res.data.data || res.data;
  },

  assignAsset: async (userId: string, assetId: string): Promise<Asset> => {
    const res = await api.post(`/directory/users/${userId}/assets/${assetId}`);
    return res.data.data || res.data;
  },

  unassignAsset: async (
    userId: string,
    assetId: string,
  ): Promise<{ success: boolean; asset: Asset }> => {
    const res = await api.delete(`/directory/users/${userId}/assets/${assetId}`);
    return res.data.data || res.data;
  },

  getAvailableAssets: async (): Promise<Asset[]> => {
    const res = await api.get('/directory/available-assets');
    return res.data.data || res.data;
  },

  // --- Software License Management ---

  getUserLicenses: async (
    userId: string,
  ): Promise<Array<LicenseAssignment & { license: License }>> => {
    const res = await api.get(`/directory/users/${userId}/licenses`);
    return res.data.data || res.data;
  },

  assignLicense: async (userId: string, licenseId: string): Promise<LicenseAssignment> => {
    const res = await api.post(`/directory/users/${userId}/licenses/${licenseId}`);
    return res.data.data || res.data;
  },

  unassignLicense: async (userId: string, assignmentId: string): Promise<{ success: boolean }> => {
    const res = await api.delete(`/directory/users/${userId}/licenses/${assignmentId}`);
    return res.data.data || res.data;
  },

  getAvailableLicenses: async (): Promise<License[]> => {
    const res = await api.get('/directory/available-licenses');
    return res.data.data || res.data;
  },

  // --- Group & Domain Sync Operations ---

  getGroups: async (): Promise<DirectoryGroup[]> => {
    const res = await api.get('/directory/groups');
    return res.data.data || res.data;
  },

  createGroup: async (data: CreateDirectoryGroupDto): Promise<DirectoryGroup> => {
    const res = await api.post('/directory/groups', data);
    return res.data.data || res.data;
  },

  updateGroup: async (id: string, data: UpdateDirectoryGroupDto): Promise<DirectoryGroup> => {
    const res = await api.patch(`/directory/groups/${id}`, data);
    return res.data.data || res.data;
  },

  deleteGroup: async (id: string): Promise<void> => {
    await api.delete(`/directory/groups/${id}`);
  },

  syncDomain: async (): Promise<DomainSyncResult> => {
    const res = await api.post('/directory/sync-domain');
    return res.data.data || res.data;
  },

  exportEmployees: async (): Promise<Record<string, unknown>[]> => {
    const res = await api.get('/directory/export');
    return res.data.data || res.data;
  },

  importEmployees: async (
    users: BatchImportDirectoryUserItem[],
  ): Promise<BatchImportDirectoryResponse> => {
    const res = await api.post('/directory/import', { users });
    return res.data.data || res.data;
  },
};
