import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const connectionString =
  process.env.DATABASE_URL ||
  'postgresql://uims:uims_secret_2026@localhost:5433/uims_db?schema=public';
const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🚀 Starting Enterprise Database Seed for UIMS...');

  // Clean existing tables for fresh seed
  console.log('🧹 Clearing legacy records for clean enterprise seeding...');
  await prisma.ticketComment.deleteMany();
  await prisma.ticket.deleteMany();
  await prisma.licenseAssignment.deleteMany();
  await prisma.assetHistory.deleteMany();
  await prisma.notification.deleteMany();
  await prisma.auditLog.deleteMany();
  await prisma.directoryMembership.deleteMany();
  await prisma.directoryGroup.deleteMany();
  await prisma.directoryUser.deleteMany();
  await prisma.emailAccount.deleteMany();
  await prisma.iPAddress.deleteMany();
  await prisma.subnet.deleteMany();
  await prisma.inventoryItem.deleteMany();
  await prisma.asset.deleteMany();
  await prisma.license.deleteMany();
  await prisma.reportSchedule.deleteMany();

  // 1. Password Hashes
  const defaultPasswordHash = await bcrypt.hash('password123', 10);
  const adminPasswordHash = await bcrypt.hash('Admin@2026', 10);

  // 2. Roles & Permissions
  const superAdminRole = await prisma.role.upsert({
    where: { name: 'Super Admin' },
    update: {},
    create: {
      name: 'Super Admin',
      description: 'Super Administrator with unrestricted enterprise access and audit authority',
    },
  });

  const adminRole = await prisma.role.upsert({
    where: { name: 'Admin' },
    update: {},
    create: { name: 'Admin', description: 'System and Infrastructure Administrator' },
  });

  const techRole = await prisma.role.upsert({
    where: { name: 'Technician' },
    update: {},
    create: { name: 'Technician', description: 'IT Helpdesk & Field Technician Specialist' },
  });

  const auditorRole = await prisma.role.upsert({
    where: { name: 'Auditor' },
    update: {},
    create: { name: 'Auditor', description: 'SOC2 Type II & ISO 27001 Compliance Auditor' },
  });

  const managerRole = await prisma.role.upsert({
    where: { name: 'Manager' },
    update: {},
    create: { name: 'Manager', description: 'Department Team Lead & Resource Approver' },
  });

  const employeeRole = await prisma.role.upsert({
    where: { name: 'Employee' },
    update: {},
    create: { name: 'Employee', description: 'Standard Enterprise Employee' },
  });

  // 3. System Login Users
  const userAdminLocal = await prisma.user.upsert({
    where: { email: 'admin@uims.local' },
    update: {
      passwordHash: adminPasswordHash,
      roleId: superAdminRole.id,
      roleName: 'Super Admin',
      firstName: 'System',
      lastName: 'Administrator',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
    },
    create: {
      email: 'admin@uims.local',
      firstName: 'System',
      lastName: 'Administrator',
      roleId: superAdminRole.id,
      roleName: 'Super Admin',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      phone: '+1 (555) 100-2000',
      passwordHash: adminPasswordHash,
    },
  });

  const userAlex = await prisma.user.upsert({
    where: { email: 'admin@uims.internal' },
    update: {
      passwordHash: defaultPasswordHash,
      roleId: superAdminRole.id,
      roleName: 'Super Admin',
      firstName: 'Alex',
      lastName: 'Johnson',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
    },
    create: {
      email: 'admin@uims.internal',
      firstName: 'Alex',
      lastName: 'Johnson',
      roleId: superAdminRole.id,
      roleName: 'Super Admin',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      phone: '+1 (555) 234-5678',
      passwordHash: defaultPasswordHash,
    },
  });

  const userSarah = await prisma.user.upsert({
    where: { email: 'sarah.chen@company.com' },
    update: {
      passwordHash: defaultPasswordHash,
      roleId: techRole.id,
      roleName: 'IT Specialist',
    },
    create: {
      email: 'sarah.chen@company.com',
      firstName: 'Sarah',
      lastName: 'Chen',
      roleId: techRole.id,
      roleName: 'IT Specialist',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
      location: 'SF HQ - Tech Bay',
      phone: '+1 (555) 345-6789',
      passwordHash: defaultPasswordHash,
    },
  });

  const userMichael = await prisma.user.upsert({
    where: { email: 'michael.wong@company.com' },
    update: {
      passwordHash: defaultPasswordHash,
      roleId: adminRole.id,
      roleName: 'Network Architect',
    },
    create: {
      email: 'michael.wong@company.com',
      firstName: 'Michael',
      lastName: 'Wong',
      roleId: adminRole.id,
      roleName: 'Network Architect',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      phone: '+1 (555) 345-1122',
      passwordHash: defaultPasswordHash,
    },
  });

  const userMarcusBell = await prisma.user.upsert({
    where: { email: 'compliance@uims.internal' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'compliance@uims.internal',
      firstName: 'Marcus',
      lastName: 'Bell',
      roleId: auditorRole.id,
      roleName: 'Lead Auditor',
      status: 'ACTIVE',
      department: 'Security & Compliance',
      location: 'London Hub',
      phone: '+44 20 7946 0912',
      passwordHash: defaultPasswordHash,
    },
  });

  const userDavidKim = await prisma.user.upsert({
    where: { email: 'david.kim@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'david.kim@company.com',
      firstName: 'David',
      lastName: 'Kim',
      roleId: employeeRole.id,
      roleName: 'Developer',
      status: 'ACTIVE',
      department: 'Engineering',
      location: 'Remote - US East',
      phone: '+1 (555) 567-8901',
      passwordHash: defaultPasswordHash,
    },
  });

  const userSophiaPatel = await prisma.user.upsert({
    where: { email: 'sophia.patel@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'sophia.patel@company.com',
      firstName: 'Sophia',
      lastName: 'Patel',
      roleId: employeeRole.id,
      roleName: 'Developer',
      status: 'ACTIVE',
      department: 'Engineering',
      location: 'SF HQ - Tech Bay',
      phone: '+1 (555) 567-2233',
      passwordHash: defaultPasswordHash,
    },
  });

  const userLiamNguyen = await prisma.user.upsert({
    where: { email: 'liam.nguyen@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'liam.nguyen@company.com',
      firstName: 'Liam',
      lastName: 'Nguyen',
      roleId: employeeRole.id,
      roleName: 'Developer',
      status: 'ACTIVE',
      department: 'Engineering',
      location: 'Remote - US West',
      phone: '+1 (555) 567-4455',
      passwordHash: defaultPasswordHash,
    },
  });

  const userCarlosMendez = await prisma.user.upsert({
    where: { email: 'carlos.mendez@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'carlos.mendez@company.com',
      firstName: 'Carlos',
      lastName: 'Mendez',
      roleId: employeeRole.id,
      roleName: 'Developer',
      status: 'ACTIVE',
      department: 'Engineering',
      location: 'NY HQ - Floor 4',
      phone: '+1 (555) 567-7788',
      passwordHash: defaultPasswordHash,
    },
  });

  const userMarcusVance = await prisma.user.upsert({
    where: { email: 'marcus.vance@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'marcus.vance@company.com',
      firstName: 'Marcus',
      lastName: 'Vance',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE',
      department: 'Product & Design',
      location: 'NY HQ - Floor 4',
      phone: '+1 (555) 456-7890',
      passwordHash: defaultPasswordHash,
    },
  });

  const userChloeMartin = await prisma.user.upsert({
    where: { email: 'chloe.martin@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'chloe.martin@company.com',
      firstName: 'Chloe',
      lastName: 'Martin',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE',
      department: 'Product & Design',
      location: 'London Hub',
      phone: '+44 20 7946 0881',
      passwordHash: defaultPasswordHash,
    },
  });

  const userElena = await prisma.user.upsert({
    where: { email: 'elena.rostova@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'elena.rostova@company.com',
      firstName: 'Elena',
      lastName: 'Rostova',
      roleId: managerRole.id,
      roleName: 'Manager',
      status: 'ACTIVE',
      department: 'Marketing',
      location: 'London Hub',
      phone: '+1 (555) 678-9012',
      passwordHash: defaultPasswordHash,
    },
  });

  const userRobertTorres = await prisma.user.upsert({
    where: { email: 'robert.torres@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'robert.torres@company.com',
      firstName: 'Robert',
      lastName: 'Torres',
      roleId: managerRole.id,
      roleName: 'Manager',
      status: 'ACTIVE',
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      phone: '+1 (555) 678-3344',
      passwordHash: defaultPasswordHash,
    },
  });

  const userLisaWang = await prisma.user.upsert({
    where: { email: 'lisa.wang@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'lisa.wang@company.com',
      firstName: 'Lisa',
      lastName: 'Wang',
      roleId: managerRole.id,
      roleName: 'Manager',
      status: 'ACTIVE',
      department: 'Finance',
      location: 'Singapore Hub',
      phone: '+65 6789 0123',
      passwordHash: defaultPasswordHash,
    },
  });

  const userRachelAdams = await prisma.user.upsert({
    where: { email: 'rachel.adams@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'rachel.adams@company.com',
      firstName: 'Rachel',
      lastName: 'Adams',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE',
      department: 'Human Resources',
      location: 'NY HQ - Floor 5',
      phone: '+1 (555) 890-1234',
      passwordHash: defaultPasswordHash,
    },
  });

  const userJamesWilson = await prisma.user.upsert({
    where: { email: 'james.wilson@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'james.wilson@company.com',
      firstName: 'James',
      lastName: 'Wilson',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE',
      department: 'Legal & Governance',
      location: 'NY HQ - Floor 5',
      phone: '+1 (555) 901-2345',
      passwordHash: defaultPasswordHash,
    },
  });

  const userHannahScott = await prisma.user.upsert({
    where: { email: 'hannah.scott@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'hannah.scott@company.com',
      firstName: 'Hannah',
      lastName: 'Scott',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE',
      department: 'Sales',
      location: 'Remote - US Central',
      phone: '+1 (555) 901-6789',
      passwordHash: defaultPasswordHash,
    },
  });

  const userThomas = await prisma.user.upsert({
    where: { email: 'thomas.wright@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'thomas.wright@company.com',
      firstName: 'Thomas',
      lastName: 'Wright',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'SUSPENDED',
      department: 'Engineering',
      location: 'Remote - EMEA',
      phone: '+1 (555) 789-0123',
      passwordHash: defaultPasswordHash,
    },
  });

  const userJessica = await prisma.user.upsert({
    where: { email: 'jessica.taylor@company.com' },
    update: { passwordHash: defaultPasswordHash },
    create: {
      email: 'jessica.taylor@company.com',
      firstName: 'Jessica',
      lastName: 'Taylor',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'INACTIVE',
      department: 'Marketing',
      location: 'London Hub',
      phone: '+44 20 7946 0999',
      passwordHash: defaultPasswordHash,
    },
  });

  // 4. Locations
  const locNYF4 = await prisma.location.upsert({
    where: { id: 'loc-ny-f4' },
    update: {},
    create: {
      id: 'loc-ny-f4',
      name: 'NY HQ - Floor 4',
      building: 'Empire State Tech Hub',
      floor: 'Floor 4',
      room: 'Open Workspace & Tech Bay',
      address: '350 5th Ave, New York, NY 10118',
    },
  });

  const locNYF5 = await prisma.location.upsert({
    where: { id: 'loc-ny-f5' },
    update: {},
    create: {
      id: 'loc-ny-f5',
      name: 'NY HQ - Floor 5',
      building: 'Empire State Tech Hub',
      floor: 'Floor 5',
      room: 'Executive Suite & Boardroom',
      address: '350 5th Ave, New York, NY 10118',
    },
  });

  const locSF = await prisma.location.upsert({
    where: { id: 'loc-sf-bay' },
    update: {},
    create: {
      id: 'loc-sf-bay',
      name: 'SF HQ - Tech Bay',
      building: 'Mission Bay Center',
      floor: 'Floor 2',
      room: 'IT Tech Lab & Prototyping Bay',
      address: '500 Howard St, San Francisco, CA 94105',
    },
  });

  const locLondon = await prisma.location.upsert({
    where: { id: 'loc-london' },
    update: {},
    create: {
      id: 'loc-london',
      name: 'London Global Hub',
      building: 'Bishopsgate Tower',
      floor: 'Floor 12',
      room: 'EMEA Operations Center',
      address: '100 Bishopsgate, London EC2N 4AG, UK',
    },
  });

  const locSingapore = await prisma.location.upsert({
    where: { id: 'loc-singapore' },
    update: {},
    create: {
      id: 'loc-singapore',
      name: 'Singapore Regional Hub',
      building: 'Marina Bay Financial Centre',
      floor: 'Floor 28',
      room: 'APAC Enterprise Suite',
      address: '1 Marina Blvd, Singapore 018989',
    },
  });

  const locDCNY4 = await prisma.location.upsert({
    where: { id: 'loc-dc-ny4' },
    update: {},
    create: {
      id: 'loc-dc-ny4',
      name: 'Equinix NY4 Data Center',
      building: 'Equinix NY4 Facility',
      floor: 'Secure Server Vault',
      room: 'Cage B-04 / Rack R01-R04',
      address: '755 Secaucus Rd, Secaucus, NJ 07094',
    },
  });

  const locDCSV5 = await prisma.location.upsert({
    where: { id: 'loc-dc-sv5' },
    update: {},
    create: {
      id: 'loc-dc-sv5',
      name: 'Equinix SV5 Silicon Valley DC',
      building: 'Equinix SV5 Facility',
      floor: 'Floor 1 Compute Row',
      room: 'Cage S-12 / Rack K08',
      address: '1111 Equinix Way, San Jose, CA 95131',
    },
  });

  // 5. Asset Categories
  const catLaptop = await prisma.assetCategory.upsert({
    where: { id: 'cat-laptop' },
    update: {},
    create: {
      id: 'cat-laptop',
      name: 'Laptop',
      description: 'Workstation laptops, MacBooks & ultrabooks',
    },
  });

  const catDesktop = await prisma.assetCategory.upsert({
    where: { id: 'cat-desktop' },
    update: {},
    create: {
      id: 'cat-desktop',
      name: 'Desktop',
      description: 'High-performance engineering workstations',
    },
  });

  const catServer = await prisma.assetCategory.upsert({
    where: { id: 'cat-server' },
    update: {},
    create: {
      id: 'cat-server',
      name: 'Server',
      description: '2U/4U Rackmount compute and virtualization hosts',
    },
  });

  const catNetworking = await prisma.assetCategory.upsert({
    where: { id: 'cat-networking' },
    update: {},
    create: {
      id: 'cat-networking',
      name: 'Networking',
      description: 'Managed switches, edge routers & firewalls',
    },
  });

  const catMonitor = await prisma.assetCategory.upsert({
    where: { id: 'cat-monitor' },
    update: {},
    create: {
      id: 'cat-monitor',
      name: 'Monitor',
      description: '4K, 5K Retina & Ultrawide design displays',
    },
  });

  const catStorage = await prisma.assetCategory.upsert({
    where: { id: 'cat-storage' },
    update: {},
    create: {
      id: 'cat-storage',
      name: 'Storage',
      description: 'Enterprise SAN/NAS arrays & backup appliances',
    },
  });

  const catMobile = await prisma.assetCategory.upsert({
    where: { id: 'cat-mobile' },
    update: {},
    create: {
      id: 'cat-mobile',
      name: 'Mobile',
      description: 'Corporate iPads, testing tablets & 5G devices',
    },
  });

  const catPeripherals = await prisma.assetCategory.upsert({
    where: { id: 'cat-peripherals' },
    update: {},
    create: {
      id: 'cat-peripherals',
      name: 'Peripherals',
      description: 'Thunderbolt 4 docks, conference A/V & printers',
    },
  });

  // 6. Hardware Assets (25 Real-World Assets)
  const assetDefinitions = [
    {
      assetTag: 'AST-1001',
      name: 'MacBook Pro 16" M3 Max',
      manufacturer: 'Apple',
      model: 'MacBookPro18,2 (Space Black)',
      serialNumber: 'C02G8392MD6R',
      status: 'IN_USE' as const,
      categoryId: catLaptop.id,
      assignedToId: userMarcusVance.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2024-02-10'),
      purchaseCost: 3499,
      warrantyExpiry: new Date('2027-02-10'),
      specs: {
        cpu: 'Apple M3 Max (16-Core CPU, 40-Core GPU)',
        ram: '64 GB Unified Memory',
        storage: '1 TB PCIe NVMe SSD',
        os: 'macOS Sonoma 14.6',
      },
      notes: 'Assigned to Principal Product Designer. Paired with CalDigit TS4 dock.',
    },
    {
      assetTag: 'AST-1002',
      name: 'Dell UltraSharp 32" 4K USB-C Hub Monitor',
      manufacturer: 'Dell',
      model: 'U3223QE (IPS Black)',
      serialNumber: 'CN-0N179F-74261',
      status: 'IN_USE' as const,
      categoryId: catMonitor.id,
      assignedToId: userMarcusVance.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2024-02-12'),
      purchaseCost: 899,
      warrantyExpiry: new Date('2027-02-12'),
      specs: {
        cpu: 'Display Controller SoC',
        ram: '4K UHD (3840x2160) 60Hz',
        storage: '90W USB-C PD + RJ45 Hub',
        os: 'Firmware v1.08',
      },
      notes: 'Design station primary color-calibrated display (98% DCI-P3).',
    },
    {
      assetTag: 'AST-1003',
      name: 'Dell PowerEdge R760 2U Rack Server',
      manufacturer: 'Dell Enterprise',
      model: 'PowerEdge R760 NVMe',
      serialNumber: '7X99KM4',
      status: 'IN_USE' as const,
      categoryId: catServer.id,
      assignedToId: userLiamNguyen.id,
      locationId: locDCNY4.id,
      purchaseDate: new Date('2023-11-20'),
      purchaseCost: 14850,
      warrantyExpiry: new Date('2028-11-20'),
      specs: {
        cpu: '2x Intel Xeon Platinum 8480+ (112 Cores / 224 Threads)',
        ram: '512 GB ECC DDR5-4800 Registered',
        storage: '8x 3.84TB NVMe U.2 SSD Hardware RAID 10',
        os: 'Ubuntu Server 24.04 LTS (Kernel 6.8)',
      },
      notes: 'Primary production Kubernetes worker node cluster (k8s-node-prod01).',
    },
    {
      assetTag: 'AST-1004',
      name: 'Dell PowerEdge R750 2U Virtualization Host',
      manufacturer: 'Dell Enterprise',
      model: 'PowerEdge R750 VMware Host',
      serialNumber: '8X9K3M2',
      status: 'IN_USE' as const,
      categoryId: catServer.id,
      assignedToId: userSarah.id,
      locationId: locDCSV5.id,
      purchaseDate: new Date('2023-05-10'),
      purchaseCost: 9200,
      warrantyExpiry: new Date('2028-05-10'),
      specs: {
        cpu: '2x Intel Xeon Gold 6330 (56 Cores)',
        ram: '256 GB ECC DDR4-3200',
        storage: '6x 1.92TB Enterprise SAS SSD',
        os: 'VMware ESXi 8.0 Update 2',
      },
      notes: 'Hosts internal core database replicas and staging compute nodes.',
    },
    {
      assetTag: 'AST-1005',
      name: 'Cisco Catalyst 9300 48-Port PoE+ Switch',
      manufacturer: 'Cisco Systems',
      model: 'C9300-48P-A',
      serialNumber: 'FOC2438L0K4',
      status: 'IN_USE' as const,
      categoryId: catNetworking.id,
      assignedToId: userMichael.id,
      locationId: locSF.id,
      purchaseDate: new Date('2022-11-01'),
      purchaseCost: 4500,
      warrantyExpiry: new Date('2027-11-01'),
      specs: {
        cpu: 'Cisco Quad-core x86 ASIC',
        ram: '16 GB DRAM',
        storage: '16 GB eMMC Flash',
        os: 'Cisco IOS XE 17.12.02',
      },
      notes: 'SF HQ core access switch. Powers 24 APs and wired developer desks.',
    },
    {
      assetTag: 'AST-1006',
      name: 'Cisco Nexus 93180YC-FX3 Spine Switch',
      manufacturer: 'Cisco Systems',
      model: 'N9K-C93180YC-FX3',
      serialNumber: 'FOC2612M8L1',
      status: 'IN_USE' as const,
      categoryId: catNetworking.id,
      assignedToId: userMichael.id,
      locationId: locDCNY4.id,
      purchaseDate: new Date('2023-04-18'),
      purchaseCost: 11200,
      warrantyExpiry: new Date('2028-04-18'),
      specs: {
        cpu: 'Cloud Scale ASIC Engine',
        ram: '32 GB DRAM',
        storage: '64 GB SSD',
        os: 'NX-OS 10.4(1)F',
      },
      notes: 'NY4 DC Top-of-Rack leaf switch with 48x 25G SFP28 and 6x 100G QSFP28.',
    },
    {
      assetTag: 'AST-1007',
      name: 'Fortinet FortiGate 200F Enterprise Firewall',
      manufacturer: 'Fortinet',
      model: 'FG-200F-BDL-950',
      serialNumber: 'FG200FTK23001844',
      status: 'IN_USE' as const,
      categoryId: catNetworking.id,
      assignedToId: userMichael.id,
      locationId: locDCNY4.id,
      purchaseDate: new Date('2023-08-01'),
      purchaseCost: 7800,
      warrantyExpiry: new Date('2026-08-01'),
      specs: {
        cpu: 'Fortinet CP9 & NP6XLite ASICs',
        ram: '8 GB Memory',
        storage: '32 GB Flash',
        os: 'FortiOS 7.4.3',
      },
      notes: 'Main edge security gateway with IPSec VPN, SSL inspection and threat protection.',
    },
    {
      assetTag: 'AST-1008',
      name: 'Lenovo ThinkPad X1 Carbon Gen 12',
      manufacturer: 'Lenovo',
      model: 'ThinkPad X1 Carbon 21KC',
      serialNumber: 'PF-49K98X',
      status: 'IN_USE' as const,
      categoryId: catLaptop.id,
      assignedToId: userDavidKim.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2024-04-05'),
      purchaseCost: 2199,
      warrantyExpiry: new Date('2027-04-05'),
      specs: {
        cpu: 'Intel Core Ultra 7 155H (16-Core / NPU AI Boost)',
        ram: '32 GB LPDDR5x-6400',
        storage: '1 TB PCIe 4.0 NVMe SSD',
        os: 'Ubuntu 24.04 LTS / Dual Boot Win 11',
      },
      notes: 'Issued to Lead Cloud Architect for multi-cloud container orchestration.',
    },
    {
      assetTag: 'AST-1009',
      name: 'Lenovo ThinkPad P16 Gen 2 Workstation',
      manufacturer: 'Lenovo',
      model: 'ThinkPad P16 21FA',
      serialNumber: 'PF-58M12L',
      status: 'IN_USE' as const,
      categoryId: catLaptop.id,
      assignedToId: userSophiaPatel.id,
      locationId: locSF.id,
      purchaseDate: new Date('2023-10-15'),
      purchaseCost: 3250,
      warrantyExpiry: new Date('2026-10-15'),
      specs: {
        cpu: 'Intel Core i9-13980HX (24-Core 5.6GHz)',
        ram: '64 GB DDR5-5200 ECC',
        storage: '2 TB PCIe 4.0 NVMe SSD',
        os: 'Fedora Workstation 40',
      },
      notes: 'High-performance AI model and database benchmarking machine.',
    },
    {
      assetTag: 'AST-1010',
      name: 'MacBook Pro 14" M3 Pro',
      manufacturer: 'Apple',
      model: 'MacBookPro18,3 (Silver)',
      serialNumber: 'C02H1883ND9P',
      status: 'IN_USE' as const,
      categoryId: catLaptop.id,
      assignedToId: userChloeMartin.id,
      locationId: locLondon.id,
      purchaseDate: new Date('2024-01-25'),
      purchaseCost: 2499,
      warrantyExpiry: new Date('2027-01-25'),
      specs: {
        cpu: 'Apple M3 Pro (12-Core CPU, 18-Core GPU)',
        ram: '36 GB Unified Memory',
        storage: '1 TB NVMe SSD',
        os: 'macOS Sonoma 14.5',
      },
      notes: 'London UX Research and prototyping lead machine.',
    },
    {
      assetTag: 'AST-1011',
      name: 'Apple MacBook Air 15" M3',
      manufacturer: 'Apple',
      model: 'MacBookAir15,2 (Midnight)',
      serialNumber: 'C02J4491QK3L',
      status: 'IN_USE' as const,
      categoryId: catLaptop.id,
      assignedToId: userElena.id,
      locationId: locLondon.id,
      purchaseDate: new Date('2024-03-10'),
      purchaseCost: 1699,
      warrantyExpiry: new Date('2027-03-10'),
      specs: {
        cpu: 'Apple M3 (8-Core CPU, 10-Core GPU)',
        ram: '24 GB Unified Memory',
        storage: '512 GB SSD',
        os: 'macOS Sonoma 14.5',
      },
      notes: 'Marketing executive deployment.',
    },
    {
      assetTag: 'AST-1012',
      name: 'Dell Precision 7680 Mobile Workstation',
      manufacturer: 'Dell',
      model: 'Precision 7680 UHD',
      serialNumber: '9K2M771',
      status: 'IN_USE' as const,
      categoryId: catLaptop.id,
      assignedToId: userCarlosMendez.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2023-09-05'),
      purchaseCost: 3100,
      warrantyExpiry: new Date('2026-09-05'),
      specs: {
        cpu: 'Intel Core i7-13850HX vPro (20-Core)',
        ram: '32 GB CAMM DDR5',
        storage: '1 TB NVMe Gen4 + NVIDIA RTX 3500 Ada',
        os: 'Windows 11 Pro Enterprise',
      },
      notes: 'Backend microservices profiling and load testing.',
    },
    {
      assetTag: 'AST-1013',
      name: 'Apple Studio Display 27" 5K Retina',
      manufacturer: 'Apple',
      model: 'Studio Display A2525',
      serialNumber: 'F17HK923MD99',
      status: 'IN_USE' as const,
      categoryId: catMonitor.id,
      assignedToId: userChloeMartin.id,
      locationId: locLondon.id,
      purchaseDate: new Date('2024-01-26'),
      purchaseCost: 1599,
      warrantyExpiry: new Date('2027-01-26'),
      specs: {
        cpu: 'Apple A13 Bionic (Center Stage & Spatial Audio)',
        ram: '5K Retina 5120x2880 Display',
        storage: '96W Thunderbolt 3 Passthrough',
        os: 'Studio Display Firmware v17.0',
      },
      notes: 'Paired with AST-1010 in London design studio.',
    },
    {
      assetTag: 'AST-1014',
      name: 'Dell UltraSharp 38" Curved USB-C Hub Monitor',
      manufacturer: 'Dell',
      model: 'U3824DW (WQHD+)',
      serialNumber: 'CN-08819A-48192',
      status: 'IN_USE' as const,
      categoryId: catMonitor.id,
      assignedToId: userDavidKim.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2023-12-01'),
      purchaseCost: 1250,
      warrantyExpiry: new Date('2026-12-01'),
      specs: {
        cpu: 'Dual KVM Controller Engine',
        ram: '3840x1600 WQHD+ 60Hz 21:9',
        storage: '2.5GbE LAN RJ45 + 90W PD',
        os: 'Firmware v1.03',
      },
      notes: 'Architecture dual-source side-by-side workstation screen.',
    },
    {
      assetTag: 'AST-1015',
      name: 'Synology RackStation RS3621xs+ Storage SAN',
      manufacturer: 'Synology Enterprise',
      model: 'RS3621xs+ 12-Bay',
      serialNumber: '2190Q8R39201',
      status: 'IN_USE' as const,
      categoryId: catStorage.id,
      assignedToId: userSarah.id,
      locationId: locDCNY4.id,
      purchaseDate: new Date('2023-03-14'),
      purchaseCost: 8900,
      warrantyExpiry: new Date('2028-03-14'),
      specs: {
        cpu: 'Intel Xeon D-1541 8-Core 2.7GHz',
        ram: '64 GB ECC DDR4',
        storage: '12x 18TB Seagate Exos Enterprise SAS (144TB Raw / RAID 6)',
        os: 'DSM 7.2.1 Enterprise',
      },
      notes: 'Internal NFS and iSCSI target for automated daily system snapshots.',
    },
    {
      assetTag: 'AST-1016',
      name: 'Apple iPad Pro 13" M4 (OLED, 512GB 5G)',
      manufacturer: 'Apple',
      model: 'iPad Pro 13 (A2925)',
      serialNumber: 'DMP99120KM4L',
      status: 'AVAILABLE' as const,
      categoryId: catMobile.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2024-05-20'),
      purchaseCost: 1499,
      warrantyExpiry: new Date('2026-05-20'),
      specs: {
        cpu: 'Apple M4 (9-Core CPU, 10-Core GPU)',
        ram: '8 GB Unified Memory',
        storage: '512 GB Tandem OLED Display + 5G',
        os: 'iPadOS 17.5',
      },
      notes: 'Available in Floor 4 IT Vault for field testing checkout.',
    },
    {
      assetTag: 'AST-1017',
      name: 'Apple iPad Air 11" M2 (128GB Wi-Fi)',
      manufacturer: 'Apple',
      model: 'iPad Air 11 (A2902)',
      serialNumber: 'DMP88319LK02',
      status: 'IN_USE' as const,
      categoryId: catMobile.id,
      assignedToId: userRachelAdams.id,
      locationId: locNYF5.id,
      purchaseDate: new Date('2024-05-22'),
      purchaseCost: 699,
      warrantyExpiry: new Date('2026-05-22'),
      specs: {
        cpu: 'Apple M2 (8-Core)',
        ram: '8 GB Unified Memory',
        storage: '128 GB Liquid Retina',
        os: 'iPadOS 17.5',
      },
      notes: 'People Operations onboarding kiosk and paperless signing tablet.',
    },
    {
      assetTag: 'AST-1018',
      name: 'Ubiquiti UniFi Dream Machine Special Edition',
      manufacturer: 'Ubiquiti Inc',
      model: 'UDM-SE Enterprise',
      serialNumber: '7483C211440A',
      status: 'IN_USE' as const,
      categoryId: catNetworking.id,
      assignedToId: userAlex.id,
      locationId: locLondon.id,
      purchaseDate: new Date('2023-07-11'),
      purchaseCost: 599,
      warrantyExpiry: new Date('2026-07-11'),
      specs: {
        cpu: 'Quad-Core ARM Cortex-A57 at 1.7GHz',
        ram: '4 GB DDR4',
        storage: '128 GB Integrated SSD + 10G SFP+',
        os: 'UniFi OS v3.2.12',
      },
      notes: 'London regional office security gateway & IDS/IPS controller.',
    },
    {
      assetTag: 'AST-1019',
      name: 'Ubiquiti UniFi U6 Enterprise Access Point',
      manufacturer: 'Ubiquiti Inc',
      model: 'U6-Enterprise (Wi-Fi 6E)',
      serialNumber: '7483C25561FA',
      status: 'IN_USE' as const,
      categoryId: catNetworking.id,
      assignedToId: userMichael.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2023-09-15'),
      purchaseCost: 299,
      warrantyExpiry: new Date('2026-09-15'),
      specs: {
        cpu: 'Broadcom Tri-Band Wi-Fi 6E SoC',
        ram: '1 GB Memory',
        storage: '10.2 Gbps Total Over-the-air Rate',
        os: 'UniFi AP Firmware v6.6.65',
      },
      notes: 'NY Office Floor 4 East Wing ceiling array AP.',
    },
    {
      assetTag: 'AST-1020',
      name: 'HP LaserJet Enterprise MFP M528dn Printer',
      manufacturer: 'HP Inc',
      model: 'LaserJet MFP M528dn',
      serialNumber: 'CNB1N39201',
      status: 'IN_USE' as const,
      categoryId: catPeripherals.id,
      assignedToId: userRobertTorres.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2022-08-10'),
      purchaseCost: 1450,
      warrantyExpiry: new Date('2025-08-10'),
      specs: {
        cpu: '1.2 GHz Processor',
        ram: '1.5 GB Memory',
        storage: '500 GB Encrypted Secure Hard Disk',
        os: 'HP FutureSmart 5 Firmware',
      },
      notes: 'Floor 4 secure badge-release printer with PIN verification.',
    },
    {
      assetTag: 'AST-1021',
      name: 'CalDigit TS4 Thunderbolt 4 Dock 18-Port',
      manufacturer: 'CalDigit',
      model: 'TS4-US-AMZ',
      serialNumber: 'CDTS48891024',
      status: 'IN_USE' as const,
      categoryId: catPeripherals.id,
      assignedToId: userMarcusVance.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2024-02-10'),
      purchaseCost: 399,
      warrantyExpiry: new Date('2026-02-10'),
      specs: {
        cpu: 'Intel Goshen Ridge JHL8440 Controller',
        ram: '98W Laptop Charging PD',
        storage: '18 I/O Ports with 2.5GbE Ethernet',
        os: 'Firmware v39.1',
      },
      notes: 'Primary desk hub for AST-1001 design station.',
    },
    {
      assetTag: 'AST-1022',
      name: 'Poly Studio X50 Video Bar & TC8 Controller',
      manufacturer: 'HP / Poly',
      model: 'Studio X50 (Zoom & Teams Native)',
      serialNumber: '8220019284AA',
      status: 'IN_USE' as const,
      categoryId: catPeripherals.id,
      assignedToId: userAlex.id,
      locationId: locNYF5.id,
      purchaseDate: new Date('2023-06-20'),
      purchaseCost: 3200,
      warrantyExpiry: new Date('2026-06-20'),
      specs: {
        cpu: 'Qualcomm Snapdragon 845 SoC',
        ram: '4 GB RAM + 4K Beamforming Camera Array',
        storage: 'Room Filling Acoustic Stereo Chambers',
        os: 'Poly VideoOS 4.1.2',
      },
      notes: 'Boardroom executive video telepresence conferencing bar.',
    },
    {
      assetTag: 'AST-1023',
      name: 'Lenovo ThinkPad X1 Carbon Gen 11 (RMA Service)',
      manufacturer: 'Lenovo',
      model: 'ThinkPad 21HM',
      serialNumber: 'PF-39K21L',
      status: 'MAINTENANCE' as const,
      categoryId: catLaptop.id,
      assignedToId: userSarah.id,
      locationId: locSF.id,
      purchaseDate: new Date('2023-08-14'),
      purchaseCost: 1950,
      warrantyExpiry: new Date('2026-08-14'),
      specs: {
        cpu: 'Intel Core i7-1365U vPro',
        ram: '32 GB LPDDR5-5200',
        storage: '512 GB PCIe 4.0 SSD',
        os: 'Windows 11 Pro 23H2',
      },
      notes: 'Sent to Lenovo Premier Support Depot for battery sensor replacement.',
    },
    {
      assetTag: 'AST-1024',
      name: 'Dell Latitude 5440 Laptop (Buffer Stock)',
      manufacturer: 'Dell',
      model: 'Latitude 5440 Business',
      serialNumber: '7N881M2',
      status: 'AVAILABLE' as const,
      categoryId: catLaptop.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2024-03-01'),
      purchaseCost: 1250,
      warrantyExpiry: new Date('2027-03-01'),
      specs: {
        cpu: 'Intel Core i5-1335U (10-Core)',
        ram: '16 GB DDR4-3200',
        storage: '512 GB NVMe SSD',
        os: 'Windows 11 Enterprise (Autopilot Ready)',
      },
      notes: 'Pre-imaged spare laptop in secure IT storage room.',
    },
    {
      assetTag: 'AST-1025',
      name: 'Apple MacBook Pro 13" M1 (Decommissioned)',
      manufacturer: 'Apple',
      model: 'MacBookPro17,1',
      serialNumber: 'C02D1839MD6R',
      status: 'RETIRED' as const,
      categoryId: catLaptop.id,
      locationId: locNYF4.id,
      purchaseDate: new Date('2020-12-10'),
      purchaseCost: 1499,
      warrantyExpiry: new Date('2023-12-10'),
      specs: {
        cpu: 'Apple M1 (8-Core)',
        ram: '16 GB Unified Memory',
        storage: '512 GB SSD (Data Sanitized DoD 5220.22-M)',
        os: 'macOS Big Sur (Wiped)',
      },
      notes: 'Retired after 4-year lifecycle completion. Certified certificate of destruction.',
    },
  ];

  for (const asset of assetDefinitions) {
    await prisma.asset.upsert({
      where: { assetTag: asset.assetTag },
      update: {},
      create: asset,
    });
  }

  // 7. Software Licenses & Enterprise Subscriptions (12 Real SaaS Licenses)
  const licenseDefinitions = [
    {
      id: 'lic-m365',
      name: 'Microsoft 365 E5 Enterprise Suite',
      vendor: 'Microsoft Corporation',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 150,
      usedSeats: 142,
      costPerSeat: 456,
      purchaseDate: new Date('2024-01-01'),
      expiryDate: new Date('2026-12-31'),
      licenseKey: 'MS-E5-9921-8834-KKL9-2026',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Core enterprise productivity, Purview DLP, Defender XDR and Entra ID P2.',
    },
    {
      id: 'lic-adobe',
      name: 'Adobe Creative Cloud All Apps Enterprise',
      vendor: 'Adobe Systems Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 30,
      usedSeats: 28,
      costPerSeat: 780,
      purchaseDate: new Date('2023-09-15'),
      expiryDate: new Date('2026-09-15'),
      licenseKey: 'ADB-CC-8392-1102-LKLM-PRO',
      status: 'EXPIRING_SOON' as const,
      autoRenew: false,
      notes: 'Renewal contract pending procurement approval with Adobe VIP reseller.',
    },
    {
      id: 'lic-jetbrains',
      name: 'JetBrains All Products Pack (Commercial)',
      vendor: 'JetBrains s.r.o.',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 45,
      usedSeats: 38,
      costPerSeat: 249,
      purchaseDate: new Date('2024-03-01'),
      expiryDate: new Date('2027-02-28'),
      licenseKey: 'JB-ALL-7731-9941-PPX1-2027',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Includes IntelliJ IDEA Ultimate, WebStorm, GoLand, PyCharm and RustRover.',
    },
    {
      id: 'lic-figma',
      name: 'Figma Enterprise Design Workspace',
      vendor: 'Figma Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 35,
      usedSeats: 32,
      costPerSeat: 540,
      purchaseDate: new Date('2023-11-30'),
      expiryDate: new Date('2026-11-30'),
      licenseKey: 'FIG-ENT-1192-3381-YYE4-TEAM',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Enterprise design system libraries and unlimited Dev Mode seats.',
    },
    {
      id: 'lic-github',
      name: 'GitHub Enterprise Cloud + Copilot Business',
      vendor: 'GitHub / Microsoft',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 60,
      usedSeats: 55,
      costPerSeat: 252,
      purchaseDate: new Date('2024-01-15'),
      expiryDate: new Date('2027-01-15'),
      licenseKey: 'GH-ENT-COPILOT-9982-1144',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Advanced Security (CodeQL, Dependabot) and AI code completions.',
    },
    {
      id: 'lic-crowdstrike',
      name: 'CrowdStrike Falcon Complete Endpoint EDR',
      vendor: 'CrowdStrike Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 200,
      usedSeats: 185,
      costPerSeat: 180,
      purchaseDate: new Date('2023-06-01'),
      expiryDate: new Date('2026-06-01'),
      licenseKey: 'CS-FALCON-CCID-91820492-X88',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: '24/7 Managed detection and response across all company laptops and servers.',
    },
    {
      id: 'lic-datadog',
      name: 'Datadog Enterprise APM & Pro Suite',
      vendor: 'Datadog Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 25,
      usedSeats: 22,
      costPerSeat: 1800,
      purchaseDate: new Date('2023-10-01'),
      expiryDate: new Date('2026-10-01'),
      licenseKey: 'DD-API-KEY-88491024-SYNTH',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Infrastructure metric collectors, APM distributed traces and synthetic tests.',
    },
    {
      id: 'lic-slack',
      name: 'Slack Enterprise Grid Plan',
      vendor: 'Slack Technologies / Salesforce',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 160,
      usedSeats: 148,
      costPerSeat: 180,
      purchaseDate: new Date('2024-01-01'),
      expiryDate: new Date('2026-12-31'),
      licenseKey: 'SLK-GRID-ORG-99218491-PROD',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Enterprise key management, unlimited channels and DLP audit streams.',
    },
    {
      id: 'lic-okta',
      name: 'Okta Workforce Identity Cloud (Adaptive MFA)',
      vendor: 'Okta Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 150,
      usedSeats: 145,
      costPerSeat: 72,
      purchaseDate: new Date('2024-01-01'),
      expiryDate: new Date('2026-12-31'),
      licenseKey: 'OKTA-TENANT-uims-internal.okta.com',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Universal Directory, Single Sign-On and Adaptive MFA with FastPass.',
    },
    {
      id: 'lic-zoom',
      name: 'Zoom Workplace Enterprise E4 Suite',
      vendor: 'Zoom Video Communications',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 80,
      usedSeats: 72,
      costPerSeat: 240,
      purchaseDate: new Date('2023-12-15'),
      expiryDate: new Date('2026-12-15'),
      licenseKey: 'ZM-ENT-99120-ROOMS-500',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Zoom Rooms, 500-attendee webinars and cloud meeting transcripts.',
    },
    {
      id: 'lic-salesforce',
      name: 'Salesforce Sales Cloud Unlimited Edition',
      vendor: 'Salesforce.com',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 20,
      usedSeats: 18,
      costPerSeat: 3600,
      purchaseDate: new Date('2024-02-01'),
      expiryDate: new Date('2027-01-31'),
      licenseKey: 'SFDC-ORG-00D5e000000XyZ1',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Global CRM and pipeline tracking for sales executive teams.',
    },
    {
      id: 'lic-vmware',
      name: 'VMware vSphere Enterprise Plus (v8.0)',
      vendor: 'Broadcom / VMware',
      type: 'PERPETUAL' as const,
      totalSeats: 8,
      usedSeats: 8,
      costPerSeat: 3500,
      purchaseDate: new Date('2023-05-01'),
      expiryDate: new Date('2028-05-01'),
      licenseKey: 'VMW-VSP-4491-0021-HH82-ESX8',
      status: 'ACTIVE' as const,
      autoRenew: false,
      notes: 'Per-CPU socket license with Tanzu Kubernetes grid integration.',
    },
  ];

  for (const lic of licenseDefinitions) {
    await prisma.license.upsert({
      where: { id: lic.id },
      update: {},
      create: lic,
    });
  }

  // 8. License Assignments to Users
  const licenseAssignments = [
    {
      licenseId: 'lic-m365',
      userId: userAlex.id,
      assignedName: 'Alex Johnson',
      assignedEmail: 'admin@uims.internal',
      department: 'IT & Infrastructure',
    },
    {
      licenseId: 'lic-m365',
      userId: userSarah.id,
      assignedName: 'Sarah Chen',
      assignedEmail: 'sarah.chen@company.com',
      department: 'IT & Infrastructure',
    },
    {
      licenseId: 'lic-m365',
      userId: userMichael.id,
      assignedName: 'Michael Wong',
      assignedEmail: 'michael.wong@company.com',
      department: 'IT & Infrastructure',
    },
    {
      licenseId: 'lic-m365',
      userId: userDavidKim.id,
      assignedName: 'David Kim',
      assignedEmail: 'david.kim@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-m365',
      userId: userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-m365',
      userId: userMarcusVance.id,
      assignedName: 'Marcus Vance',
      assignedEmail: 'marcus.vance@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-m365',
      userId: userElena.id,
      assignedName: 'Elena Rostova',
      assignedEmail: 'elena.rostova@company.com',
      department: 'Marketing',
    },
    {
      licenseId: 'lic-adobe',
      userId: userMarcusVance.id,
      assignedName: 'Marcus Vance',
      assignedEmail: 'marcus.vance@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-adobe',
      userId: userChloeMartin.id,
      assignedName: 'Chloe Martin',
      assignedEmail: 'chloe.martin@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-adobe',
      userId: userElena.id,
      assignedName: 'Elena Rostova',
      assignedEmail: 'elena.rostova@company.com',
      department: 'Marketing',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: userDavidKim.id,
      assignedName: 'David Kim',
      assignedEmail: 'david.kim@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: userLiamNguyen.id,
      assignedName: 'Liam Nguyen',
      assignedEmail: 'liam.nguyen@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: userCarlosMendez.id,
      assignedName: 'Carlos Mendez',
      assignedEmail: 'carlos.mendez@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-figma',
      userId: userMarcusVance.id,
      assignedName: 'Marcus Vance',
      assignedEmail: 'marcus.vance@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-figma',
      userId: userChloeMartin.id,
      assignedName: 'Chloe Martin',
      assignedEmail: 'chloe.martin@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-figma',
      userId: userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: userDavidKim.id,
      assignedName: 'David Kim',
      assignedEmail: 'david.kim@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: userLiamNguyen.id,
      assignedName: 'Liam Nguyen',
      assignedEmail: 'liam.nguyen@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: userCarlosMendez.id,
      assignedName: 'Carlos Mendez',
      assignedEmail: 'carlos.mendez@company.com',
      department: 'Engineering',
    },
  ];

  await prisma.licenseAssignment.createMany({
    data: licenseAssignments,
    skipDuplicates: true,
  });

  // 9. Hardware Inventory Items (12 Consumable & Hardware Stock SKUs)
  const inventoryItems = [
    {
      sku: 'CAB-CAT6A-2M-BLU',
      name: 'Cat6a 10Gbps Snagless RJ45 Patch Cable (2m, Blue)',
      category: 'Cables & Adapters',
      quantity: 64,
      minThreshold: 20,
      unitCost: 6.5,
      location: 'Storage Room A',
      binNumber: 'Bin A-04',
      supplier: 'Monoprice B2B Direct',
      notes: 'Standard high-speed desk patch cables.',
    },
    {
      sku: 'ACC-MSE-MX3S-GRY',
      name: 'Logitech MX Master 3S Wireless Performance Mouse',
      category: 'Peripherals',
      quantity: 2,
      minThreshold: 5,
      unitCost: 99.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 2',
      supplier: 'CDW Direct Enterprise',
      notes: 'Low stock warning! Restock order PO-9921 placed.',
    },
    {
      sku: 'ACC-DOCK-TS4-TB4',
      name: 'CalDigit TS4 Thunderbolt 4 Dock 18-Port (Spare)',
      category: 'Peripherals',
      quantity: 5,
      minThreshold: 3,
      unitCost: 379.0,
      location: 'Storage Room B',
      binNumber: 'Cabinet Secure-1',
      supplier: 'B&H Photo Video B2B',
      notes: 'Emergency hot-swap docks for executive boardrooms.',
    },
    {
      sku: 'RAM-DDR5-32G-SODIMM',
      name: 'Crucial 32GB DDR5-5600 SODIMM Laptop Memory Module',
      category: 'Storage & RAM',
      quantity: 14,
      minThreshold: 6,
      unitCost: 110.0,
      location: 'IT Tech Lab',
      binNumber: 'Anti-Static Drawer 3',
      supplier: 'Newegg Business',
      notes: 'Laptop RAM upgrade kit for engineering workstations.',
    },
    {
      sku: 'SSD-NVME-2TB-SAMS',
      name: 'Samsung 990 Pro 2TB PCIe 4.0 NVMe SSD M.2',
      category: 'Storage & RAM',
      quantity: 8,
      minThreshold: 4,
      unitCost: 175.0,
      location: 'IT Tech Lab',
      binNumber: 'Anti-Static Drawer 1',
      supplier: 'CDW Direct Enterprise',
      notes: 'Fast internal storage drives for engineer machine refreshes.',
    },
    {
      sku: 'PWR-APL-140W-USBC',
      name: 'Apple 140W USB-C Power Adapter + 2m MagSafe 3 Cable',
      category: 'Power & Battery',
      quantity: 16,
      minThreshold: 5,
      unitCost: 99.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 1',
      supplier: 'Apple Enterprise Direct',
      notes: 'Replacement chargers for 16-inch MacBook Pro fleet.',
    },
    {
      sku: 'PWR-DELL-130W-USBC',
      name: 'Dell 130W USB-C AC Adapter with Power Cord',
      category: 'Power & Battery',
      quantity: 12,
      minThreshold: 5,
      unitCost: 79.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 1',
      supplier: 'Dell Premier Direct',
      notes: 'Power bricks for Dell Precision / Latitude laptops.',
    },
    {
      sku: 'ADP-TB-25GBE-LAN',
      name: 'Belkin USB-C to 2.5Gbps Gigabit Ethernet Adapter',
      category: 'Cables & Adapters',
      quantity: 0,
      minThreshold: 5,
      unitCost: 35.0,
      location: 'Storage Room A',
      binNumber: 'Bin A-12',
      supplier: 'Amazon Business',
      notes: 'Completely depleted! Pending supplier restock delivery.',
    },
    {
      sku: 'OPT-SFP-10G-SR-CS',
      name: 'Cisco 10GBASE-SR SFP+ Optical Transceiver Module',
      category: 'Cables & Adapters',
      quantity: 18,
      minThreshold: 6,
      unitCost: 120.0,
      location: 'NY4 DC Tech Cage',
      binNumber: 'Fiber Bin F-02',
      supplier: 'FS.com Enterprise',
      notes: 'Multimode 850nm OM4 fiber transceivers for rack interconnects.',
    },
    {
      sku: 'SEC-YUBIKEY-5C-NFC',
      name: 'Yubico YubiKey 5C NFC FIDO2 / WebAuthn Security Key',
      category: 'Peripherals',
      quantity: 35,
      minThreshold: 10,
      unitCost: 55.0,
      location: 'Storage Room B',
      binNumber: 'Vault Locker 2',
      supplier: 'Yubico Direct B2B',
      notes: 'Mandatory hardware MFA token for all employees with cloud access.',
    },
    {
      sku: 'AUD-HEADSET-POLY-V2',
      name: 'Poly Voyager Focus 2 UC Wireless Bluetooth Headset',
      category: 'Peripherals',
      quantity: 9,
      minThreshold: 4,
      unitCost: 229.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 4',
      supplier: 'HP / Poly Enterprise',
      notes: 'Active noise-canceling headsets with desktop charging stand.',
    },
  ];

  for (const item of inventoryItems) {
    await prisma.inventoryItem.upsert({
      where: { sku: item.sku },
      update: {},
      create: item,
    });
  }

  // 10. Directory Users (Active Directory / LDAP / Okta Sync)
  const directoryUsersData = [
    {
      username: 'alex.johnson',
      email: 'admin@uims.internal',
      displayName: 'Alex Johnson',
      jobTitle: 'VP of Information Technology',
      department: 'IT & Infrastructure',
      role: 'Super Admin',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 234-5678',
      location: 'NY HQ - Floor 4',
      source: 'LOCAL' as const,
    },
    {
      username: 'sarah.chen',
      email: 'sarah.chen@company.com',
      displayName: 'Sarah Chen',
      jobTitle: 'Senior Systems Administrator',
      department: 'IT & Infrastructure',
      role: 'IT Specialist',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 345-6789',
      location: 'SF HQ - Tech Bay',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'michael.wong',
      email: 'michael.wong@company.com',
      displayName: 'Michael Wong',
      jobTitle: 'Senior Network Architect',
      department: 'IT & Infrastructure',
      role: 'Admin',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 345-1122',
      location: 'NY HQ - Floor 4',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'marcus.bell',
      email: 'compliance@uims.internal',
      displayName: 'Marcus Bell',
      jobTitle: 'Principal Security Compliance Auditor',
      department: 'Security & Compliance',
      role: 'Auditor',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+44 20 7946 0912',
      location: 'London Hub',
      source: 'LOCAL' as const,
    },
    {
      username: 'marcus.vance',
      email: 'marcus.vance@company.com',
      displayName: 'Marcus Vance',
      jobTitle: 'Principal Product Designer',
      department: 'Product & Design',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 456-7890',
      location: 'NY HQ - Floor 4',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'chloe.martin',
      email: 'chloe.martin@company.com',
      displayName: 'Chloe Martin',
      jobTitle: 'Senior UX Researcher',
      department: 'Product & Design',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+44 20 7946 0881',
      location: 'London Hub',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'david.kim',
      email: 'david.kim@company.com',
      displayName: 'David Kim',
      jobTitle: 'Lead Cloud Architect',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-8901',
      location: 'Remote - US East',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'sophia.patel',
      email: 'sophia.patel@company.com',
      displayName: 'Sophia Patel',
      jobTitle: 'Senior Staff Fullstack Engineer',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-2233',
      location: 'SF HQ - Tech Bay',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'liam.nguyen',
      email: 'liam.nguyen@company.com',
      displayName: 'Liam Nguyen',
      jobTitle: 'Lead DevOps & SRE Architect',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-4455',
      location: 'Remote - US West',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'carlos.mendez',
      email: 'carlos.mendez@company.com',
      displayName: 'Carlos Mendez',
      jobTitle: 'Senior Backend Platform Engineer',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-7788',
      location: 'NY HQ - Floor 4',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'elena.rostova',
      email: 'elena.rostova@company.com',
      displayName: 'Elena Rostova',
      jobTitle: 'Director of Growth Marketing',
      department: 'Marketing',
      role: 'Manager',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 678-9012',
      location: 'London Hub',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'robert.torres',
      email: 'robert.torres@company.com',
      displayName: 'Robert Torres',
      jobTitle: 'IT Infrastructure Operations Manager',
      department: 'IT & Infrastructure',
      role: 'Manager',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 678-3344',
      location: 'NY HQ - Floor 4',
      source: 'LOCAL' as const,
    },
    {
      username: 'lisa.wang',
      email: 'lisa.wang@company.com',
      displayName: 'Lisa Wang',
      jobTitle: 'Financial Controller',
      department: 'Finance',
      role: 'Manager',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+65 6789 0123',
      location: 'Singapore Hub',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'rachel.adams',
      email: 'rachel.adams@company.com',
      displayName: 'Rachel Adams',
      jobTitle: 'Head of People Operations',
      department: 'Human Resources',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 890-1234',
      location: 'NY HQ - Floor 5',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'james.wilson',
      email: 'james.wilson@company.com',
      displayName: 'James Wilson',
      jobTitle: 'Senior Corporate Counsel',
      department: 'Legal & Governance',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 901-2345',
      location: 'NY HQ - Floor 5',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'hannah.scott',
      email: 'hannah.scott@company.com',
      displayName: 'Hannah Scott',
      jobTitle: 'Strategic Account Executive',
      department: 'Sales',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 901-6789',
      location: 'Remote - US Central',
      source: 'AZURE_AD' as const,
    },
    {
      username: 'thomas.wright',
      email: 'thomas.wright@company.com',
      displayName: 'Thomas Wright',
      jobTitle: 'Junior QA Engineer (Contractor)',
      department: 'Engineering',
      role: 'Employee',
      accountStatus: 'SUSPENDED' as const,
      twoFactorEnabled: false,
      phone: '+1 (555) 789-0123',
      location: 'Remote - EMEA',
      source: 'LOCAL' as const,
    },
    {
      username: 'jessica.taylor',
      email: 'jessica.taylor@company.com',
      displayName: 'Jessica Taylor',
      jobTitle: 'Content Strategist (Leave of Absence)',
      department: 'Marketing',
      role: 'Employee',
      accountStatus: 'SUSPENDED' as const,
      twoFactorEnabled: true,
      phone: '+44 20 7946 0999',
      location: 'London Hub',
      source: 'AZURE_AD' as const,
    },
  ];

  for (const du of directoryUsersData) {
    await prisma.directoryUser.upsert({
      where: { email: du.email },
      update: {},
      create: du,
    });
  }

  // 11. Directory Groups
  const directoryGroups = [
    {
      id: 'grp-all-company',
      name: 'All Company Employees',
      email: 'all-employees@company.com',
      memberCount: 148,
      scope: 'Internal Only',
      managedBy: 'People Operations (Rachel Adams)',
      description: 'Broadcast distribution list for entire enterprise workforce.',
    },
    {
      id: 'grp-engineering-core',
      name: 'Engineering & DevOps Core',
      email: 'engineering-core@company.com',
      memberCount: 52,
      scope: 'Internal Only',
      managedBy: 'David Kim',
      description: 'Software engineers, architects, backend and frontend developers.',
    },
    {
      id: 'grp-it-infrastructure',
      name: 'IT Infrastructure & Operations',
      email: 'it-ops@company.com',
      memberCount: 12,
      scope: 'Internal Only',
      managedBy: 'Robert Torres',
      description: 'Systems, network, and data center engineering teams.',
    },
    {
      id: 'grp-security-sirt',
      name: 'Security Incident Response Team (SIRT)',
      email: 'security-response@company.com',
      memberCount: 8,
      scope: 'Restricted / Security High',
      managedBy: 'Sarah Chen',
      description: 'SecOps engineers, auditors and 24/7 incident responders.',
    },
    {
      id: 'grp-product-design',
      name: 'Product Design & UX Research',
      email: 'product-design@company.com',
      memberCount: 14,
      scope: 'Internal Only',
      managedBy: 'Marcus Vance',
      description: 'Design systems, UI/UX and product managers.',
    },
    {
      id: 'grp-growth-marketing',
      name: 'Growth Marketing & Public Relations',
      email: 'press-media@company.com',
      memberCount: 16,
      scope: 'Public / External Allowed',
      managedBy: 'Elena Rostova',
      description: 'Marketing campaigns, social media and PR press inquiries.',
    },
    {
      id: 'grp-finance-procure',
      name: 'Finance & Hardware Procurement',
      email: 'procurement-finance@company.com',
      memberCount: 9,
      scope: 'Internal Only',
      managedBy: 'Lisa Wang',
      description: 'Hardware asset budgets, software renewals and vendor contracts.',
    },
    {
      id: 'grp-executive-steering',
      name: 'Executive Steering Committee',
      email: 'executive-leadership@company.com',
      memberCount: 7,
      scope: 'Confidential / Board Level',
      managedBy: 'Alex Johnson',
      description: 'Executive VPs, Directors and Legal Counsel.',
    },
  ];

  for (const dg of directoryGroups) {
    await prisma.directoryGroup.upsert({
      where: { id: dg.id },
      update: {},
      create: dg,
    });
  }

  // 12. Email Accounts (14 Enterprise Mailboxes & Inboxes)
  const emailAccounts = [
    {
      address: 'alex.johnson@company.com',
      displayName: 'Alex Johnson (VP of IT)',
      type: 'Executive',
      quotaUsed: 18.4,
      quotaTotal: 100,
      status: 'Active',
      department: 'IT & Infrastructure',
      autoReplyEnabled: false,
      aliases: ['alex@company.com', 'cio@company.com'],
    },
    {
      address: 'sarah.chen@company.com',
      displayName: 'Sarah Chen (IT Specialist)',
      type: 'User',
      quotaUsed: 24.2,
      quotaTotal: 50,
      status: 'Active',
      department: 'IT & Infrastructure',
      autoReplyEnabled: false,
      aliases: ['schen@company.com'],
    },
    {
      address: 'it-support@company.com',
      displayName: 'IT Helpdesk Inbound Queue',
      type: 'Shared',
      quotaUsed: 42.1,
      quotaTotal: 100,
      status: 'Active',
      department: 'IT & Infrastructure',
      autoReplyEnabled: true,
      aliases: ['helpdesk@company.com', 'support@company.com', 'itservicedesk@company.com'],
    },
    {
      address: 'security-alerts@company.com',
      displayName: 'SOC Security & Automated Alerts',
      type: 'Shared',
      quotaUsed: 68.5,
      quotaTotal: 100,
      status: 'Active',
      department: 'Security & Compliance',
      autoReplyEnabled: false,
      aliases: ['soc@company.com', 'abuse@company.com'],
    },
    {
      address: 'sales-team@company.com',
      displayName: 'Global Sales Shared Pipeline',
      type: 'Shared',
      quotaUsed: 46.8,
      quotaTotal: 50,
      status: 'Warning',
      department: 'Sales',
      autoReplyEnabled: true,
      aliases: ['deals@company.com', 'inquiries@company.com', 'revenue@company.com'],
    },
    {
      address: 'marcus.vance@company.com',
      displayName: 'Marcus Vance (Principal Design)',
      type: 'User',
      quotaUsed: 12.8,
      quotaTotal: 50,
      status: 'Active',
      department: 'Product & Design',
      autoReplyEnabled: false,
      aliases: ['marcus@company.com', 'design-lead@company.com'],
    },
    {
      address: 'david.kim@company.com',
      displayName: 'David Kim (Cloud Architect)',
      type: 'User',
      quotaUsed: 15.2,
      quotaTotal: 50,
      status: 'Active',
      department: 'Engineering',
      autoReplyEnabled: false,
      aliases: ['dkim@company.com'],
    },
    {
      address: 'elena.rostova@company.com',
      displayName: 'Elena Rostova (Marketing Director)',
      type: 'Executive',
      quotaUsed: 31.4,
      quotaTotal: 100,
      status: 'Active',
      department: 'Marketing',
      autoReplyEnabled: false,
      aliases: ['elena@company.com'],
    },
    {
      address: 'finance-invoices@company.com',
      displayName: 'Accounts Payable & Invoices',
      type: 'Shared',
      quotaUsed: 38.0,
      quotaTotal: 50,
      status: 'Active',
      department: 'Finance',
      autoReplyEnabled: true,
      aliases: ['billing@company.com', 'invoices@company.com'],
    },
    {
      address: 'hr-confidential@company.com',
      displayName: 'People Ops Confidential Inbox',
      type: 'Shared',
      quotaUsed: 9.4,
      quotaTotal: 50,
      status: 'Active',
      department: 'Human Resources',
      autoReplyEnabled: true,
      aliases: ['careers@company.com', 'hr@company.com'],
    },
    {
      address: 'boardroom-ny@company.com',
      displayName: 'NY Executive Boardroom Calendar Room',
      type: 'Resource',
      quotaUsed: 1.8,
      quotaTotal: 10,
      status: 'Active',
      department: 'Facilities',
      autoReplyEnabled: true,
      aliases: ['room-ny-501@company.com'],
    },
    {
      address: 'conference-sf-alpha@company.com',
      displayName: 'SF Tech Bay Alpha Conference Room',
      type: 'Resource',
      quotaUsed: 0.9,
      quotaTotal: 10,
      status: 'Active',
      department: 'Facilities',
      autoReplyEnabled: true,
      aliases: ['room-sf-201@company.com'],
    },
    {
      address: 'london-executive-suite@company.com',
      displayName: 'London Bishopsgate Video Room',
      type: 'Resource',
      quotaUsed: 2.1,
      quotaTotal: 10,
      status: 'Active',
      department: 'Facilities',
      autoReplyEnabled: true,
      aliases: ['room-lon-1201@company.com'],
    },
  ];

  for (const ea of emailAccounts) {
    await prisma.emailAccount.upsert({
      where: { address: ea.address },
      update: {},
      create: ea,
    });
  }

  // 13. Subnets & VLANs (6 Subnets)
  const subnetsData = [
    {
      cidr: '192.168.1.0/24',
      name: 'NY Data Center & Core Infrastructure',
      vlanName: 'VLAN 10 (Servers)',
      gateway: '192.168.1.1',
      totalIps: 254,
      usedIps: 184,
      location: 'NY4 Secure Vault',
    },
    {
      cidr: '192.168.10.0/24',
      name: 'HQ Employee Wired Workstations & Desks',
      vlanName: 'VLAN 20 (Workstations)',
      gateway: '192.168.10.1',
      totalIps: 254,
      usedIps: 212,
      location: 'NY HQ - Floor 4',
    },
    {
      cidr: '10.200.0.0/22',
      name: 'Corporate 802.1X Wi-Fi DHCP Pool',
      vlanName: 'VLAN 30 (Wi-Fi APs)',
      gateway: '10.200.0.1',
      totalIps: 1022,
      usedIps: 420,
      location: 'Global Hubs',
    },
    {
      cidr: '10.100.0.0/24',
      name: 'Production Kubernetes Cluster Nodes',
      vlanName: 'VLAN 40 (K8s Prod)',
      gateway: '10.100.0.1',
      totalIps: 254,
      usedIps: 96,
      location: 'NY4 / SV5 DCs',
    },
    {
      cidr: '10.50.0.0/24',
      name: 'Facilities IoT, Scanners & Security Cams',
      vlanName: 'VLAN 50 (IoT Devices)',
      gateway: '10.50.0.1',
      totalIps: 254,
      usedIps: 68,
      location: 'All Office Facilities',
    },
    {
      cidr: '172.16.0.0/24',
      name: 'Out-of-Band Management & IPMI / iDRAC',
      vlanName: 'VLAN 99 (OOB Management)',
      gateway: '172.16.0.1',
      totalIps: 254,
      usedIps: 42,
      location: 'Data Centers',
    },
  ];

  for (const s of subnetsData) {
    await prisma.subnet.upsert({
      where: { cidr: s.cidr },
      update: {},
      create: s,
    });
  }

  // 14. IP Addresses Allocation (20+ Real Hosts)
  const ipAddressesData = [
    {
      address: '192.168.1.1',
      hostname: 'cisco-core-gw01.uims.lan',
      macAddress: 'F0:5C:19:88:22:91',
      vendor: 'Cisco Systems',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Switch',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.3ms)',
    },
    {
      address: '192.168.1.10',
      hostname: 'ny-dc-srv01.uims.lan',
      macAddress: '00:1B:44:11:3A:B7',
      vendor: 'Dell Enterprise',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '1m ago (1.4ms)',
    },
    {
      address: '192.168.1.15',
      hostname: 'fortigate-fw01.uims.lan',
      macAddress: '70:4C:A5:33:11:88',
      vendor: 'Fortinet Enterprise',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Switch',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.2ms)',
    },
    {
      address: '192.168.1.50',
      hostname: 'backup-synology-nas01.uims.lan',
      macAddress: '00:11:32:8A:4F:72',
      vendor: 'Synology NAS',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (1.8ms)',
    },
    {
      address: '192.168.10.25',
      hostname: 'hp-laserjet-floor4.uims.lan',
      macAddress: '3C:52:82:19:00:DF',
      vendor: 'HP Inc',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 20 (Workstations)',
      deviceType: 'Printer',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '2m ago (3.2ms)',
    },
    {
      address: '192.168.10.45',
      hostname: 'macbook-marcus-vance.uims.lan',
      macAddress: '9C:64:8B:2A:41:09',
      vendor: 'Apple Inc',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 20 (Workstations)',
      deviceType: 'Workstation',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '3m ago (4.2ms)',
    },
    {
      address: '192.168.10.46',
      hostname: 'thinkpad-david-kim.uims.lan',
      macAddress: '54:E1:AD:77:88:99',
      vendor: 'Lenovo',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 20 (Workstations)',
      deviceType: 'Workstation',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '1m ago (2.8ms)',
    },
    {
      address: '192.168.10.150',
      hostname: 'unifi-ap-floor4-east.uims.lan',
      macAddress: '74:83:C2:55:61:FA',
      vendor: 'Ubiquiti UniFi',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 30 (Wi-Fi APs)',
      deviceType: 'Access Point',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Just now (1.1ms)',
    },
    {
      address: '192.168.10.151',
      hostname: 'unifi-ap-floor4-west.uims.lan',
      macAddress: '74:83:C2:55:61:FB',
      vendor: 'Ubiquiti UniFi',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 30 (Wi-Fi APs)',
      deviceType: 'Access Point',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Just now (0.9ms)',
    },
    {
      address: '10.100.0.11',
      hostname: 'k8s-master01.uims.lan',
      macAddress: '52:54:00:88:1A:01',
      vendor: 'Dell Enterprise',
      subnetName: '10.100.0.0/24',
      vlanName: 'VLAN 40 (K8s Prod)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.4ms)',
    },
    {
      address: '10.100.0.21',
      hostname: 'k8s-worker-gpu01.uims.lan',
      macAddress: '52:54:00:88:1B:02',
      vendor: 'Dell Enterprise',
      subnetName: '10.100.0.0/24',
      vlanName: 'VLAN 40 (K8s Prod)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.5ms)',
    },
    {
      address: '172.16.0.10',
      hostname: 'idrac-poweredge-r760.oob.lan',
      macAddress: 'B0:4E:26:11:99:33',
      vendor: 'Dell iDRAC Enterprise',
      subnetName: '172.16.0.0/24',
      vlanName: 'VLAN 99 (OOB Management)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '1m ago (1.9ms)',
    },
    {
      address: '192.168.1.99',
      hostname: 'spare-vm-host.uims.lan',
      macAddress: '00:50:56:9A:11:22',
      vendor: 'VMware vSphere',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Server',
      status: 'RESERVED' as const,
      pingStatus: 'offline',
      lastSeen: 'Standby DR replica',
    },
  ];

  for (const ip of ipAddressesData) {
    await prisma.iPAddress.upsert({
      where: { address: ip.address },
      update: {},
      create: ip,
    });
  }

  // 15. Helpdesk Support Tickets & Threaded Comments (8 Comprehensive Tickets)
  const ticketsData = [
    {
      id: 'tkt-1001',
      ticketCode: 'TKT-1001',
      title: 'Cannot access internal VPN from remote home network',
      category: 'Network',
      priority: 'URGENT' as const,
      status: 'OPEN' as const,
      requesterName: 'Marcus Vance',
      requesterEmail: 'marcus.vance@company.com',
      assigneeName: 'Sarah Chen',
      assignedToId: userSarah.id,
      createdById: userMarcusVance.id,
      affectedAsset: 'AST-1001 (MacBook Pro 16)',
      slaDeadline: '2h left',
      comments: [
        {
          authorName: 'Marcus Vance',
          authorEmail: 'marcus.vance@company.com',
          isStaff: false,
          content:
            'WireGuard client reports handshake timeout when connecting to NY-GW01 gateway since morning.',
        },
        {
          authorName: 'Sarah Chen',
          authorEmail: 'sarah.chen@company.com',
          avatarColor: '#1677ff',
          isStaff: true,
          content:
            'Checking gateway UDP 51820 NAT keepalive rules on FortiGate-200F. Running live traceroute now.',
        },
      ],
    },
    {
      id: 'tkt-1002',
      ticketCode: 'TKT-1002',
      title: 'Request second external 4K monitor for marketing design station',
      category: 'Hardware',
      priority: 'LOW' as const,
      status: 'IN_PROGRESS' as const,
      requesterName: 'Elena Rostova',
      requesterEmail: 'elena.rostova@company.com',
      assigneeName: 'Sarah Chen',
      assignedToId: userSarah.id,
      createdById: userElena.id,
      affectedAsset: 'AST-1011 (MacBook Air 15)',
      slaDeadline: '1d left',
      comments: [
        {
          authorName: 'Elena Rostova',
          authorEmail: 'elena.rostova@company.com',
          isStaff: false,
          content:
            'Need an extra 27" 4K monitor for marketing campaign assets and keynote video editing.',
        },
        {
          authorName: 'Sarah Chen',
          authorEmail: 'sarah.chen@company.com',
          avatarColor: '#1677ff',
          isStaff: true,
          content:
            'Approved by department manager. We have Dell U2723QE in stock in Room A. Deploying today.',
        },
      ],
    },
    {
      id: 'tkt-1003',
      ticketCode: 'TKT-1003',
      title: 'Figma Enterprise Seat Invitation Not Received for Design Sprint',
      category: 'Software',
      priority: 'HIGH' as const,
      status: 'OPEN' as const,
      requesterName: 'David Kim',
      requesterEmail: 'david.kim@company.com',
      assigneeName: 'Alex Johnson',
      assignedToId: userAlex.id,
      createdById: userDavidKim.id,
      affectedAsset: 'lic-figma (Figma Enterprise)',
      slaDeadline: '3h left',
      comments: [
        {
          authorName: 'David Kim',
          authorEmail: 'david.kim@company.com',
          isStaff: false,
          content: 'Need editor seat license for mobile design sprint starting at noon today.',
        },
      ],
    },
    {
      id: 'tkt-1004',
      ticketCode: 'TKT-1004',
      title: 'Reset Password & 2FA MFA Token for Office 365 Entra ID',
      category: 'Access & Security',
      priority: 'MEDIUM' as const,
      status: 'RESOLVED' as const,
      requesterName: 'Thomas Wright',
      requesterEmail: 'thomas.wright@company.com',
      assigneeName: 'Sarah Chen',
      assignedToId: userSarah.id,
      createdById: userThomas.id,
      slaDeadline: 'Resolved in 24m',
      comments: [
        {
          authorName: 'Thomas Wright',
          authorEmail: 'thomas.wright@company.com',
          isStaff: false,
          content: 'Switched phone and lost Microsoft Authenticator app token seed.',
        },
        {
          authorName: 'Sarah Chen',
          authorEmail: 'sarah.chen@company.com',
          avatarColor: '#1677ff',
          isStaff: true,
          content:
            'Identity verified over secure voice channel. Entra ID MFA token reset completed.',
        },
      ],
    },
    {
      id: 'tkt-1005',
      ticketCode: 'TKT-1005',
      title: 'Wi-Fi 6 AP connectivity intermittent packet drops in Floor 4 East Wing',
      category: 'Network',
      priority: 'HIGH' as const,
      status: 'IN_PROGRESS' as const,
      requesterName: 'Carlos Mendez',
      requesterEmail: 'carlos.mendez@company.com',
      assigneeName: 'Michael Wong',
      assignedToId: userMichael.id,
      createdById: userCarlosMendez.id,
      affectedAsset: 'AST-1019 (UniFi U6 AP)',
      slaDeadline: '4h left',
      comments: [
        {
          authorName: 'Carlos Mendez',
          authorEmail: 'carlos.mendez@company.com',
          isStaff: false,
          content:
            'Laptops in East Wing conference room disconnect during Zoom screen shares every 20-30 mins.',
        },
        {
          authorName: 'Michael Wong',
          authorEmail: 'michael.wong@company.com',
          avatarColor: '#1677ff',
          isStaff: true,
          content:
            'RF spectrum scan shows 80MHz channel interference with neighboring radar DFS band. Moving to non-DFS 160MHz channel.',
        },
      ],
    },
    {
      id: 'tkt-1006',
      ticketCode: 'TKT-1006',
      title: 'New Developer Laptop Onboarding & YubiKey Hardware MFA Issue',
      category: 'Hardware',
      priority: 'MEDIUM' as const,
      status: 'IN_PROGRESS' as const,
      requesterName: 'Rachel Adams',
      requesterEmail: 'rachel.adams@company.com',
      assigneeName: 'Sarah Chen',
      assignedToId: userSarah.id,
      createdById: userRachelAdams.id,
      slaDeadline: '6h left',
      comments: [
        {
          authorName: 'Rachel Adams',
          authorEmail: 'rachel.adams@company.com',
          isStaff: false,
          content:
            'New frontend engineer joining next Monday. Need pre-configured ThinkPad P16 and YubiKey 5C issued.',
        },
      ],
    },
    {
      id: 'tkt-1007',
      ticketCode: 'TKT-1007',
      title: 'PostgreSQL staging database slow query spike on /analytics endpoint',
      category: 'Infrastructure',
      priority: 'URGENT' as const,
      status: 'RESOLVED' as const,
      requesterName: 'Liam Nguyen',
      requesterEmail: 'liam.nguyen@company.com',
      assigneeName: 'David Kim',
      assignedToId: userDavidKim.id,
      createdById: userLiamNguyen.id,
      slaDeadline: 'Resolved in 15m',
      comments: [
        {
          authorName: 'Liam Nguyen',
          authorEmail: 'liam.nguyen@company.com',
          isStaff: false,
          content: 'Query latency on audit_logs table exceeded 1200ms during reporting burst.',
        },
        {
          authorName: 'David Kim',
          authorEmail: 'david.kim@company.com',
          avatarColor: '#10b981',
          isStaff: true,
          content:
            'Applied compound B-tree index on (entity, timestamp DESC). Latency dropped back to 3ms.',
        },
      ],
    },
    {
      id: 'tkt-1008',
      ticketCode: 'TKT-1008',
      title: 'Request AWS Production ReadOnly IAM role for SOC2 compliance audit',
      category: 'Access & Security',
      priority: 'MEDIUM' as const,
      status: 'OPEN' as const,
      requesterName: 'Marcus Bell',
      requesterEmail: 'compliance@uims.internal',
      assigneeName: 'Alex Johnson',
      assignedToId: userAlex.id,
      createdById: userMarcusBell.id,
      slaDeadline: '1d left',
      comments: [
        {
          authorName: 'Marcus Bell',
          authorEmail: 'compliance@uims.internal',
          isStaff: false,
          content:
            'Need temporary read-only access to AWS CloudTrail and AWS Config for annual SOC2 Type II audit evidence collection.',
        },
      ],
    },
  ];

  for (const t of ticketsData) {
    const { comments, ...ticketFields } = t;
    const createdTicket = await prisma.ticket.upsert({
      where: { id: ticketFields.id },
      update: {},
      create: ticketFields,
    });

    if (comments && comments.length > 0) {
      for (const c of comments) {
        await prisma.ticketComment.create({
          data: {
            ticketId: createdTicket.id,
            authorName: c.authorName,
            authorEmail: c.authorEmail,
            avatarColor: c.avatarColor || '#1677ff',
            isStaff: c.isStaff,
            content: c.content,
          },
        });
      }
    }
  }

  // 16. Audit Logs (12 Comprehensive Security & Governance Logs)
  const auditLogs = [
    {
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'PROVISION',
      severity: 'Info',
      entity: 'Asset AST-1001',
      entityType: 'Asset',
      ipAddress: '192.168.1.15 (NY HQ)',
      status: 'Success',
      details: 'Provisioned new Apple MacBook Pro 16" M3 Max to Marcus Vance (Principal Design).',
      diffPayload: {
        requestId: 'req_88a91b2c',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) UIMS-Client/2.4',
        after: {
          tag: 'AST-1001',
          model: 'MacBook Pro 16 M3 Max',
          assignedTo: 'Marcus Vance',
          price: 3499,
        },
      },
    },
    {
      userName: 'Sarah Chen',
      userEmail: 'sarah.chen@company.com',
      action: 'UPDATE',
      severity: 'Info',
      entity: 'License Adobe CC',
      entityType: 'License',
      ipAddress: '192.168.10.12 (SF HQ)',
      status: 'Success',
      details: 'Allocated 1 Adobe Creative Cloud seat to Chloe Martin (London Design Studio).',
      diffPayload: {
        requestId: 'req_99c81a1d',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        before: { usedSeats: 27 },
        after: { usedSeats: 28, assignedUser: 'Chloe Martin' },
      },
    },
    {
      userName: 'Security Threat Defense',
      userEmail: 'threat-engine@uims.internal',
      action: 'LOGIN_FAILED',
      severity: 'Critical',
      entity: 'Auth Gateway SAML',
      entityType: 'Security',
      ipAddress: '89.248.163.2 (St. Petersburg, RU)',
      status: 'Blocked',
      details:
        'Invalid SAML assertion signature and brute force attempt. Origin IP blocked by firewall rate-limiter.',
      diffPayload: {
        requestId: 'sec_block_4482',
        userAgent: 'python-requests/2.31.0',
        before: { geoCountry: 'RU', riskScore: 98 },
        after: { actionTaken: 'GEO_IP_DROP_RULE_ENGAGED' },
      },
    },
    {
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'PERMISSION_GRANT',
      severity: 'Warning',
      entity: 'Role Super Admin',
      entityType: 'User',
      ipAddress: '192.168.1.15 (NY HQ)',
      status: 'Success',
      details:
        'Granted temporary Super Admin elevated privileges to Sarah Chen for weekend data center migration.',
      diffPayload: {
        requestId: 'req_elevation_331',
        userAgent: 'UIMS-AdminConsole/2.4.0',
        before: { role: 'IT Specialist' },
        after: { role: 'Super Admin', expiresAt: '2026-08-18 00:00 UTC' },
      },
    },
    {
      userName: 'System Daemon Engine',
      userEmail: 'daemon@uims.internal',
      action: 'SNAPSHOT_VERIFY',
      severity: 'Info',
      entity: 'PostgreSQL Daily Snapshot',
      entityType: 'Storage',
      ipAddress: '127.0.0.1 (Localhost)',
      status: 'Success',
      details:
        'Automated nightly database snapshot sha256 checksum verified and mirrored to Synology SAN NAS.',
    },
    {
      userName: 'Michael Wong',
      userEmail: 'michael.wong@company.com',
      action: 'CONFIG_CHANGE',
      severity: 'Warning',
      entity: 'FortiGate 200F Firewall',
      entityType: 'Network',
      ipAddress: '192.168.1.15 (NY HQ)',
      status: 'Success',
      details: 'Updated IPSec VPN Phase 2 cryptographic proposals to AES-256-GCM / SHA-384.',
    },
    {
      userName: 'Sarah Chen',
      userEmail: 'sarah.chen@company.com',
      action: 'MFA_RESET',
      severity: 'Info',
      entity: 'User Thomas Wright',
      entityType: 'User',
      ipAddress: '192.168.10.12 (SF HQ)',
      status: 'Success',
      details: 'Revoked lost Microsoft Authenticator seed and generated new QR registration token.',
    },
    {
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'INVENTORY_REORDER',
      severity: 'Info',
      entity: 'SKU ACC-MSE-MX3S-GRY',
      entityType: 'Inventory',
      ipAddress: '192.168.1.15 (NY HQ)',
      status: 'Success',
      details: 'Generated purchase requisition PO-9921 for 20 units of Logitech MX Master 3S mice.',
    },
  ];

  for (const log of auditLogs) {
    await prisma.auditLog.create({
      data: log,
    });
  }

  // 17. System Notifications (in PostgreSQL Notification model)
  const notificationsData = [
    {
      userId: userAlex.id,
      title: 'Adobe Creative Cloud Renewal Notice',
      message:
        'Adobe Creative Cloud subscription (28 seats in use) expires on Sep 15. Renew contract.',
      type: 'WARNING' as const,
      isRead: false,
      link: '/licenses',
    },
    {
      userId: userAlex.id,
      title: 'Belkin Ethernet Adapters Stock Depleted',
      message:
        'Belkin USB-C to 2.5Gbps Gigabit Ethernet Adapter is completely at 0 units (Threshold: 5).',
      type: 'ALERT' as const,
      isRead: false,
      link: '/inventory',
    },
    {
      userId: userSarah.id,
      title: 'Urgent Helpdesk Incident Assigned',
      message: 'TKT-1001: "Cannot access internal VPN from remote home network" assigned to you.',
      type: 'WARNING' as const,
      isRead: false,
      link: '/tickets',
    },
    {
      userId: userAlex.id,
      title: 'Automated Daily Snapshot Verified',
      message:
        'PostgreSQL database snapshot sha256 checksum matched and encrypted in SeaweedFS vault.',
      type: 'INFO' as const,
      isRead: true,
      link: '/settings',
    },
    {
      userId: userMarcusVance.id,
      title: 'New Hardware Asset Provisioned',
      message: 'MacBook Pro 16" M3 Max (AST-1001) is registered and ready for deployment.',
      type: 'INFO' as const,
      isRead: true,
      link: '/assets',
    },
    {
      userId: userAlex.id,
      title: 'SAML Authentication Anomaly Blocked',
      message:
        'Unauthorized login brute force from IP 89.248.163.2 automatically dropped by firewall.',
      type: 'ALERT' as const,
      isRead: false,
      link: '/audit',
    },
  ];

  for (const n of notificationsData) {
    await prisma.notification.create({
      data: n,
    });
  }

  // 18. System Settings
  await prisma.setting.upsert({
    where: { key: 'general' },
    update: {},
    create: {
      key: 'general',
      group: 'general',
      description: 'General Enterprise Organization Preferences',
      value: {
        companyName: 'Acme Enterprise Global Inc.',
        supportEmail: 'it-support@company.com',
        timezone: 'UTC',
        dateFormat: 'YYYY-MM-DD',
        primaryDataCenter: 'Equinix NY4 Secaucus',
        complianceFrameworks: ['SOC2 Type II', 'ISO 27001', 'GDPR', 'HIPAA'],
      },
    },
  });

  await prisma.setting.upsert({
    where: { key: 'security' },
    update: {},
    create: {
      key: 'security',
      group: 'security',
      description: 'Security, SAML SSO & Authentication Governance Policy',
      value: {
        enforce2FA: true,
        sessionTimeout: 30,
        minPasswordLength: 12,
        samlEntityId: 'https://uims.internal/saml/metadata',
        allowedCidrRanges: ['192.168.0.0/16', '10.0.0.0/8', '172.16.0.0/12'],
        autoLockInactiveAccountsDays: 90,
      },
    },
  });

  // 19. Report Schedules
  const reportSchedules = [
    {
      title: 'Quarterly Asset Valuation & Depreciation Curve',
      category: 'Finance & Hardware',
      frequency: 'Quarterly (1st of Quarter)',
      format: 'PDF + Excel summary',
      recipients: 'lisa.wang@company.com, alex.johnson@company.com',
    },
    {
      title: 'Monthly SaaS License Optimization & Waste Audit',
      category: 'Software & Cloud',
      frequency: 'Monthly (1st of Month)',
      format: 'PDF + Excel summary',
      recipients: 'procurement-finance@company.com, cio@company.com',
    },
    {
      title: 'Weekly Helpdesk SLA & Incident Resolution Velocity',
      category: 'Operations',
      frequency: 'Weekly (Mondays 08:00 UTC)',
      format: 'PDF',
      recipients: 'it-ops@company.com, robert.torres@company.com',
    },
    {
      title: 'Continuous SOC2 & ISO 27001 Compliance Audit Telemetry',
      category: 'Security & Compliance',
      frequency: 'Continuous / Monthly Digest',
      format: 'PDF + Raw CSV Data Stream',
      recipients: 'compliance@uims.internal, auditor.marcus@uims.internal',
    },
  ];

  for (const rs of reportSchedules) {
    await prisma.reportSchedule.create({
      data: rs,
    });
  }

  console.log('✅ Enterprise Seed completed successfully with 100% realistic production dataset.');
}

main()
  .catch((e) => {
    console.error('❌ Seed Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
