// Concise, professional enterprise Active Directory dataset for Broadpeak (Youngone Group) — BSL (Soc Trang) & BSH (Ho Chi Minh)
export interface AdDirectoryRecord {
  employeeCode: string;
  displayName: string;
  jobTitle: string;
  groupCompany: string;
  company: string;
  department: string;
  section: string;
  email: string;
  telephone: string;
  isClosed: boolean;
  computerName: string;
  adGroup: string;
  status: 'ACTIVE' | 'DISABLED';
}

export const enterpriseAdMasterData: Array<AdDirectoryRecord> = [
  // ── BSL Factory Operations (Soc Trang Campus) ───────────────────────────
  {
    employeeCode: 'BSL-1001',
    displayName: 'Nguyen Van Minh',
    jobTitle: 'Garment Cutting & Pattern Technician',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Garment Manufacturing & Cutting',
    section: 'Automated Cutting Bay',
    email: 'minh.nguyen@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9101',
    isClosed: false,
    computerName: 'BSL-WS-1001',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1002',
    displayName: 'Tran Thi Mai',
    jobTitle: 'Sewing Production Supervisor',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Garment Manufacturing & Cutting',
    section: 'Sewing Floor 1',
    email: 'mai.tran@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9102',
    isClosed: false,
    computerName: 'BSL-WS-1002',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1003',
    displayName: 'Le Hoang Nam',
    jobTitle: 'Quality Assurance Inspector',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Quality Assurance & Technical Audit',
    section: 'Inline Inspection',
    email: 'nam.le@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9103',
    isClosed: false,
    computerName: 'BSL-WS-1003',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1004',
    displayName: 'Pham Quoc Bao',
    jobTitle: 'Industrial Automation Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory IT & Industrial Automation',
    section: 'Shop Floor Automation',
    email: 'bao.pham@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9104',
    isClosed: false,
    computerName: 'BSL-LT-1004',
    adGroup: 'GR_BSL_IT_Support',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1005',
    displayName: 'Do Thi Lan',
    jobTitle: 'Raw Material Warehouse Officer',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Warehouse & Logistics Hub',
    section: 'Fabric Stockroom',
    email: 'lan.do@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9105',
    isClosed: false,
    computerName: 'BSL-WS-1005',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1006',
    displayName: 'Vo Minh Tri',
    jobTitle: 'Finished Goods Logistics Lead',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Warehouse & Logistics Hub',
    section: 'Export Packing Bay',
    email: 'tri.vo@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9106',
    isClosed: false,
    computerName: 'BSL-WS-1006',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1007',
    displayName: 'Dang Thu Ha',
    jobTitle: 'EHS & Workplace Safety Officer',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Human Resources & General Affairs',
    section: 'Industrial Safety',
    email: 'ha.dang@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9107',
    isClosed: false,
    computerName: 'BSL-LT-1007',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1008',
    displayName: 'Bui Thanh Son',
    jobTitle: 'Shopfloor Barcode Scanning Operator',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory IT & Industrial Automation',
    section: 'Barcode Tracking',
    email: 'son.bui@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9108',
    isClosed: false,
    computerName: 'BSL-HHT-1008',
    adGroup: 'GR_BSL_IT_Support',
    status: 'ACTIVE',
  },

  // ── BSH Corporate & Commercial Hub (Ho Chi Minh Office) ──────────────────
  {
    employeeCode: 'BSH-2001',
    displayName: 'Nguyen Duc Thinh',
    jobTitle: 'Senior Apparel Sourcing Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Apparel Merchandising & Sourcing',
    section: 'Global Buyer Sourcing',
    email: 'thinh.nguyen@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8201',
    isClosed: false,
    computerName: 'BSH-LT-2001',
    adGroup: 'GR_BSH_Merchandising',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2002',
    displayName: 'Phan Thi My Linh',
    jobTitle: 'Key Account Merchandiser',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Apparel Merchandising & Sourcing',
    section: 'Outdoor Outerwear Accounts',
    email: 'linh.phan@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8202',
    isClosed: false,
    computerName: 'BSH-LT-2002',
    adGroup: 'GR_BSH_Merchandising',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2003',
    displayName: 'Trinh Quoc Dat',
    jobTitle: 'Cost Accounting & Tariffs Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Finance, Treasury & Cost Accounting',
    section: 'Cost Accounting',
    email: 'dat.trinh@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8203',
    isClosed: false,
    computerName: 'BSH-LT-2003',
    adGroup: 'GR_BSH_CorporateOffice',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2004',
    displayName: 'Vu Hoang Long',
    jobTitle: 'ERP & SAP Systems Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Enterprise IT & Cloud Systems',
    section: 'Business Applications',
    email: 'long.vu@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8204',
    isClosed: false,
    computerName: 'BSH-LT-2004',
    adGroup: 'GR_BSH_CorporateOffice',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2005',
    displayName: 'Tran Ngoc Anh',
    jobTitle: 'Corporate Talent Recruiter',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'People Operations & Talent Acquisition',
    section: 'Recruitment & Employer Branding',
    email: 'anh.tran@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8205',
    isClosed: false,
    computerName: 'BSH-LT-2005',
    adGroup: 'GR_BSH_CorporateOffice',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2006',
    displayName: 'Le Thi Kim Ngan',
    jobTitle: 'Executive Operations Coordinator',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Corporate Leadership & Strategy',
    section: 'Executive Office',
    email: 'ngan.le@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8206',
    isClosed: false,
    computerName: 'BSH-LT-2006',
    adGroup: 'GR_Youngone_Executive',
    status: 'ACTIVE',
  },
];
