// Concise, professional enterprise Active Directory dataset for Broadpeak (Youngone Group) — BSL (Soc Trang) & BSH (Ho Chi Minh)
export interface AdDirectoryRecord {
  employeeCode: string;
  displayName: string;
  jobTitle: string;
  groupCompany: string;
  company: string;
  department: string;
  departmentCode?: string;
  positionCode?: string;
  locationCode?: string;
  section: string;
  email: string;
  telephone: string;
  isClosed: boolean;
  computerName: string;
  adGroup: string;
  status: 'ACTIVE' | 'DISABLED';
}

export const enterpriseAdMasterData: Array<AdDirectoryRecord> = [
  // ── BSL Factory Operations (Soc Trang Campus) ───────────────────────────
  {
    employeeCode: 'BSL-1001',
    displayName: 'Nguyen Van Minh',
    jobTitle: 'Cutting Section Team Leader (Tổ Trưởng Cắt F1)',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory 1 - Cutting Section (Tổ Cắt Vải)',
    departmentCode: 'DEPT-BSL-F1-CUT',
    positionCode: 'POS-BSL-F1-CUT-LEAD',
    locationCode: 'loc-bsl-f1-cut',
    section: 'Automated Cutting Bay',
    email: 'minh.nguyen@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9101',
    isClosed: false,
    computerName: 'BSL-WS-1001',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1002',
    displayName: 'Tran Thi Mai',
    jobTitle: 'Sewing Assembly Line Leader (Trưởng Chuyền May F1)',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory 1 - Sewing Assembly Lines (Chuyền May Công Nghiệp)',
    departmentCode: 'DEPT-BSL-F1-SEW',
    positionCode: 'POS-BSL-F1-SEW-SUP',
    locationCode: 'loc-bsl-f1-sew',
    section: 'Sewing Floor 1',
    email: 'mai.tran@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9102',
    isClosed: false,
    computerName: 'BSL-WS-1002',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1003',
    displayName: 'Le Hoang Nam',
    jobTitle: 'Inline QA/QC Inspector (KCS Trưởng Xưởng F1)',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory 1 - Inline QA/QC Section (Tổ Kiểm Định Chất Lượng KCS)',
    departmentCode: 'DEPT-BSL-F1-QA',
    positionCode: 'POS-BSL-F1-QA-LEAD',
    locationCode: 'loc-bsl-f1-qa',
    section: 'Inline Inspection',
    email: 'nam.le@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9103',
    isClosed: false,
    computerName: 'BSL-WS-1003',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1004',
    displayName: 'Pham Quoc Bao',
    jobTitle: 'Industrial IT & Automation Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory IT & Industrial Automation (Phòng CNTT & Tự Động Hóa)',
    departmentCode: 'DEPT-BSL-IT',
    positionCode: 'POS-BSL-IT-SPEC',
    locationCode: 'loc-bsl-bc-datacenter',
    section: 'Shop Floor Automation',
    email: 'bao.pham@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9104',
    isClosed: false,
    computerName: 'BSL-LT-1004',
    adGroup: 'GR_BSL_IT_Support',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1005',
    displayName: 'Do Thi Lan',
    jobTitle: 'Central Warehouse & Fabric Supervisor',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Central Fabric & Raw Material Store (Kho Nguyên Phụ Liệu & Vải)',
    departmentCode: 'DEPT-BSL-LOG-MAT',
    positionCode: 'POS-BSL-WH-SUP',
    locationCode: 'loc-bsl-wh-raw',
    section: 'Fabric Stockroom',
    email: 'lan.do@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9105',
    isClosed: false,
    computerName: 'BSL-WS-1005',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1006',
    displayName: 'Vo Minh Tri',
    jobTitle: 'Supply Chain & Logistics Director (Giám Đốc Khối Kho Vận)',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Finished Goods Export Warehouse (Kho Thành Phẩm Xuất Khẩu)',
    departmentCode: 'DEPT-BSL-LOG-FG',
    positionCode: 'POS-BSL-SC-DIR',
    locationCode: 'loc-bsl-wh-fg',
    section: 'Export Packing Bay',
    email: 'tri.vo@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9106',
    isClosed: false,
    computerName: 'BSL-WS-1006',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1007',
    displayName: 'Dang Thu Ha',
    jobTitle: 'Plant Administration & HSE Officer',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'General Administration & Plant Affairs (Phòng Hành Chính & Tổng Hợp)',
    departmentCode: 'DEPT-BSL-ADMIN',
    positionCode: 'POS-BSL-ADMIN-LEAD',
    locationCode: 'loc-bsl-bc-admin',
    section: 'Industrial Safety',
    email: 'ha.dang@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9107',
    isClosed: false,
    computerName: 'BSL-LT-1007',
    adGroup: 'GR_BSL_FactoryOperations',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSL-1008',
    displayName: 'Bui Thanh Son',
    jobTitle: 'Industrial IT & Automation Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Soc Trang (BSL)',
    department: 'Factory IT & Industrial Automation (Phòng CNTT & Tự Động Hóa)',
    departmentCode: 'DEPT-BSL-IT',
    positionCode: 'POS-BSL-IT-SPEC',
    locationCode: 'loc-bsl-bc-datacenter',
    section: 'Barcode Tracking',
    email: 'son.bui@broadpeak.youngone.com',
    telephone: '+84 (299) 387-9108',
    isClosed: false,
    computerName: 'BSL-HHT-1008',
    adGroup: 'GR_BSL_IT_Support',
    status: 'ACTIVE',
  },

  // ── BSH Corporate & Commercial Hub (Ho Chi Minh Office) ──────────────────
  {
    employeeCode: 'BSH-2001',
    displayName: 'Nguyen Duc Thinh',
    jobTitle: 'Global Fabric Sourcing Specialist',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Global Sourcing & Raw Material Development (Phòng Phát Triển Nguồn Cung Vải)',
    departmentCode: 'DEPT-BSH-SRC',
    positionCode: 'POS-BSH-SRC-SPEC',
    locationCode: 'loc-bsh-d7',
    section: 'Global Buyer Sourcing',
    email: 'thinh.nguyen@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8201',
    isClosed: false,
    computerName: 'BSH-LT-2001',
    adGroup: 'GR_BSH_Merchandising',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2002',
    displayName: 'Phan Thi My Linh',
    jobTitle: 'Apparel Merchandiser',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Apparel Merchandising & Buyer Accounts (Phòng Quản Lý Đơn Hàng & Khách Hàng)',
    departmentCode: 'DEPT-BSH-MERCH',
    positionCode: 'POS-BSH-MERCH-SPEC',
    locationCode: 'loc-bsh-d7',
    section: 'Outdoor Outerwear Accounts',
    email: 'linh.phan@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8202',
    isClosed: false,
    computerName: 'BSH-LT-2002',
    adGroup: 'GR_BSH_Merchandising',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2003',
    displayName: 'Trinh Quoc Dat',
    jobTitle: 'Chief Accountant & Financial Controller',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Finance, Treasury & Cost Accounting (Phòng Tài Chính & Kế Toán Tổng Hợp)',
    departmentCode: 'DEPT-BSH-FIN',
    positionCode: 'POS-BSH-FIN-CTRL',
    locationCode: 'loc-bsh-d7',
    section: 'Cost Accounting',
    email: 'dat.trinh@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8203',
    isClosed: false,
    computerName: 'BSH-LT-2003',
    adGroup: 'GR_BSH_CorporateOffice',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2004',
    displayName: 'Vu Hoang Long',
    jobTitle: 'Enterprise IT Systems Architect',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Enterprise IT & Cloud Systems (Phòng CNTT Doanh Nghiệp & Đám Mây)',
    departmentCode: 'DEPT-BSH-IT',
    positionCode: 'POS-BSH-IT-ARCH',
    locationCode: 'loc-bsh-d7',
    section: 'Business Applications',
    email: 'long.vu@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8204',
    isClosed: false,
    computerName: 'BSH-LT-2004',
    adGroup: 'GR_BSH_CorporateOffice',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2005',
    displayName: 'Tran Ngoc Anh',
    jobTitle: 'Talent Acquisition & HR Manager',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'People Operations & Talent Acquisition (Phòng Nhân Sự & Thu Hút Nhân Tài)',
    departmentCode: 'DEPT-BSH-HR',
    positionCode: 'POS-BSH-HR-MGR',
    locationCode: 'loc-bsh-d7',
    section: 'Recruitment & Employer Branding',
    email: 'anh.tran@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8205',
    isClosed: false,
    computerName: 'BSH-LT-2005',
    adGroup: 'GR_BSH_CorporateOffice',
    status: 'ACTIVE',
  },
  {
    employeeCode: 'BSH-2006',
    displayName: 'Le Thi Kim Ngan',
    jobTitle: 'Commercial & Sourcing Director (Giám Đốc Thương Mại)',
    groupCompany: 'Youngone Corporation',
    company: 'Broadpeak Ho Chi Minh (BSH)',
    department: 'Commercial & Sourcing Division (Khối Kinh Doanh & Nguồn Cung Quốc Tế)',
    departmentCode: 'DEPT-BSH-COMM',
    positionCode: 'POS-BSH-COMM-DIR',
    locationCode: 'loc-bsh-d7',
    section: 'Executive Office',
    email: 'ngan.le@broadpeak.youngone.com',
    telephone: '+84 (28) 3997-8206',
    isClosed: false,
    computerName: 'BSH-LT-2006',
    adGroup: 'GR_Youngone_Executive',
    status: 'ACTIVE',
  },
];
