import type { PrismaClient } from '@prisma/client';

interface SeedTaxonomyResult {
  locations: Record<string, { id: string }>;
  categories: Record<string, { id: string }>;
}

interface SeedUsersResult {
  roles: Record<string, { id: string }>;
  users: Record<string, { id: string }>;
}

export async function seedAssets(
  prisma: PrismaClient,
  taxonomy: SeedTaxonomyResult,
  users: SeedUsersResult,
) {
  const { locations, categories } = taxonomy;
  const { users: u } = users;

  const assetDefinitions = [
    {
      assetTag: 'AST-1001',
      name: 'MacBook Pro 16" M3 Max',
      manufacturer: 'Apple',
      model: 'MacBookPro18,2 (Space Black)',
      serialNumber: 'C02G8392MD6R',
      status: 'IN_USE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userMarcusVance.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2024-02-10'),
      purchaseCost: 3499,
      warrantyExpiry: new Date('2027-02-10'),
      specs: {
        cpu: 'Apple M3 Max (16-Core CPU, 40-Core GPU)',
        ram: '64 GB Unified Memory',
        storage: '1 TB PCIe NVMe SSD',
        os: 'macOS Sonoma 14.6',
      },
      notes: 'Assigned to Principal Product Designer. Paired with CalDigit TS4 dock.',
    },
    {
      assetTag: 'AST-1002',
      name: 'Dell UltraSharp 32" 4K USB-C Hub Monitor',
      manufacturer: 'Dell',
      model: 'U3223QE (IPS Black)',
      serialNumber: 'CN-0N179F-74261',
      status: 'IN_USE' as const,
      categoryId: categories.catMonitor.id,
      assignedToId: u.userMarcusVance.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2024-02-12'),
      purchaseCost: 899,
      warrantyExpiry: new Date('2027-02-12'),
      specs: {
        cpu: 'Display Controller SoC',
        ram: '4K UHD (3840x2160) 60Hz',
        storage: '90W USB-C PD + RJ45 Hub',
        os: 'Firmware v1.08',
      },
      notes: 'Design station primary color-calibrated display (98% DCI-P3).',
    },
    {
      assetTag: 'AST-1003',
      name: 'Dell PowerEdge R760 2U Rack Server',
      manufacturer: 'Dell Enterprise',
      model: 'PowerEdge R760 NVMe',
      serialNumber: '7X99KM4',
      status: 'IN_USE' as const,
      categoryId: categories.catServer.id,
      assignedToId: u.userLiamNguyen.id,
      locationId: locations.locDCNY4.id,
      purchaseDate: new Date('2023-11-20'),
      purchaseCost: 14850,
      warrantyExpiry: new Date('2028-11-20'),
      specs: {
        cpu: '2x Intel Xeon Platinum 8480+ (112 Cores / 224 Threads)',
        ram: '512 GB ECC DDR5-4800 Registered',
        storage: '8x 3.84TB NVMe U.2 SSD Hardware RAID 10',
        os: 'Ubuntu Server 24.04 LTS (Kernel 6.8)',
      },
      notes: 'Primary production Kubernetes worker node cluster (k8s-node-prod01).',
    },
    {
      assetTag: 'AST-1004',
      name: 'Dell PowerEdge R750 2U Virtualization Host',
      manufacturer: 'Dell Enterprise',
      model: 'PowerEdge R750 VMware Host',
      serialNumber: '8X9K3M2',
      status: 'IN_USE' as const,
      categoryId: categories.catServer.id,
      assignedToId: u.userSarah.id,
      locationId: locations.locDCSV5.id,
      purchaseDate: new Date('2023-05-10'),
      purchaseCost: 9200,
      warrantyExpiry: new Date('2028-05-10'),
      specs: {
        cpu: '2x Intel Xeon Gold 6330 (56 Cores)',
        ram: '256 GB ECC DDR4-3200',
        storage: '6x 1.92TB Enterprise SAS SSD',
        os: 'VMware ESXi 8.0 Update 2',
      },
      notes: 'Hosts internal core database replicas and staging compute nodes.',
    },
    {
      assetTag: 'AST-1005',
      name: 'Cisco Catalyst 9300 48-Port PoE+ Switch',
      manufacturer: 'Cisco Systems',
      model: 'C9300-48P-A',
      serialNumber: 'FOC2438L0K4',
      status: 'IN_USE' as const,
      categoryId: categories.catNetworking.id,
      assignedToId: u.userMichael.id,
      locationId: locations.locSF.id,
      purchaseDate: new Date('2022-11-01'),
      purchaseCost: 4500,
      warrantyExpiry: new Date('2027-11-01'),
      specs: {
        cpu: 'Cisco Quad-core x86 ASIC',
        ram: '16 GB DRAM',
        storage: '16 GB eMMC Flash',
        os: 'Cisco IOS XE 17.12.02',
      },
      notes: 'SF HQ core access switch. Powers 24 APs and wired developer desks.',
    },
    {
      assetTag: 'AST-1006',
      name: 'Cisco Nexus 93180YC-FX3 Spine Switch',
      manufacturer: 'Cisco Systems',
      model: 'N9K-C93180YC-FX3',
      serialNumber: 'FOC2612M8L1',
      status: 'IN_USE' as const,
      categoryId: categories.catNetworking.id,
      assignedToId: u.userMichael.id,
      locationId: locations.locDCNY4.id,
      purchaseDate: new Date('2023-04-18'),
      purchaseCost: 11200,
      warrantyExpiry: new Date('2028-04-18'),
      specs: {
        cpu: 'Cloud Scale ASIC Engine',
        ram: '32 GB DRAM',
        storage: '64 GB SSD',
        os: 'NX-OS 10.4(1)F',
      },
      notes: 'NY4 DC Top-of-Rack leaf switch with 48x 25G SFP28 and 6x 100G QSFP28.',
    },
    {
      assetTag: 'AST-1007',
      name: 'Fortinet FortiGate 200F Enterprise Firewall',
      manufacturer: 'Fortinet',
      model: 'FG-200F-BDL-950',
      serialNumber: 'FG200FTK23001844',
      status: 'IN_USE' as const,
      categoryId: categories.catNetworking.id,
      assignedToId: u.userMichael.id,
      locationId: locations.locDCNY4.id,
      purchaseDate: new Date('2023-08-01'),
      purchaseCost: 7800,
      warrantyExpiry: new Date('2026-08-01'),
      specs: {
        cpu: 'Fortinet CP9 & NP6XLite ASICs',
        ram: '8 GB Memory',
        storage: '32 GB Flash',
        os: 'FortiOS 7.4.3',
      },
      notes: 'Main edge security gateway with IPSec VPN, SSL inspection and threat protection.',
    },
    {
      assetTag: 'AST-1008',
      name: 'Lenovo ThinkPad X1 Carbon Gen 12',
      manufacturer: 'Lenovo',
      model: 'ThinkPad X1 Carbon 21KC',
      serialNumber: 'PF-49K98X',
      status: 'IN_USE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userDavidKim.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2024-04-05'),
      purchaseCost: 2199,
      warrantyExpiry: new Date('2027-04-05'),
      specs: {
        cpu: 'Intel Core Ultra 7 155H (16-Core / NPU AI Boost)',
        ram: '32 GB LPDDR5x-6400',
        storage: '1 TB PCIe 4.0 NVMe SSD',
        os: 'Ubuntu 24.04 LTS / Dual Boot Win 11',
      },
      notes: 'Issued to Lead Cloud Architect for multi-cloud container orchestration.',
    },
    {
      assetTag: 'AST-1009',
      name: 'Lenovo ThinkPad P16 Gen 2 Workstation',
      manufacturer: 'Lenovo',
      model: 'ThinkPad P16 21FA',
      serialNumber: 'PF-58M12L',
      status: 'IN_USE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userSophiaPatel.id,
      locationId: locations.locSF.id,
      purchaseDate: new Date('2023-10-15'),
      purchaseCost: 3250,
      warrantyExpiry: new Date('2026-10-15'),
      specs: {
        cpu: 'Intel Core i9-13980HX (24-Core 5.6GHz)',
        ram: '64 GB DDR5-5200 ECC',
        storage: '2 TB PCIe 4.0 NVMe SSD',
        os: 'Fedora Workstation 40',
      },
      notes: 'High-performance AI model and database benchmarking machine.',
    },
    {
      assetTag: 'AST-1010',
      name: 'MacBook Pro 14" M3 Pro',
      manufacturer: 'Apple',
      model: 'MacBookPro18,3 (Silver)',
      serialNumber: 'C02H1883ND9P',
      status: 'IN_USE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userChloeMartin.id,
      locationId: locations.locLondon.id,
      purchaseDate: new Date('2024-01-25'),
      purchaseCost: 2499,
      warrantyExpiry: new Date('2027-01-25'),
      specs: {
        cpu: 'Apple M3 Pro (12-Core CPU, 18-Core GPU)',
        ram: '36 GB Unified Memory',
        storage: '1 TB NVMe SSD',
        os: 'macOS Sonoma 14.5',
      },
      notes: 'London UX Research and prototyping lead machine.',
    },
    {
      assetTag: 'AST-1011',
      name: 'Apple MacBook Air 15" M3',
      manufacturer: 'Apple',
      model: 'MacBookAir15,2 (Midnight)',
      serialNumber: 'C02J4491QK3L',
      status: 'IN_USE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userElena.id,
      locationId: locations.locLondon.id,
      purchaseDate: new Date('2024-03-10'),
      purchaseCost: 1699,
      warrantyExpiry: new Date('2027-03-10'),
      specs: {
        cpu: 'Apple M3 (8-Core CPU, 10-Core GPU)',
        ram: '24 GB Unified Memory',
        storage: '512 GB SSD',
        os: 'macOS Sonoma 14.5',
      },
      notes: 'Marketing executive deployment.',
    },
    {
      assetTag: 'AST-1012',
      name: 'Dell Precision 7680 Mobile Workstation',
      manufacturer: 'Dell',
      model: 'Precision 7680 UHD',
      serialNumber: '9K2M771',
      status: 'IN_USE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userCarlosMendez.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2023-09-05'),
      purchaseCost: 3100,
      warrantyExpiry: new Date('2026-09-05'),
      specs: {
        cpu: 'Intel Core i7-13850HX vPro (20-Core)',
        ram: '32 GB CAMM DDR5',
        storage: '1 TB NVMe Gen4 + NVIDIA RTX 3500 Ada',
        os: 'Windows 11 Pro Enterprise',
      },
      notes: 'Backend microservices profiling and load testing.',
    },
    {
      assetTag: 'AST-1013',
      name: 'Apple Studio Display 27" 5K Retina',
      manufacturer: 'Apple',
      model: 'Studio Display A2525',
      serialNumber: 'F17HK923MD99',
      status: 'IN_USE' as const,
      categoryId: categories.catMonitor.id,
      assignedToId: u.userChloeMartin.id,
      locationId: locations.locLondon.id,
      purchaseDate: new Date('2024-01-26'),
      purchaseCost: 1599,
      warrantyExpiry: new Date('2027-01-26'),
      specs: {
        cpu: 'Apple A13 Bionic (Center Stage & Spatial Audio)',
        ram: '5K Retina 5120x2880 Display',
        storage: '96W Thunderbolt 3 Passthrough',
        os: 'Studio Display Firmware v17.0',
      },
      notes: 'Paired with AST-1010 in London design studio.',
    },
    {
      assetTag: 'AST-1014',
      name: 'Dell UltraSharp 38" Curved USB-C Hub Monitor',
      manufacturer: 'Dell',
      model: 'U3824DW (WQHD+)',
      serialNumber: 'CN-08819A-48192',
      status: 'IN_USE' as const,
      categoryId: categories.catMonitor.id,
      assignedToId: u.userDavidKim.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2023-12-01'),
      purchaseCost: 1250,
      warrantyExpiry: new Date('2026-12-01'),
      specs: {
        cpu: 'Dual KVM Controller Engine',
        ram: '3840x1600 WQHD+ 60Hz 21:9',
        storage: '2.5GbE LAN RJ45 + 90W PD',
        os: 'Firmware v1.03',
      },
      notes: 'Architecture dual-source side-by-side workstation screen.',
    },
    {
      assetTag: 'AST-1015',
      name: 'Synology RackStation RS3621xs+ Storage SAN',
      manufacturer: 'Synology Enterprise',
      model: 'RS3621xs+ 12-Bay',
      serialNumber: '2190Q8R39201',
      status: 'IN_USE' as const,
      categoryId: categories.catStorage.id,
      assignedToId: u.userSarah.id,
      locationId: locations.locDCNY4.id,
      purchaseDate: new Date('2023-03-14'),
      purchaseCost: 8900,
      warrantyExpiry: new Date('2028-03-14'),
      specs: {
        cpu: 'Intel Xeon D-1541 8-Core 2.7GHz',
        ram: '64 GB ECC DDR4',
        storage: '12x 18TB Seagate Exos Enterprise SAS (144TB Raw / RAID 6)',
        os: 'DSM 7.2.1 Enterprise',
      },
      notes: 'Internal NFS and iSCSI target for automated daily system snapshots.',
    },
    {
      assetTag: 'AST-1016',
      name: 'Apple iPad Pro 13" M4 (OLED, 512GB 5G)',
      manufacturer: 'Apple',
      model: 'iPad Pro 13 (A2925)',
      serialNumber: 'DMP99120KM4L',
      status: 'AVAILABLE' as const,
      categoryId: categories.catMobile.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2024-05-20'),
      purchaseCost: 1499,
      warrantyExpiry: new Date('2026-05-20'),
      specs: {
        cpu: 'Apple M4 (9-Core CPU, 10-Core GPU)',
        ram: '8 GB Unified Memory',
        storage: '512 GB Tandem OLED Display + 5G',
        os: 'iPadOS 17.5',
      },
      notes: 'Available in Floor 4 IT Vault for field testing checkout.',
    },
    {
      assetTag: 'AST-1017',
      name: 'Apple iPad Air 11" M2 (128GB Wi-Fi)',
      manufacturer: 'Apple',
      model: 'iPad Air 11 (A2902)',
      serialNumber: 'DMP88319LK02',
      status: 'IN_USE' as const,
      categoryId: categories.catMobile.id,
      assignedToId: u.userRachelAdams.id,
      locationId: locations.locNYF5.id,
      purchaseDate: new Date('2024-05-22'),
      purchaseCost: 699,
      warrantyExpiry: new Date('2026-05-22'),
      specs: {
        cpu: 'Apple M2 (8-Core)',
        ram: '8 GB Unified Memory',
        storage: '128 GB Liquid Retina',
        os: 'iPadOS 17.5',
      },
      notes: 'People Operations onboarding kiosk and paperless signing tablet.',
    },
    {
      assetTag: 'AST-1018',
      name: 'Ubiquiti UniFi Dream Machine Special Edition',
      manufacturer: 'Ubiquiti Inc',
      model: 'UDM-SE Enterprise',
      serialNumber: '7483C211440A',
      status: 'IN_USE' as const,
      categoryId: categories.catNetworking.id,
      assignedToId: u.userAlex.id,
      locationId: locations.locLondon.id,
      purchaseDate: new Date('2023-07-11'),
      purchaseCost: 599,
      warrantyExpiry: new Date('2026-07-11'),
      specs: {
        cpu: 'Quad-Core ARM Cortex-A57 at 1.7GHz',
        ram: '4 GB DDR4',
        storage: '128 GB Integrated SSD + 10G SFP+',
        os: 'UniFi OS v3.2.12',
      },
      notes: 'London regional office security gateway & IDS/IPS controller.',
    },
    {
      assetTag: 'AST-1019',
      name: 'Ubiquiti UniFi U6 Enterprise Access Point',
      manufacturer: 'Ubiquiti Inc',
      model: 'U6-Enterprise (Wi-Fi 6E)',
      serialNumber: '7483C25561FA',
      status: 'IN_USE' as const,
      categoryId: categories.catNetworking.id,
      assignedToId: u.userMichael.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2023-09-15'),
      purchaseCost: 299,
      warrantyExpiry: new Date('2026-09-15'),
      specs: {
        cpu: 'Broadcom Tri-Band Wi-Fi 6E SoC',
        ram: '1 GB Memory',
        storage: '10.2 Gbps Total Over-the-air Rate',
        os: 'UniFi AP Firmware v6.6.65',
      },
      notes: 'NY Office Floor 4 East Wing ceiling array AP.',
    },
    {
      assetTag: 'AST-1020',
      name: 'HP LaserJet Enterprise MFP M528dn Printer',
      manufacturer: 'HP Inc',
      model: 'LaserJet MFP M528dn',
      serialNumber: 'CNB1N39201',
      status: 'IN_USE' as const,
      categoryId: categories.catPeripherals.id,
      assignedToId: u.userRobertTorres.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2022-08-10'),
      purchaseCost: 1450,
      warrantyExpiry: new Date('2025-08-10'),
      specs: {
        cpu: '1.2 GHz Processor',
        ram: '1.5 GB Memory',
        storage: '500 GB Encrypted Secure Hard Disk',
        os: 'HP FutureSmart 5 Firmware',
      },
      notes: 'Floor 4 secure badge-release printer with PIN verification.',
    },
    {
      assetTag: 'AST-1021',
      name: 'CalDigit TS4 Thunderbolt 4 Dock 18-Port',
      manufacturer: 'CalDigit',
      model: 'TS4-US-AMZ',
      serialNumber: 'CDTS48891024',
      status: 'IN_USE' as const,
      categoryId: categories.catPeripherals.id,
      assignedToId: u.userMarcusVance.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2024-02-10'),
      purchaseCost: 399,
      warrantyExpiry: new Date('2026-02-10'),
      specs: {
        cpu: 'Intel Goshen Ridge JHL8440 Controller',
        ram: '98W Laptop Charging PD',
        storage: '18 I/O Ports with 2.5GbE Ethernet',
        os: 'Firmware v39.1',
      },
      notes: 'Primary desk hub for AST-1001 design station.',
    },
    {
      assetTag: 'AST-1022',
      name: 'Poly Studio X50 Video Bar & TC8 Controller',
      manufacturer: 'HP / Poly',
      model: 'Studio X50 (Zoom & Teams Native)',
      serialNumber: '8220019284AA',
      status: 'IN_USE' as const,
      categoryId: categories.catPeripherals.id,
      assignedToId: u.userAlex.id,
      locationId: locations.locNYF5.id,
      purchaseDate: new Date('2023-06-20'),
      purchaseCost: 3200,
      warrantyExpiry: new Date('2026-06-20'),
      specs: {
        cpu: 'Qualcomm Snapdragon 845 SoC',
        ram: '4 GB RAM + 4K Beamforming Camera Array',
        storage: 'Room Filling Acoustic Stereo Chambers',
        os: 'Poly VideoOS 4.1.2',
      },
      notes: 'Boardroom executive video telepresence conferencing bar.',
    },
    {
      assetTag: 'AST-1023',
      name: 'Lenovo ThinkPad X1 Carbon Gen 11 (RMA Service)',
      manufacturer: 'Lenovo',
      model: 'ThinkPad 21HM',
      serialNumber: 'PF-39K21L',
      status: 'MAINTENANCE' as const,
      categoryId: categories.catLaptop.id,
      assignedToId: u.userSarah.id,
      locationId: locations.locSF.id,
      purchaseDate: new Date('2023-08-14'),
      purchaseCost: 1950,
      warrantyExpiry: new Date('2026-08-14'),
      specs: {
        cpu: 'Intel Core i7-1365U vPro',
        ram: '32 GB LPDDR5-5200',
        storage: '512 GB PCIe 4.0 SSD',
        os: 'Windows 11 Pro 23H2',
      },
      notes: 'Sent to Lenovo Premier Support Depot for battery sensor replacement.',
    },
    {
      assetTag: 'AST-1024',
      name: 'Dell Latitude 5440 Laptop (Buffer Stock)',
      manufacturer: 'Dell',
      model: 'Latitude 5440 Business',
      serialNumber: '7N881M2',
      status: 'AVAILABLE' as const,
      categoryId: categories.catLaptop.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2024-03-01'),
      purchaseCost: 1250,
      warrantyExpiry: new Date('2027-03-01'),
      specs: {
        cpu: 'Intel Core i5-1335U (10-Core)',
        ram: '16 GB DDR4-3200',
        storage: '512 GB NVMe SSD',
        os: 'Windows 11 Enterprise (Autopilot Ready)',
      },
      notes: 'Pre-imaged spare laptop in secure IT storage room.',
    },
    {
      assetTag: 'AST-1025',
      name: 'Apple MacBook Pro 13" M1 (Decommissioned)',
      manufacturer: 'Apple',
      model: 'MacBookPro17,1',
      serialNumber: 'C02D1839MD6R',
      status: 'RETIRED' as const,
      categoryId: categories.catLaptop.id,
      locationId: locations.locNYF4.id,
      purchaseDate: new Date('2020-12-10'),
      purchaseCost: 1499,
      warrantyExpiry: new Date('2023-12-10'),
      specs: {
        cpu: 'Apple M1 (8-Core)',
        ram: '16 GB Unified Memory',
        storage: '512 GB SSD (Data Sanitized DoD 5220.22-M)',
        os: 'macOS Big Sur (Wiped)',
      },
      notes: 'Retired after 4-year lifecycle completion. Certified certificate of destruction.',
    },
  ];

  const createdAssets: Record<string, { id: string; assetTag: string }> = {};

  for (const asset of assetDefinitions) {
    const record = await prisma.asset.upsert({
      where: { assetTag: asset.assetTag },
      update: {},
      create: asset,
    });
    createdAssets[asset.assetTag] = record;
  }

  return createdAssets;
}
