import type { PrismaClient } from '@prisma/client';

export async function seedAudit(prisma: PrismaClient) {
  // Fetch related records to establish full relational integrity
  const [users, roles, assets, licenses, inventory, directoryGroups] = await Promise.all([
    prisma.user.findMany(),
    prisma.role.findMany(),
    prisma.asset.findMany(),
    prisma.license.findMany(),
    prisma.inventoryItem.findMany(),
    prisma.directoryGroup.findMany(),
  ]);

  const userMap = new Map<string, string>();
  for (const u of users) {
    userMap.set(u.email, u.id);
  }

  const roleMap = new Map<string, string>();
  for (const r of roles) {
    roleMap.set(r.name, r.id);
  }

  const assetMap = new Map<string, string>();
  for (const a of assets) {
    assetMap.set(a.assetTag, a.id);
  }

  const licenseMap = new Map<string, string>();
  for (const l of licenses) {
    licenseMap.set(l.name, l.id);
    licenseMap.set(l.id, l.id);
  }

  const invMap = new Map<string, string>();
  for (const i of inventory) {
    invMap.set(i.sku, i.id);
  }

  const groupMap = new Map<string, string>();
  for (const g of directoryGroups) {
    groupMap.set(g.name, g.id);
    groupMap.set(g.id, g.id);
  }

  const auditLogs = [
    // 1. User Lifecycle & Identity Provisioning
    {
      id: 'aud-001',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'USER_PROVISION',
      severity: 'Info',
      status: 'Success',
      entity: 'User Sophia Patel',
      entityType: 'User',
      entityId: userMap.get('sophia.patel@company.com') || 'usr-sophia-patel',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 201,
      durationMs: 42.5,
      timestamp: new Date('2026-08-19T08:30:00Z'),
      details:
        'Provisioned new Active Directory user account for Sophia Patel with automated Entra ID synchronization and default engineering security groups.',
      diffPayload: {
        requestId: 'req_prov_9941a',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Info',
        status: 'Success',
        before: null,
        after: {
          username: 'sophia.patel',
          email: 'sophia.patel@company.com',
          employeeCode: 'EMP-1006',
          role: 'Employee',
          ouPath: 'OU=Engineering,OU=HQ,DC=uims,DC=internal',
          adGroup: 'GR_HQ_EngineeringCore',
          status: 'ACTIVE',
        },
      },
      oldValue: null,
      newValue: {
        username: 'sophia.patel',
        email: 'sophia.patel@company.com',
        role: 'Employee',
        status: 'ACTIVE',
      },
    },
    {
      id: 'aud-002',
      userId: userMap.get('sarah.chen@company.com') || null,
      userName: 'Sarah Chen',
      userEmail: 'sarah.chen@company.com',
      action: 'USER_PASSWORD_RESET',
      severity: 'Warning',
      status: 'Success',
      entity: 'User Thomas Wright',
      entityType: 'User',
      entityId: userMap.get('thomas.wright@company.com') || 'usr-thomas-wright',
      ipAddress: '192.168.10.12 (SF HQ)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) UIMS-SecOps/2.4',
      statusCode: 200,
      durationMs: 18.2,
      timestamp: new Date('2026-08-19T09:15:00Z'),
      details:
        'Executed administrative password reset for Thomas Wright following verification of Identity Desk Ticket IT-5502. Forced password rotation at next logon.',
      diffPayload: {
        requestId: 'req_pwd_7731b',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) UIMS-SecOps/2.4',
        ipAddress: '192.168.10.12',
        severity: 'Warning',
        status: 'Success',
        before: {
          passwordLastChanged: '2026-05-10T14:20:00Z',
          mustChangePassword: false,
        },
        after: {
          passwordLastChanged: '2026-08-19T09:15:00Z',
          mustChangePassword: true,
          tempPasswordPolicyApplied: true,
        },
      },
      oldValue: { mustChangePassword: false },
      newValue: { mustChangePassword: true },
    },
    {
      id: 'aud-003',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'USER_SUSPEND',
      severity: 'Warning',
      status: 'Success',
      entity: 'User Thomas Wright',
      entityType: 'User',
      entityId: userMap.get('thomas.wright@company.com') || 'usr-thomas-wright',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 200,
      durationMs: 31.0,
      timestamp: new Date('2026-08-19T10:00:00Z'),
      details:
        'Suspended domain account for contractor Thomas Wright upon scheduled completion of contract term. Revoked active Kerberos ticket-granting tickets (TGT).',
      diffPayload: {
        requestId: 'req_susp_3389c',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Warning',
        status: 'Success',
        before: {
          status: 'ACTIVE',
          isLocked: false,
          isClosed: false,
        },
        after: {
          status: 'SUSPENDED',
          isLocked: true,
          isClosed: true,
          suspensionReason: 'Contractor end-of-term audit',
        },
      },
      oldValue: { status: 'ACTIVE', isLocked: false },
      newValue: { status: 'SUSPENDED', isLocked: true },
    },
    {
      id: 'aud-004',
      userId: null,
      userName: 'Active Directory Domain Controller (DC01)',
      userEmail: 'dc01@uims.internal',
      action: 'USER_LOCKOUT',
      severity: 'Critical',
      status: 'Blocked',
      entity: 'User David Kim',
      entityType: 'User',
      entityId: userMap.get('david.kim@company.com') || 'usr-david-kim',
      ipAddress: '198.51.100.44 (External Gateway)',
      userAgent: 'Kerberos-Auth-Engine/1.10',
      statusCode: 423,
      durationMs: 5.1,
      timestamp: new Date('2026-08-19T11:20:00Z'),
      details:
        'Automated security policy lockout triggered for account david.kim after 5 consecutive failed Kerberos pre-authentication attempts from external untrusted IP.',
      diffPayload: {
        requestId: 'sec_lockout_8820d',
        userAgent: 'Kerberos-Auth-Engine/1.10',
        ipAddress: '198.51.100.44',
        severity: 'Critical',
        status: 'Blocked',
        before: {
          failedLogonAttempts: 4,
          isLocked: false,
        },
        after: {
          failedLogonAttempts: 5,
          isLocked: true,
          lockDurationMinutes: 30,
          lockoutTimestamp: '2026-08-19T11:20:00Z',
        },
      },
      oldValue: { failedLogonAttempts: 4, isLocked: false },
      newValue: { failedLogonAttempts: 5, isLocked: true },
    },
    {
      id: 'aud-005',
      userId: userMap.get('sarah.chen@company.com') || null,
      userName: 'Sarah Chen',
      userEmail: 'sarah.chen@company.com',
      action: 'USER_UNLOCK',
      severity: 'Info',
      status: 'Success',
      entity: 'User David Kim',
      entityType: 'User',
      entityId: userMap.get('david.kim@company.com') || 'usr-david-kim',
      ipAddress: '192.168.10.12 (SF HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 200,
      durationMs: 14.8,
      timestamp: new Date('2026-08-19T11:45:00Z'),
      details:
        'Unlocked domain user account for David Kim following out-of-band video identity verification (Incident INC-4091). Reset bad logon count to zero.',
      diffPayload: {
        requestId: 'req_unlk_2218e',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.10.12',
        severity: 'Info',
        status: 'Success',
        before: {
          isLocked: true,
          failedLogonAttempts: 5,
        },
        after: {
          isLocked: false,
          failedLogonAttempts: 0,
          verificationMethod: 'OOB Voice & Biometric MFA',
        },
      },
      oldValue: { isLocked: true },
      newValue: { isLocked: false },
    },
    {
      id: 'aud-006',
      userId: userMap.get('sarah.chen@company.com') || null,
      userName: 'Sarah Chen',
      userEmail: 'sarah.chen@company.com',
      action: 'MFA_RESET',
      severity: 'Warning',
      status: 'Success',
      entity: 'User Thomas Wright',
      entityType: 'User',
      entityId: userMap.get('thomas.wright@company.com') || 'usr-thomas-wright',
      ipAddress: '192.168.10.12 (SF HQ)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) UIMS-SecOps/2.4',
      statusCode: 200,
      durationMs: 22.0,
      timestamp: new Date('2026-08-19T13:10:00Z'),
      details:
        'Revoked lost Microsoft Authenticator software TOTP token and generated emergency single-use bypass registration code for Thomas Wright.',
      diffPayload: {
        requestId: 'req_mfa_5541f',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) UIMS-SecOps/2.4',
        ipAddress: '192.168.10.12',
        severity: 'Warning',
        status: 'Success',
        before: {
          mfaEnrolled: true,
          mfaDevice: 'iPhone 13 Pro (iOS 17.4)',
          mfaMethod: 'TOTP + Push',
        },
        after: {
          mfaEnrolled: false,
          bypassCodeGenerated: true,
          expirationHours: 4,
        },
      },
      oldValue: { mfaEnrolled: true },
      newValue: { mfaEnrolled: false },
    },

    // 2. Role Governance & Elevated Privilege Lifecycle
    {
      id: 'aud-007',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'ROLE_ASSIGNMENT_CHANGE',
      severity: 'Info',
      status: 'Success',
      entity: 'Role Manager',
      entityType: 'Role',
      entityId: roleMap.get('Manager') || 'rol-manager',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 200,
      durationMs: 28.4,
      timestamp: new Date('2026-08-19T14:00:00Z'),
      details:
        'Promoted Elena Rostova from Employee to Manager role in accordance with Human Resources promotion authorization HR-2026-091.',
      diffPayload: {
        requestId: 'req_role_6619g',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Info',
        status: 'Success',
        before: {
          targetUser: 'elena.rostova@company.com',
          roleName: 'Employee',
          approvalAuthority: false,
        },
        after: {
          targetUser: 'elena.rostova@company.com',
          roleName: 'Manager',
          approvalAuthority: true,
          procurementLimitUsd: 25000,
        },
      },
      oldValue: { roleName: 'Employee' },
      newValue: { roleName: 'Manager' },
    },
    {
      id: 'aud-008',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'PRIVILEGE_ELEVATION_GRANT',
      severity: 'Warning',
      status: 'Success',
      entity: 'Role Super Admin',
      entityType: 'Role',
      entityId: roleMap.get('Super Admin') || 'rol-super-admin',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 200,
      durationMs: 36.7,
      timestamp: new Date('2026-08-19T15:30:00Z'),
      details:
        'Approved Just-In-Time (JIT) temporary Super Admin privilege elevation for Sarah Chen during core data center routing maintenance (Ticket CHG-8821).',
      diffPayload: {
        requestId: 'req_elevation_331h',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Warning',
        status: 'Success',
        before: {
          targetUser: 'sarah.chen@company.com',
          activeRole: 'Technician',
          breakGlassActive: false,
        },
        after: {
          targetUser: 'sarah.chen@company.com',
          activeRole: 'Super Admin',
          breakGlassActive: true,
          elevationDurationHours: 8,
          expiresAt: '2026-08-19T23:30:00Z',
          approvedBy: 'Alex Johnson',
        },
      },
      oldValue: { role: 'Technician', breakGlassActive: false },
      newValue: { role: 'Super Admin', breakGlassActive: true },
    },
    {
      id: 'aud-009',
      userId: null,
      userName: 'Privilege Governance Engine',
      userEmail: 'governance-engine@uims.internal',
      action: 'PRIVILEGE_ELEVATION_EXPIRE',
      severity: 'Info',
      status: 'Success',
      entity: 'Role Super Admin',
      entityType: 'Role',
      entityId: roleMap.get('Super Admin') || 'rol-super-admin',
      ipAddress: '127.0.0.1 (Localhost)',
      userAgent: 'UIMS-IAM-Governance/2.4.0',
      statusCode: 200,
      durationMs: 12.3,
      timestamp: new Date('2026-08-19T23:30:00Z'),
      details:
        'Automated Just-In-Time privilege expiration: Revoked temporary Super Admin elevation for Sarah Chen and reverted active session role to Technician.',
      diffPayload: {
        requestId: 'req_expire_4412i',
        userAgent: 'UIMS-IAM-Governance/2.4.0',
        ipAddress: '127.0.0.1',
        severity: 'Info',
        status: 'Success',
        before: {
          targetUser: 'sarah.chen@company.com',
          activeRole: 'Super Admin',
          breakGlassActive: true,
        },
        after: {
          targetUser: 'sarah.chen@company.com',
          activeRole: 'Technician',
          breakGlassActive: false,
          totalElevatedHours: 8.0,
        },
      },
      oldValue: { role: 'Super Admin', breakGlassActive: true },
      newValue: { role: 'Technician', breakGlassActive: false },
    },
    {
      id: 'aud-010',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'PERMISSION_CATALOG_UPDATE',
      severity: 'Info',
      status: 'Success',
      entity: 'Role Technician',
      entityType: 'Permission',
      entityId: roleMap.get('Technician') || 'perm-technician',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 200,
      durationMs: 19.5,
      timestamp: new Date('2026-08-20T01:00:00Z'),
      details:
        'Updated enterprise RBAC permission matrix: Granted Network:export and Setting:read permissions to Technician role following least-privilege review.',
      diffPayload: {
        requestId: 'req_perm_1109j',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Info',
        status: 'Success',
        before: {
          roleName: 'Technician',
          assignedPermissionsCount: 15,
        },
        after: {
          roleName: 'Technician',
          assignedPermissionsCount: 17,
          addedPermissions: ['Network:export', 'Setting:read'],
        },
      },
      oldValue: { assignedPermissionsCount: 15 },
      newValue: { assignedPermissionsCount: 17 },
    },

    // 3. Security Incident & Threat Detection
    {
      id: 'aud-011',
      userId: null,
      userName: 'Security Threat Defense Engine',
      userEmail: 'threat-engine@uims.internal',
      action: 'BRUTE_FORCE_DETECTED',
      severity: 'Critical',
      status: 'Blocked',
      entity: 'Auth Gateway SAML',
      entityType: 'Security',
      entityId: 'sec-saml-gateway',
      ipAddress: '89.248.163.2 (St. Petersburg, RU)',
      userAgent: 'python-requests/2.31.0',
      statusCode: 401,
      durationMs: 1.2,
      timestamp: new Date('2026-08-20T02:15:00Z'),
      details:
        'Distributed dictionary attack and invalid SAML assertion brute force storm detected. Origin IP 89.248.163.2 permanently blocked at edge FortiGate firewall.',
      diffPayload: {
        requestId: 'sec_block_4482k',
        userAgent: 'python-requests/2.31.0',
        ipAddress: '89.248.163.2',
        severity: 'Critical',
        status: 'Blocked',
        before: {
          geoCountry: 'RU',
          riskScore: 98,
          failedAttemptsLastMinute: 142,
        },
        after: {
          actionTaken: 'FIREWALL_DROP_AND_BLACKHOLE_IP',
          reportedToSIRT: true,
          firewallRuleId: 'FW-RULE-DENY-89-248',
        },
      },
      oldValue: { riskScore: 98 },
      newValue: { firewallAction: 'DROP_AND_BLACKHOLE' },
    },
    {
      id: 'aud-012',
      userId: null,
      userName: 'Entra ID Identity Protection',
      userEmail: 'entra-protection@uims.internal',
      action: 'ANOMALOUS_ACCESS',
      severity: 'Critical',
      status: 'Warning',
      entity: 'User Lisa Wang',
      entityType: 'Security',
      entityId: userMap.get('lisa.wang@company.com') || 'usr-lisa-wang',
      ipAddress: '119.74.12.88 (Singapore Hub)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      statusCode: 200,
      durationMs: 8.4,
      timestamp: new Date('2026-08-20T03:30:00Z'),
      details:
        'Impossible travel velocity anomaly detected for account lisa.wang@company.com: Logon from Singapore 14 minutes after active New York session. Mandatory FIDO2 challenge triggered.',
      diffPayload: {
        requestId: 'sec_anom_7781l',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        ipAddress: '119.74.12.88',
        severity: 'Critical',
        status: 'Warning',
        before: {
          lastKnownLocation: 'New York, US (IP: 192.168.1.15)',
          previousLogonTime: '2026-08-20T03:16:00Z',
        },
        after: {
          detectedLocation: 'Singapore, SG (IP: 119.74.12.88)',
          calculatedSpeedKmh: 45000,
          stepUpMfaResult: 'FIDO2_HARDWARE_KEY_CHALLENGE_PASSED',
        },
      },
      oldValue: { lastLocation: 'New York, US' },
      newValue: { detectedLocation: 'Singapore, SG', stepUpMfaPassed: true },
    },
    {
      id: 'aud-013',
      userId: null,
      userName: 'Directory Services Auditor',
      userEmail: 'ad-audit@uims.internal',
      action: 'UNAUTHORIZED_OU_ACCESS',
      severity: 'Critical',
      status: 'Blocked',
      entity: 'OU ExecutiveLeadership',
      entityType: 'Security',
      entityId: 'ou-exec-leadership',
      ipAddress: '192.168.20.102 (Plant 1)',
      userAgent: 'LDAP-Client/3.0',
      statusCode: 403,
      durationMs: 3.2,
      timestamp: new Date('2026-08-20T04:10:00Z'),
      details:
        'Unauthorized LDAP directory traversal attempt on OU=Management,OU=HQ,DC=uims,DC=internal from unauthenticated workstation STOTHPR102. Request denied by DC01.',
      diffPayload: {
        requestId: 'sec_ou_9934m',
        userAgent: 'LDAP-Client/3.0',
        ipAddress: '192.168.20.102',
        severity: 'Critical',
        status: 'Blocked',
        before: {
          targetOu: 'OU=Management,OU=HQ,DC=uims,DC=internal',
          requesterContext: 'Anonymous',
        },
        after: {
          responseCode: 'LDAP_INSUFFICIENT_ACCESS_RIGHTS',
          accessDeniedLogged: true,
        },
      },
      oldValue: { requesterContext: 'Anonymous' },
      newValue: { responseCode: 403 },
    },

    // 4. Asset & License Governance Logs
    {
      id: 'aud-014',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'ASSET_PROVISION',
      severity: 'Info',
      status: 'Success',
      entity: 'Asset AST-1001',
      entityType: 'Asset',
      entityId: assetMap.get('AST-1001') || 'ast-1001',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) UIMS-Client/2.4',
      statusCode: 201,
      durationMs: 55.0,
      timestamp: new Date('2026-08-20T05:00:00Z'),
      details:
        'Provisioned new Apple MacBook Pro 16" M3 Max (AST-1001) to Marcus Vance (Principal Product Designer). Enrolled in Jamf Pro MDM with FileVault 2 encryption.',
      diffPayload: {
        requestId: 'req_88a91b2c',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) UIMS-Client/2.4',
        ipAddress: '192.168.1.15',
        severity: 'Info',
        status: 'Success',
        before: {
          status: 'AVAILABLE',
          assignedToId: null,
          mdmEnrolled: false,
        },
        after: {
          status: 'IN_USE',
          assignedToId: userMap.get('marcus.vance@company.com') || 'usr-marcus-vance',
          assignedTo: 'Marcus Vance',
          assetTag: 'AST-1001',
          purchaseCost: 3499,
          mdmEnrolled: true,
          fileVaultEnabled: true,
        },
      },
      oldValue: { status: 'AVAILABLE', assignedTo: null },
      newValue: { status: 'IN_USE', assignedTo: 'Marcus Vance' },
    },
    {
      id: 'aud-015',
      userId: userMap.get('robert.torres@company.com') || null,
      userName: 'Robert Torres',
      userEmail: 'robert.torres@company.com',
      action: 'ASSET_DECOMMISSION',
      severity: 'Info',
      status: 'Success',
      entity: 'Asset AST-1015',
      entityType: 'Asset',
      entityId: assetMap.get('AST-1015') || 'ast-1015',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 200,
      durationMs: 48.1,
      timestamp: new Date('2026-08-20T05:30:00Z'),
      details:
        'Decommissioned legacy Dell PowerEdge R740 Server (AST-1015) following certified NIST SP 800-88 Rev. 1 cryptographic storage sanitization.',
      diffPayload: {
        requestId: 'req_decom_6621n',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Info',
        status: 'Success',
        before: {
          status: 'IN_USE',
          location: 'NY HQ Server Room 4B',
        },
        after: {
          status: 'RETIRED',
          sanitizeCertificate: 'NIST-88-CRYPTOWIPE-9942',
          retiredDate: '2026-08-19',
        },
      },
      oldValue: { status: 'IN_USE' },
      newValue: { status: 'RETIRED' },
    },
    {
      id: 'aud-016',
      userId: userMap.get('sarah.chen@company.com') || null,
      userName: 'Sarah Chen',
      userEmail: 'sarah.chen@company.com',
      action: 'LICENSE_ALLOCATION',
      severity: 'Info',
      status: 'Success',
      entity: 'License Adobe Creative Cloud',
      entityType: 'License',
      entityId:
        licenseMap.get('Adobe Creative Cloud All Apps Enterprise') ||
        licenseMap.get('lic-adobe') ||
        'lic-adobe',
      ipAddress: '192.168.10.12 (SF HQ)',
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
      statusCode: 200,
      durationMs: 24.3,
      timestamp: new Date('2026-08-20T06:00:00Z'),
      details:
        'Allocated 1 Adobe Creative Cloud All Apps Enterprise seat to Chloe Martin (Senior UX Researcher, London Hub).',
      diffPayload: {
        requestId: 'req_99c81a1d',
        userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
        ipAddress: '192.168.10.12',
        severity: 'Info',
        status: 'Success',
        before: {
          usedSeats: 27,
          availableSeats: 3,
        },
        after: {
          usedSeats: 28,
          availableSeats: 2,
          assignedUser: 'Chloe Martin',
          assignedEmail: 'chloe.martin@company.com',
        },
      },
      oldValue: { usedSeats: 27 },
      newValue: { usedSeats: 28, assignedUser: 'Chloe Martin' },
    },
    {
      id: 'aud-017',
      userId: null,
      userName: 'License Optimization Daemon',
      userEmail: 'lic-daemon@uims.internal',
      action: 'LICENSE_RECLAIM',
      severity: 'Info',
      status: 'Success',
      entity: 'License JetBrains All Products',
      entityType: 'License',
      entityId:
        licenseMap.get('JetBrains All Products Pack (Commercial)') ||
        licenseMap.get('lic-jetbrains') ||
        'lic-jetbrains',
      ipAddress: '127.0.0.1 (Localhost)',
      userAgent: 'UIMS-License-Optimizer/1.0',
      statusCode: 200,
      durationMs: 15.6,
      timestamp: new Date('2026-08-20T06:30:00Z'),
      details:
        'Automated SaaS license reclamation: Revoked unused JetBrains commercial license from inactive contractor account after 90 days of zero telemetry.',
      diffPayload: {
        requestId: 'req_reclaim_8830o',
        userAgent: 'UIMS-License-Optimizer/1.0',
        ipAddress: '127.0.0.1',
        severity: 'Info',
        status: 'Success',
        before: {
          usedSeats: 38,
          inactiveDays: 92,
        },
        after: {
          usedSeats: 37,
          reclaimedLicenseKey: 'JB-ALL-7731-9941-PPX1-2027',
          costSavingsAnnualUsd: 249,
        },
      },
      oldValue: { usedSeats: 38 },
      newValue: { usedSeats: 37 },
    },

    // 5. Infrastructure & System Operations
    {
      id: 'aud-018',
      userId: userMap.get('michael.wong@company.com') || null,
      userName: 'Michael Wong',
      userEmail: 'michael.wong@company.com',
      action: 'CONFIG_CHANGE',
      severity: 'Warning',
      status: 'Success',
      entity: 'FortiGate 200F Firewall',
      entityType: 'Network',
      entityId: 'net-fortigate-200f',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'FortiOS-API/7.4.3 (SecOps-Session)',
      statusCode: 200,
      durationMs: 88.0,
      timestamp: new Date('2026-08-20T07:00:00Z'),
      details:
        'Updated IPSec VPN Phase 2 cryptographic proposals to AES-256-GCM / SHA-384 and disabled legacy TLS 1.0/1.1 protocols.',
      diffPayload: {
        requestId: 'req_netcfg_5512p',
        userAgent: 'FortiOS-API/7.4.3 (SecOps-Session)',
        ipAddress: '192.168.1.15',
        severity: 'Warning',
        status: 'Success',
        before: {
          minTlsVersion: '1.1',
          cipherSuites: 'AES-128-CBC / SHA-1',
        },
        after: {
          minTlsVersion: '1.3',
          cipherSuites: 'AES-256-GCM / SHA-384',
          pfsGroup: 'DH-19',
        },
      },
      oldValue: { minTlsVersion: '1.1' },
      newValue: { minTlsVersion: '1.3', cipherSuites: 'AES-256-GCM-SHA384' },
    },
    {
      id: 'aud-019',
      userId: null,
      userName: 'System Daemon Engine',
      userEmail: 'daemon@uims.internal',
      action: 'SNAPSHOT_VERIFY',
      severity: 'Info',
      status: 'Success',
      entity: 'PostgreSQL Daily Snapshot',
      entityType: 'Storage',
      entityId: 'snap-postgres-daily',
      ipAddress: '127.0.0.1 (Localhost)',
      userAgent: 'UIMS-Backup-Daemon/2.4.0',
      statusCode: 200,
      durationMs: 120.4,
      timestamp: new Date('2026-08-20T07:30:00Z'),
      details:
        'Automated nightly database snapshot sha256 checksum verified and mirrored to Synology SAN NAS immutable off-site vault.',
      diffPayload: {
        requestId: 'req_snap_3301q',
        userAgent: 'UIMS-Backup-Daemon/2.4.0',
        ipAddress: '127.0.0.1',
        severity: 'Info',
        status: 'Success',
        before: {
          lastVerifiedSnapshot: '2026-08-19T00:00:00Z',
        },
        after: {
          snapshotId: 'snap_20260820_0000',
          sha256Checksum: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
          mirrorStatus: 'SYNCED_IMMUTABLE',
        },
      },
      oldValue: { lastVerifiedSnapshot: '2026-08-19' },
      newValue: { mirrorStatus: 'SYNCED_IMMUTABLE' },
    },
    {
      id: 'aud-020',
      userId: userMap.get('admin@uims.internal') || null,
      userName: 'Alex Johnson',
      userEmail: 'admin@uims.internal',
      action: 'INVENTORY_REORDER',
      severity: 'Info',
      status: 'Success',
      entity: 'SKU ACC-MSE-MX3S-GRY',
      entityType: 'Inventory',
      entityId: invMap.get('ACC-MSE-MX3S-GRY') || 'sku-mx3s-gry',
      ipAddress: '192.168.1.15 (NY HQ)',
      userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
      statusCode: 201,
      durationMs: 34.2,
      timestamp: new Date('2026-08-20T08:00:00Z'),
      details:
        'Generated automated replenishment purchase requisition PO-9921 for 20 units of Logitech MX Master 3S Performance Mice.',
      diffPayload: {
        requestId: 'req_inv_1182r',
        userAgent: 'UIMS-AdminConsole/2.4.0 (macOS; arm64)',
        ipAddress: '192.168.1.15',
        severity: 'Info',
        status: 'Success',
        before: {
          stockQuantity: 2,
          minThreshold: 5,
        },
        after: {
          stockQuantity: 2,
          reorderQuantity: 20,
          purchaseOrder: 'PO-9921',
          supplier: 'CDW Logistics',
        },
      },
      oldValue: { stockQuantity: 2 },
      newValue: { stockQuantity: 2, reorderQuantity: 20, purchaseOrder: 'PO-9921' },
    },
  ];

  for (const log of auditLogs) {
    await prisma.auditLog.upsert({
      where: { id: log.id },
      update: {
        userId: log.userId,
        userName: log.userName,
        userEmail: log.userEmail,
        action: log.action,
        severity: log.severity,
        status: log.status,
        entity: log.entity,
        entityType: log.entityType,
        entityId: log.entityId,
        ipAddress: log.ipAddress,
        userAgent: log.userAgent,
        statusCode: log.statusCode,
        durationMs: log.durationMs,
        timestamp: log.timestamp,
        details: log.details,
        diffPayload: log.diffPayload,
        oldValue: log.oldValue,
        newValue: log.newValue,
      },
      create: {
        id: log.id,
        userId: log.userId,
        userName: log.userName,
        userEmail: log.userEmail,
        action: log.action,
        severity: log.severity,
        status: log.status,
        entity: log.entity,
        entityType: log.entityType,
        entityId: log.entityId,
        ipAddress: log.ipAddress,
        userAgent: log.userAgent,
        statusCode: log.statusCode,
        durationMs: log.durationMs,
        timestamp: log.timestamp,
        details: log.details,
        diffPayload: log.diffPayload,
        oldValue: log.oldValue,
        newValue: log.newValue,
      },
    });
  }
}
