import type { PrismaClient } from '@prisma/client';

export async function seedDirectory(prisma: PrismaClient) {
  // 10. Directory Users (Active Directory / LDAP / Okta Sync)
  const directoryUsersData = [
    {
      username: 'alex.johnson',
      email: 'admin@uims.internal',
      displayName: 'Alex Johnson',
      jobTitle: 'VP of Information Technology',
      department: 'IT & Infrastructure',
      role: 'Super Admin',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 234-5678',
      location: 'NY HQ - Floor 4',
      source: 'LOCAL' as const,
      adInitialPassword: 'Ad#AlexJohnson2026!',
      mailInitialPassword: 'Mail#AlexJohnson2026@',
      hasMailbox: true,
      mailboxType: 'Executive',
      quotaUsed: 18.4,
      quotaTotal: 100,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['alex@company.com', 'cio@company.com'],
    },
    {
      username: 'sarah.chen',
      email: 'sarah.chen@company.com',
      displayName: 'Sarah Chen',
      jobTitle: 'Senior Systems Administrator',
      department: 'IT & Infrastructure',
      role: 'IT Specialist',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 345-6789',
      location: 'SF HQ - Tech Bay',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#SarahChen2026!',
      mailInitialPassword: 'Mail#SarahChen2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 24.2,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['schen@company.com'],
    },
    {
      username: 'michael.wong',
      email: 'michael.wong@company.com',
      displayName: 'Michael Wong',
      jobTitle: 'Senior Network Architect',
      department: 'IT & Infrastructure',
      role: 'Admin',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 345-1122',
      location: 'NY HQ - Floor 4',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#MichaelWong2026!',
      mailInitialPassword: 'Mail#MichaelWong2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 14.5,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['mwong@company.com'],
    },
    {
      username: 'marcus.bell',
      email: 'compliance@uims.internal',
      displayName: 'Marcus Bell',
      jobTitle: 'Principal Security Compliance Auditor',
      department: 'Security & Compliance',
      role: 'Auditor',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+44 20 7946 0912',
      location: 'London Hub',
      source: 'LOCAL' as const,
      adInitialPassword: 'Ad#MarcusBell2026!',
      mailInitialPassword: 'Mail#MarcusBell2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 8.7,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['mbell@company.com', 'sec-auditor@company.com'],
    },
    {
      username: 'marcus.vance',
      email: 'marcus.vance@company.com',
      displayName: 'Marcus Vance',
      jobTitle: 'Principal Product Designer',
      department: 'Product & Design',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 456-7890',
      location: 'NY HQ - Floor 4',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#MarcusVance2026!',
      mailInitialPassword: 'Mail#MarcusVance2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 12.8,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['marcus@company.com', 'design-lead@company.com'],
    },
    {
      username: 'chloe.martin',
      email: 'chloe.martin@company.com',
      displayName: 'Chloe Martin',
      jobTitle: 'Senior UX Researcher',
      department: 'Product & Design',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+44 20 7946 0881',
      location: 'London Hub',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#ChloeMartin2026!',
      mailInitialPassword: 'Mail#ChloeMartin2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 9.3,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['cmartin@company.com'],
    },
    {
      username: 'david.kim',
      email: 'david.kim@company.com',
      displayName: 'David Kim',
      jobTitle: 'Lead Cloud Architect',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-8901',
      location: 'Remote - US East',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#DavidKim2026!',
      mailInitialPassword: 'Mail#DavidKim2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 15.2,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['dkim@company.com'],
    },
    {
      username: 'sophia.patel',
      email: 'sophia.patel@company.com',
      displayName: 'Sophia Patel',
      jobTitle: 'Senior Staff Fullstack Engineer',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-2233',
      location: 'SF HQ - Tech Bay',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#SophiaPatel2026!',
      mailInitialPassword: 'Mail#SophiaPatel2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 22.1,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['spatel@company.com'],
    },
    {
      username: 'liam.nguyen',
      email: 'liam.nguyen@company.com',
      displayName: 'Liam Nguyen',
      jobTitle: 'Lead DevOps & SRE Architect',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-4455',
      location: 'Remote - US West',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#LiamNguyen2026!',
      mailInitialPassword: 'Mail#LiamNguyen2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 16.4,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['lnguyen@company.com'],
    },
    {
      username: 'carlos.mendez',
      email: 'carlos.mendez@company.com',
      displayName: 'Carlos Mendez',
      jobTitle: 'Senior Backend Platform Engineer',
      department: 'Engineering',
      role: 'Developer',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 567-7788',
      location: 'NY HQ - Floor 4',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#CarlosMendez2026!',
      mailInitialPassword: 'Mail#CarlosMendez2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 11.2,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['cmendez@company.com'],
    },
    {
      username: 'elena.rostova',
      email: 'elena.rostova@company.com',
      displayName: 'Elena Rostova',
      jobTitle: 'Director of Growth Marketing',
      department: 'Marketing',
      role: 'Manager',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 678-9012',
      location: 'London Hub',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#ElenaRostova2026!',
      mailInitialPassword: 'Mail#ElenaRostova2026@',
      hasMailbox: true,
      mailboxType: 'Executive',
      quotaUsed: 31.4,
      quotaTotal: 100,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['elena@company.com'],
    },
    {
      username: 'robert.torres',
      email: 'robert.torres@company.com',
      displayName: 'Robert Torres',
      jobTitle: 'IT Infrastructure Operations Manager',
      department: 'IT & Infrastructure',
      role: 'Manager',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 678-3344',
      location: 'NY HQ - Floor 4',
      source: 'LOCAL' as const,
      adInitialPassword: 'Ad#RobertTorres2026!',
      mailInitialPassword: 'Mail#RobertTorres2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 19.8,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['rtorres@company.com'],
    },
    {
      username: 'lisa.wang',
      email: 'lisa.wang@company.com',
      displayName: 'Lisa Wang',
      jobTitle: 'Financial Controller',
      department: 'Finance',
      role: 'Manager',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+65 6789 0123',
      location: 'Singapore Hub',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#LisaWang2026!',
      mailInitialPassword: 'Mail#LisaWang2026@',
      hasMailbox: true,
      mailboxType: 'Executive',
      quotaUsed: 26.5,
      quotaTotal: 100,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['lwang@company.com', 'finance-lead@company.com'],
    },
    {
      username: 'rachel.adams',
      email: 'rachel.adams@company.com',
      displayName: 'Rachel Adams',
      jobTitle: 'Head of People Operations',
      department: 'Human Resources',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 890-1234',
      location: 'NY HQ - Floor 5',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#RachelAdams2026!',
      mailInitialPassword: 'Mail#RachelAdams2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 9.4,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: true,
      aliases: ['radams@company.com', 'hr-lead@company.com'],
    },
    {
      username: 'james.wilson',
      email: 'james.wilson@company.com',
      displayName: 'James Wilson',
      jobTitle: 'Senior Corporate Counsel',
      department: 'Legal & Governance',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 901-2345',
      location: 'NY HQ - Floor 5',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#JamesWilson2026!',
      mailInitialPassword: 'Mail#JamesWilson2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 14.1,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['jwilson@company.com', 'legal@company.com'],
    },
    {
      username: 'hannah.scott',
      email: 'hannah.scott@company.com',
      displayName: 'Hannah Scott',
      jobTitle: 'Strategic Account Executive',
      department: 'Sales',
      role: 'Employee',
      accountStatus: 'ACTIVE' as const,
      twoFactorEnabled: true,
      phone: '+1 (555) 901-6789',
      location: 'Remote - US Central',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#HannahScott2026!',
      mailInitialPassword: 'Mail#HannahScott2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 21.0,
      quotaTotal: 50,
      mailStatus: 'Active',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: ['hscott@company.com'],
    },
    {
      username: 'thomas.wright',
      email: 'thomas.wright@company.com',
      displayName: 'Thomas Wright',
      jobTitle: 'Junior QA Engineer (Contractor)',
      department: 'Engineering',
      role: 'Employee',
      accountStatus: 'SUSPENDED' as const,
      twoFactorEnabled: false,
      phone: '+1 (555) 789-0123',
      location: 'Remote - EMEA',
      source: 'LOCAL' as const,
      adInitialPassword: 'Ad#ThomasWright2026!',
      mailInitialPassword: 'Mail#ThomasWright2026@',
      hasMailbox: false,
      mailboxType: 'User',
      quotaUsed: 0,
      quotaTotal: 50,
      mailStatus: 'Suspended',
      forwardingAddress: null,
      autoReplyEnabled: false,
      aliases: [],
    },
    {
      username: 'jessica.taylor',
      email: 'jessica.taylor@company.com',
      displayName: 'Jessica Taylor',
      jobTitle: 'Content Strategist (Leave of Absence)',
      department: 'Marketing',
      role: 'Employee',
      accountStatus: 'SUSPENDED' as const,
      twoFactorEnabled: true,
      phone: '+44 20 7946 0999',
      location: 'London Hub',
      source: 'AZURE_AD' as const,
      adInitialPassword: 'Ad#JessicaTaylor2026!',
      mailInitialPassword: 'Mail#JessicaTaylor2026@',
      hasMailbox: true,
      mailboxType: 'User',
      quotaUsed: 17.6,
      quotaTotal: 50,
      mailStatus: 'Suspended',
      forwardingAddress: 'marketing-team@company.com',
      autoReplyEnabled: true,
      aliases: ['jtaylor@company.com'],
    },
  ];

  for (const du of directoryUsersData) {
    await prisma.directoryUser.upsert({
      where: { email: du.email },
      update: du,
      create: du,
    });
  }

  // 11. Directory Groups
  const directoryGroups = [
    {
      id: 'grp-all-company',
      name: 'All Company Employees',
      email: 'all-employees@company.com',
      memberCount: 148,
      scope: 'Internal Only',
      managedBy: 'People Operations (Rachel Adams)',
      description: 'Broadcast distribution list for entire enterprise workforce.',
    },
    {
      id: 'grp-engineering-core',
      name: 'Engineering & DevOps Core',
      email: 'engineering-core@company.com',
      memberCount: 52,
      scope: 'Internal Only',
      managedBy: 'David Kim',
      description: 'Software engineers, architects, backend and frontend developers.',
    },
    {
      id: 'grp-it-infrastructure',
      name: 'IT Infrastructure & Operations',
      email: 'it-ops@company.com',
      memberCount: 12,
      scope: 'Internal Only',
      managedBy: 'Robert Torres',
      description: 'Systems, network, and data center engineering teams.',
    },
    {
      id: 'grp-security-sirt',
      name: 'Security Incident Response Team (SIRT)',
      email: 'security-response@company.com',
      memberCount: 8,
      scope: 'Restricted / Security High',
      managedBy: 'Sarah Chen',
      description: 'SecOps engineers, auditors and 24/7 incident responders.',
    },
    {
      id: 'grp-product-design',
      name: 'Product Design & UX Research',
      email: 'product-design@company.com',
      memberCount: 14,
      scope: 'Internal Only',
      managedBy: 'Marcus Vance',
      description: 'Design systems, UI/UX and product managers.',
    },
    {
      id: 'grp-growth-marketing',
      name: 'Growth Marketing & Public Relations',
      email: 'press-media@company.com',
      memberCount: 16,
      scope: 'Public / External Allowed',
      managedBy: 'Elena Rostova',
      description: 'Marketing campaigns, social media and PR press inquiries.',
    },
    {
      id: 'grp-finance-procure',
      name: 'Finance & Hardware Procurement',
      email: 'procurement-finance@company.com',
      memberCount: 9,
      scope: 'Internal Only',
      managedBy: 'Lisa Wang',
      description: 'Hardware asset budgets, software renewals and vendor contracts.',
    },
    {
      id: 'grp-executive-steering',
      name: 'Executive Steering Committee',
      email: 'executive-leadership@company.com',
      memberCount: 7,
      scope: 'Confidential / Board Level',
      managedBy: 'Alex Johnson',
      description: 'Executive VPs, Directors and Legal Counsel.',
    },
  ];

  for (const dg of directoryGroups) {
    await prisma.directoryGroup.upsert({
      where: { id: dg.id },
      update: {},
      create: dg,
    });
  }

  // 12. Email Accounts (14 Enterprise Mailboxes & Inboxes)
  const emailAccounts = [
    {
      address: 'alex.johnson@company.com',
      displayName: 'Alex Johnson (VP of IT)',
      type: 'Executive',
      quotaUsed: 18.4,
      quotaTotal: 100,
      status: 'Active',
      department: 'IT & Infrastructure',
      autoReplyEnabled: false,
      aliases: ['alex@company.com', 'cio@company.com'],
    },
    {
      address: 'sarah.chen@company.com',
      displayName: 'Sarah Chen (IT Specialist)',
      type: 'User',
      quotaUsed: 24.2,
      quotaTotal: 50,
      status: 'Active',
      department: 'IT & Infrastructure',
      autoReplyEnabled: false,
      aliases: ['schen@company.com'],
    },
    {
      address: 'it-support@company.com',
      displayName: 'IT Helpdesk Inbound Queue',
      type: 'Shared',
      quotaUsed: 42.1,
      quotaTotal: 100,
      status: 'Active',
      department: 'IT & Infrastructure',
      autoReplyEnabled: true,
      aliases: ['helpdesk@company.com', 'support@company.com', 'itservicedesk@company.com'],
    },
    {
      address: 'security-alerts@company.com',
      displayName: 'SOC Security & Automated Alerts',
      type: 'Shared',
      quotaUsed: 68.5,
      quotaTotal: 100,
      status: 'Active',
      department: 'Security & Compliance',
      autoReplyEnabled: false,
      aliases: ['soc@company.com', 'abuse@company.com'],
    },
    {
      address: 'sales-team@company.com',
      displayName: 'Global Sales Shared Pipeline',
      type: 'Shared',
      quotaUsed: 46.8,
      quotaTotal: 50,
      status: 'Warning',
      department: 'Sales',
      autoReplyEnabled: true,
      aliases: ['deals@company.com', 'inquiries@company.com', 'revenue@company.com'],
    },
    {
      address: 'marcus.vance@company.com',
      displayName: 'Marcus Vance (Principal Design)',
      type: 'User',
      quotaUsed: 12.8,
      quotaTotal: 50,
      status: 'Active',
      department: 'Product & Design',
      autoReplyEnabled: false,
      aliases: ['marcus@company.com', 'design-lead@company.com'],
    },
    {
      address: 'david.kim@company.com',
      displayName: 'David Kim (Cloud Architect)',
      type: 'User',
      quotaUsed: 15.2,
      quotaTotal: 50,
      status: 'Active',
      department: 'Engineering',
      autoReplyEnabled: false,
      aliases: ['dkim@company.com'],
    },
    {
      address: 'elena.rostova@company.com',
      displayName: 'Elena Rostova (Marketing Director)',
      type: 'Executive',
      quotaUsed: 31.4,
      quotaTotal: 100,
      status: 'Active',
      department: 'Marketing',
      autoReplyEnabled: false,
      aliases: ['elena@company.com'],
    },
    {
      address: 'finance-invoices@company.com',
      displayName: 'Accounts Payable & Invoices',
      type: 'Shared',
      quotaUsed: 38.0,
      quotaTotal: 50,
      status: 'Active',
      department: 'Finance',
      autoReplyEnabled: true,
      aliases: ['billing@company.com', 'invoices@company.com'],
    },
    {
      address: 'hr-confidential@company.com',
      displayName: 'People Ops Confidential Inbox',
      type: 'Shared',
      quotaUsed: 9.4,
      quotaTotal: 50,
      status: 'Active',
      department: 'Human Resources',
      autoReplyEnabled: true,
      aliases: ['careers@company.com', 'hr@company.com'],
    },
    {
      address: 'boardroom-ny@company.com',
      displayName: 'NY Executive Boardroom Calendar Room',
      type: 'Resource',
      quotaUsed: 1.8,
      quotaTotal: 10,
      status: 'Active',
      department: 'Facilities',
      autoReplyEnabled: true,
      aliases: ['room-ny-501@company.com'],
    },
    {
      address: 'conference-sf-alpha@company.com',
      displayName: 'SF Tech Bay Alpha Conference Room',
      type: 'Resource',
      quotaUsed: 0.9,
      quotaTotal: 10,
      status: 'Active',
      department: 'Facilities',
      autoReplyEnabled: true,
      aliases: ['room-sf-201@company.com'],
    },
    {
      address: 'london-executive-suite@company.com',
      displayName: 'London Bishopsgate Video Room',
      type: 'Resource',
      quotaUsed: 2.1,
      quotaTotal: 10,
      status: 'Active',
      department: 'Facilities',
      autoReplyEnabled: true,
      aliases: ['room-lon-1201@company.com'],
    },
  ];

  for (const ea of emailAccounts) {
    await prisma.emailAccount.upsert({
      where: { address: ea.address },
      update: {},
      create: ea,
    });
  }
}
