import type { PrismaClient } from '@prisma/client';

export async function seedInventory(prisma: PrismaClient) {
  const inventoryItems = [
    {
      sku: 'CAB-CAT6A-2M-BLU',
      name: 'Cat6a 10Gbps Snagless RJ45 Patch Cable (2m, Blue)',
      category: 'Cables & Adapters',
      quantity: 64,
      minThreshold: 20,
      unitCost: 6.5,
      location: 'Storage Room A',
      binNumber: 'Bin A-04',
      supplier: 'Monoprice B2B Direct',
      notes: 'Standard high-speed desk patch cables.',
    },
    {
      sku: 'ACC-MSE-MX3S-GRY',
      name: 'Logitech MX Master 3S Wireless Performance Mouse',
      category: 'Peripherals',
      quantity: 2,
      minThreshold: 5,
      unitCost: 99.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 2',
      supplier: 'CDW Direct Enterprise',
      notes: 'Low stock warning! Restock order PO-9921 placed.',
    },
    {
      sku: 'ACC-DOCK-TS4-TB4',
      name: 'CalDigit TS4 Thunderbolt 4 Dock 18-Port (Spare)',
      category: 'Peripherals',
      quantity: 5,
      minThreshold: 3,
      unitCost: 379.0,
      location: 'Storage Room B',
      binNumber: 'Cabinet Secure-1',
      supplier: 'B&H Photo Video B2B',
      notes: 'Emergency hot-swap docks for executive boardrooms.',
    },
    {
      sku: 'RAM-DDR5-32G-SODIMM',
      name: 'Crucial 32GB DDR5-5600 SODIMM Laptop Memory Module',
      category: 'Storage & RAM',
      quantity: 14,
      minThreshold: 6,
      unitCost: 110.0,
      location: 'IT Tech Lab',
      binNumber: 'Anti-Static Drawer 3',
      supplier: 'Newegg Business',
      notes: 'Laptop RAM upgrade kit for engineering workstations.',
    },
    {
      sku: 'SSD-NVME-2TB-SAMS',
      name: 'Samsung 990 Pro 2TB PCIe 4.0 NVMe SSD M.2',
      category: 'Storage & RAM',
      quantity: 8,
      minThreshold: 4,
      unitCost: 175.0,
      location: 'IT Tech Lab',
      binNumber: 'Anti-Static Drawer 1',
      supplier: 'CDW Direct Enterprise',
      notes: 'Fast internal storage drives for engineer machine refreshes.',
    },
    {
      sku: 'PWR-APL-140W-USBC',
      name: 'Apple 140W USB-C Power Adapter + 2m MagSafe 3 Cable',
      category: 'Power & Battery',
      quantity: 16,
      minThreshold: 5,
      unitCost: 99.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 1',
      supplier: 'Apple Enterprise Direct',
      notes: 'Replacement chargers for 16-inch MacBook Pro fleet.',
    },
    {
      sku: 'PWR-DELL-130W-USBC',
      name: 'Dell 130W USB-C AC Adapter with Power Cord',
      category: 'Power & Battery',
      quantity: 12,
      minThreshold: 5,
      unitCost: 79.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 1',
      supplier: 'Dell Premier Direct',
      notes: 'Power bricks for Dell Precision / Latitude laptops.',
    },
    {
      sku: 'ADP-TB-25GBE-LAN',
      name: 'Belkin USB-C to 2.5Gbps Gigabit Ethernet Adapter',
      category: 'Cables & Adapters',
      quantity: 0,
      minThreshold: 5,
      unitCost: 35.0,
      location: 'Storage Room A',
      binNumber: 'Bin A-12',
      supplier: 'Amazon Business',
      notes: 'Completely depleted! Pending supplier restock delivery.',
    },
    {
      sku: 'OPT-SFP-10G-SR-CS',
      name: 'Cisco 10GBASE-SR SFP+ Optical Transceiver Module',
      category: 'Cables & Adapters',
      quantity: 18,
      minThreshold: 6,
      unitCost: 120.0,
      location: 'NY4 DC Tech Cage',
      binNumber: 'Fiber Bin F-02',
      supplier: 'FS.com Enterprise',
      notes: 'Multimode 850nm OM4 fiber transceivers for rack interconnects.',
    },
    {
      sku: 'SEC-YUBIKEY-5C-NFC',
      name: 'Yubico YubiKey 5C NFC FIDO2 / WebAuthn Security Key',
      category: 'Peripherals',
      quantity: 35,
      minThreshold: 10,
      unitCost: 55.0,
      location: 'Storage Room B',
      binNumber: 'Vault Locker 2',
      supplier: 'Yubico Direct B2B',
      notes: 'Mandatory hardware MFA token for all employees with cloud access.',
    },
    {
      sku: 'AUD-HEADSET-POLY-V2',
      name: 'Poly Voyager Focus 2 UC Wireless Bluetooth Headset',
      category: 'Peripherals',
      quantity: 9,
      minThreshold: 4,
      unitCost: 229.0,
      location: 'Storage Room A',
      binNumber: 'Shelf 4',
      supplier: 'HP / Poly Enterprise',
      notes: 'Active noise-canceling headsets with desktop charging stand.',
    },
  ];

  for (const item of inventoryItems) {
    await prisma.inventoryItem.upsert({
      where: { sku: item.sku },
      update: {},
      create: item,
    });
  }
}
