import type { PrismaClient } from '@prisma/client';

interface SeedUsersResult {
  roles: Record<string, { id: string }>;
  users: Record<string, { id: string }>;
}

export async function seedLicenses(prisma: PrismaClient, users: SeedUsersResult) {
  const { users: u } = users;

  const licenseDefinitions = [
    {
      id: 'lic-m365',
      name: 'Microsoft 365 E5 Enterprise Suite',
      vendor: 'Microsoft Corporation',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 150,
      usedSeats: 142,
      costPerSeat: 456,
      purchaseDate: new Date('2024-01-01'),
      expiryDate: new Date('2026-12-31'),
      licenseKey: 'MS-E5-9921-8834-KKL9-2026',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Core enterprise productivity, Purview DLP, Defender XDR and Entra ID P2.',
    },
    {
      id: 'lic-adobe',
      name: 'Adobe Creative Cloud All Apps Enterprise',
      vendor: 'Adobe Systems Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 30,
      usedSeats: 28,
      costPerSeat: 780,
      purchaseDate: new Date('2023-09-15'),
      expiryDate: new Date('2026-09-15'),
      licenseKey: 'ADB-CC-8392-1102-LKLM-PRO',
      status: 'EXPIRING_SOON' as const,
      autoRenew: false,
      notes: 'Renewal contract pending procurement approval with Adobe VIP reseller.',
    },
    {
      id: 'lic-jetbrains',
      name: 'JetBrains All Products Pack (Commercial)',
      vendor: 'JetBrains s.r.o.',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 45,
      usedSeats: 38,
      costPerSeat: 249,
      purchaseDate: new Date('2024-03-01'),
      expiryDate: new Date('2027-02-28'),
      licenseKey: 'JB-ALL-7731-9941-PPX1-2027',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Includes IntelliJ IDEA Ultimate, WebStorm, GoLand, PyCharm and RustRover.',
    },
    {
      id: 'lic-figma',
      name: 'Figma Enterprise Design Workspace',
      vendor: 'Figma Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 35,
      usedSeats: 32,
      costPerSeat: 540,
      purchaseDate: new Date('2023-11-30'),
      expiryDate: new Date('2026-11-30'),
      licenseKey: 'FIG-ENT-1192-3381-YYE4-TEAM',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Enterprise design system libraries and unlimited Dev Mode seats.',
    },
    {
      id: 'lic-github',
      name: 'GitHub Enterprise Cloud + Copilot Business',
      vendor: 'GitHub / Microsoft',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 60,
      usedSeats: 55,
      costPerSeat: 252,
      purchaseDate: new Date('2024-01-15'),
      expiryDate: new Date('2027-01-15'),
      licenseKey: 'GH-ENT-COPILOT-9982-1144',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Advanced Security (CodeQL, Dependabot) and AI code completions.',
    },
    {
      id: 'lic-crowdstrike',
      name: 'CrowdStrike Falcon Complete Endpoint EDR',
      vendor: 'CrowdStrike Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 200,
      usedSeats: 185,
      costPerSeat: 180,
      purchaseDate: new Date('2023-06-01'),
      expiryDate: new Date('2026-06-01'),
      licenseKey: 'CS-FALCON-CCID-91820492-X88',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: '24/7 Managed detection and response across all company laptops and servers.',
    },
    {
      id: 'lic-datadog',
      name: 'Datadog Enterprise APM & Pro Suite',
      vendor: 'Datadog Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 25,
      usedSeats: 22,
      costPerSeat: 1800,
      purchaseDate: new Date('2023-10-01'),
      expiryDate: new Date('2026-10-01'),
      licenseKey: 'DD-API-KEY-88491024-SYNTH',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Infrastructure metric collectors, APM distributed traces and synthetic tests.',
    },
    {
      id: 'lic-slack',
      name: 'Slack Enterprise Grid Plan',
      vendor: 'Slack Technologies / Salesforce',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 160,
      usedSeats: 148,
      costPerSeat: 180,
      purchaseDate: new Date('2024-01-01'),
      expiryDate: new Date('2026-12-31'),
      licenseKey: 'SLK-GRID-ORG-99218491-PROD',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Enterprise key management, unlimited channels and DLP audit streams.',
    },
    {
      id: 'lic-okta',
      name: 'Okta Workforce Identity Cloud (Adaptive MFA)',
      vendor: 'Okta Inc',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 150,
      usedSeats: 145,
      costPerSeat: 72,
      purchaseDate: new Date('2024-01-01'),
      expiryDate: new Date('2026-12-31'),
      licenseKey: 'OKTA-TENANT-uims-internal.okta.com',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Universal Directory, Single Sign-On and Adaptive MFA with FastPass.',
    },
    {
      id: 'lic-zoom',
      name: 'Zoom Workplace Enterprise E4 Suite',
      vendor: 'Zoom Video Communications',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 80,
      usedSeats: 72,
      costPerSeat: 240,
      purchaseDate: new Date('2023-12-15'),
      expiryDate: new Date('2026-12-15'),
      licenseKey: 'ZM-ENT-99120-ROOMS-500',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Zoom Rooms, 500-attendee webinars and cloud meeting transcripts.',
    },
    {
      id: 'lic-salesforce',
      name: 'Salesforce Sales Cloud Unlimited Edition',
      vendor: 'Salesforce.com',
      type: 'SUBSCRIPTION' as const,
      totalSeats: 20,
      usedSeats: 18,
      costPerSeat: 3600,
      purchaseDate: new Date('2024-02-01'),
      expiryDate: new Date('2027-01-31'),
      licenseKey: 'SFDC-ORG-00D5e000000XyZ1',
      status: 'ACTIVE' as const,
      autoRenew: true,
      notes: 'Global CRM and pipeline tracking for sales executive teams.',
    },
    {
      id: 'lic-vmware',
      name: 'VMware vSphere Enterprise Plus (v8.0)',
      vendor: 'Broadcom / VMware',
      type: 'PERPETUAL' as const,
      totalSeats: 8,
      usedSeats: 8,
      costPerSeat: 3500,
      purchaseDate: new Date('2023-05-01'),
      expiryDate: new Date('2028-05-01'),
      licenseKey: 'VMW-VSP-4491-0021-HH82-ESX8',
      status: 'ACTIVE' as const,
      autoRenew: false,
      notes: 'Per-CPU socket license with Tanzu Kubernetes grid integration.',
    },
  ];

  for (const lic of licenseDefinitions) {
    await prisma.license.upsert({
      where: { id: lic.id },
      update: {},
      create: lic,
    });
  }

  const licenseAssignments = [
    {
      licenseId: 'lic-m365',
      userId: u.userAlex.id,
      assignedName: 'Alex Johnson',
      assignedEmail: 'admin@uims.internal',
      department: 'IT & Infrastructure',
    },
    {
      licenseId: 'lic-m365',
      userId: u.userSarah.id,
      assignedName: 'Sarah Chen',
      assignedEmail: 'sarah.chen@company.com',
      department: 'IT & Infrastructure',
    },
    {
      licenseId: 'lic-m365',
      userId: u.userMichael.id,
      assignedName: 'Michael Wong',
      assignedEmail: 'michael.wong@company.com',
      department: 'IT & Infrastructure',
    },
    {
      licenseId: 'lic-m365',
      userId: u.userDavidKim.id,
      assignedName: 'David Kim',
      assignedEmail: 'david.kim@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-m365',
      userId: u.userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-m365',
      userId: u.userMarcusVance.id,
      assignedName: 'Marcus Vance',
      assignedEmail: 'marcus.vance@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-m365',
      userId: u.userElena.id,
      assignedName: 'Elena Rostova',
      assignedEmail: 'elena.rostova@company.com',
      department: 'Marketing',
    },
    {
      licenseId: 'lic-adobe',
      userId: u.userMarcusVance.id,
      assignedName: 'Marcus Vance',
      assignedEmail: 'marcus.vance@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-adobe',
      userId: u.userChloeMartin.id,
      assignedName: 'Chloe Martin',
      assignedEmail: 'chloe.martin@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-adobe',
      userId: u.userElena.id,
      assignedName: 'Elena Rostova',
      assignedEmail: 'elena.rostova@company.com',
      department: 'Marketing',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: u.userDavidKim.id,
      assignedName: 'David Kim',
      assignedEmail: 'david.kim@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: u.userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: u.userLiamNguyen.id,
      assignedName: 'Liam Nguyen',
      assignedEmail: 'liam.nguyen@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-jetbrains',
      userId: u.userCarlosMendez.id,
      assignedName: 'Carlos Mendez',
      assignedEmail: 'carlos.mendez@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-figma',
      userId: u.userMarcusVance.id,
      assignedName: 'Marcus Vance',
      assignedEmail: 'marcus.vance@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-figma',
      userId: u.userChloeMartin.id,
      assignedName: 'Chloe Martin',
      assignedEmail: 'chloe.martin@company.com',
      department: 'Product & Design',
    },
    {
      licenseId: 'lic-figma',
      userId: u.userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: u.userDavidKim.id,
      assignedName: 'David Kim',
      assignedEmail: 'david.kim@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: u.userSophiaPatel.id,
      assignedName: 'Sophia Patel',
      assignedEmail: 'sophia.patel@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: u.userLiamNguyen.id,
      assignedName: 'Liam Nguyen',
      assignedEmail: 'liam.nguyen@company.com',
      department: 'Engineering',
    },
    {
      licenseId: 'lic-github',
      userId: u.userCarlosMendez.id,
      assignedName: 'Carlos Mendez',
      assignedEmail: 'carlos.mendez@company.com',
      department: 'Engineering',
    },
  ];

  await prisma.licenseAssignment.createMany({
    data: licenseAssignments,
    skipDuplicates: true,
  });
}
