import type { PrismaClient } from '@prisma/client';

export async function seedNetwork(prisma: PrismaClient) {
  // 13. Subnets & VLANs (6 Subnets)
  const subnetsData = [
    {
      cidr: '192.168.1.0/24',
      name: 'NY Data Center & Core Infrastructure',
      vlanName: 'VLAN 10 (Servers)',
      gateway: '192.168.1.1',
      totalIps: 254,
      usedIps: 184,
      location: 'NY4 Secure Vault',
    },
    {
      cidr: '192.168.10.0/24',
      name: 'HQ Employee Wired Workstations & Desks',
      vlanName: 'VLAN 20 (Workstations)',
      gateway: '192.168.10.1',
      totalIps: 254,
      usedIps: 212,
      location: 'NY HQ - Floor 4',
    },
    {
      cidr: '10.200.0.0/22',
      name: 'Corporate 802.1X Wi-Fi DHCP Pool',
      vlanName: 'VLAN 30 (Wi-Fi APs)',
      gateway: '10.200.0.1',
      totalIps: 1022,
      usedIps: 420,
      location: 'Global Hubs',
    },
    {
      cidr: '10.100.0.0/24',
      name: 'Production Kubernetes Cluster Nodes',
      vlanName: 'VLAN 40 (K8s Prod)',
      gateway: '10.100.0.1',
      totalIps: 254,
      usedIps: 96,
      location: 'NY4 / SV5 DCs',
    },
    {
      cidr: '10.50.0.0/24',
      name: 'Facilities IoT, Scanners & Security Cams',
      vlanName: 'VLAN 50 (IoT Devices)',
      gateway: '10.50.0.1',
      totalIps: 254,
      usedIps: 68,
      location: 'All Office Facilities',
    },
    {
      cidr: '172.16.0.0/24',
      name: 'Out-of-Band Management & IPMI / iDRAC',
      vlanName: 'VLAN 99 (OOB Management)',
      gateway: '172.16.0.1',
      totalIps: 254,
      usedIps: 42,
      location: 'Data Centers',
    },
  ];

  for (const s of subnetsData) {
    await prisma.subnet.upsert({
      where: { cidr: s.cidr },
      update: {},
      create: s,
    });
  }

  // 14. IP Addresses Allocation (20+ Real Hosts)
  const ipAddressesData = [
    {
      address: '192.168.1.1',
      hostname: 'cisco-core-gw01.uims.lan',
      macAddress: 'F0:5C:19:88:22:91',
      vendor: 'Cisco Systems',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Switch',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.3ms)',
    },
    {
      address: '192.168.1.10',
      hostname: 'ny-dc-srv01.uims.lan',
      macAddress: '00:1B:44:11:3A:B7',
      vendor: 'Dell Enterprise',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '1m ago (1.4ms)',
    },
    {
      address: '192.168.1.15',
      hostname: 'fortigate-fw01.uims.lan',
      macAddress: '70:4C:A5:33:11:88',
      vendor: 'Fortinet Enterprise',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Switch',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.2ms)',
    },
    {
      address: '192.168.1.50',
      hostname: 'backup-synology-nas01.uims.lan',
      macAddress: '00:11:32:8A:4F:72',
      vendor: 'Synology NAS',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (1.8ms)',
    },
    {
      address: '192.168.10.25',
      hostname: 'hp-laserjet-floor4.uims.lan',
      macAddress: '3C:52:82:19:00:DF',
      vendor: 'HP Inc',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 20 (Workstations)',
      deviceType: 'Printer',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '2m ago (3.2ms)',
    },
    {
      address: '192.168.10.45',
      hostname: 'macbook-marcus-vance.uims.lan',
      macAddress: '9C:64:8B:2A:41:09',
      vendor: 'Apple Inc',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 20 (Workstations)',
      deviceType: 'Workstation',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '3m ago (4.2ms)',
    },
    {
      address: '192.168.10.46',
      hostname: 'thinkpad-david-kim.uims.lan',
      macAddress: '54:E1:AD:77:88:99',
      vendor: 'Lenovo',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 20 (Workstations)',
      deviceType: 'Workstation',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '1m ago (2.8ms)',
    },
    {
      address: '192.168.10.150',
      hostname: 'unifi-ap-floor4-east.uims.lan',
      macAddress: '74:83:C2:55:61:FA',
      vendor: 'Ubiquiti UniFi',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 30 (Wi-Fi APs)',
      deviceType: 'Access Point',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Just now (1.1ms)',
    },
    {
      address: '192.168.10.151',
      hostname: 'unifi-ap-floor4-west.uims.lan',
      macAddress: '74:83:C2:55:61:FB',
      vendor: 'Ubiquiti UniFi',
      subnetName: '192.168.10.0/24',
      vlanName: 'VLAN 30 (Wi-Fi APs)',
      deviceType: 'Access Point',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Just now (0.9ms)',
    },
    {
      address: '10.100.0.11',
      hostname: 'k8s-master01.uims.lan',
      macAddress: '52:54:00:88:1A:01',
      vendor: 'Dell Enterprise',
      subnetName: '10.100.0.0/24',
      vlanName: 'VLAN 40 (K8s Prod)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.4ms)',
    },
    {
      address: '10.100.0.21',
      hostname: 'k8s-worker-gpu01.uims.lan',
      macAddress: '52:54:00:88:1B:02',
      vendor: 'Dell Enterprise',
      subnetName: '10.100.0.0/24',
      vlanName: 'VLAN 40 (K8s Prod)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: 'Real-time (0.5ms)',
    },
    {
      address: '172.16.0.10',
      hostname: 'idrac-poweredge-r760.oob.lan',
      macAddress: 'B0:4E:26:11:99:33',
      vendor: 'Dell iDRAC Enterprise',
      subnetName: '172.16.0.0/24',
      vlanName: 'VLAN 99 (OOB Management)',
      deviceType: 'Server',
      status: 'ASSIGNED' as const,
      pingStatus: 'online',
      lastSeen: '1m ago (1.9ms)',
    },
    {
      address: '192.168.1.99',
      hostname: 'spare-vm-host.uims.lan',
      macAddress: '00:50:56:9A:11:22',
      vendor: 'VMware vSphere',
      subnetName: '192.168.1.0/24',
      vlanName: 'VLAN 10 (Servers)',
      deviceType: 'Server',
      status: 'RESERVED' as const,
      pingStatus: 'offline',
      lastSeen: 'Standby DR replica',
    },
  ];

  for (const ip of ipAddressesData) {
    await prisma.iPAddress.upsert({
      where: { address: ip.address },
      update: {},
      create: ip,
    });
  }
}
