import type { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

export async function seedRolesAndUsers(prisma: PrismaClient) {
  // 1. Password Hashes
  const defaultPasswordHash = await bcrypt.hash('password123', 10);
  const adminPasswordHash = await bcrypt.hash('Admin@2026', 10);

  // 2. Roles & Permissions
  const superAdminRole = await prisma.role.upsert({
    where: { name: 'Super Admin' },
    update: {
      description:
        'Enterprise Super Administrator with unrestricted governance authority, emergency break-glass access, and full platform oversight.',
    },
    create: {
      name: 'Super Admin',
      description:
        'Enterprise Super Administrator with unrestricted governance authority, emergency break-glass access, and full platform oversight.',
    },
  });

  const adminRole = await prisma.role.upsert({
    where: { name: 'Admin' },
    update: {
      description:
        'Infrastructure and Operations Administrator with system-wide resource management and configuration rights.',
    },
    create: {
      name: 'Admin',
      description:
        'Infrastructure and Operations Administrator with system-wide resource management and configuration rights.',
    },
  });

  const techRole = await prisma.role.upsert({
    where: { name: 'Technician' },
    update: {
      description:
        'IT Operations and Field Technician Specialist with hardware fleet, inventory stockroom, and network endpoint maintenance privileges.',
    },
    create: {
      name: 'Technician',
      description:
        'IT Operations and Field Technician Specialist with hardware fleet, inventory stockroom, and network endpoint maintenance privileges.',
    },
  });

  const auditorRole = await prisma.role.upsert({
    where: { name: 'Auditor' },
    update: {
      description:
        'SOC2 Type II and ISO 27001 Compliance Auditor with read-only inspection and export authority across all governance trails.',
    },
    create: {
      name: 'Auditor',
      description:
        'SOC2 Type II and ISO 27001 Compliance Auditor with read-only inspection and export authority across all governance trails.',
    },
  });

  const managerRole = await prisma.role.upsert({
    where: { name: 'Manager' },
    update: {
      description:
        'Department Team Lead and Resource Approver with operational oversight and reporting privileges for assigned business units.',
    },
    create: {
      name: 'Manager',
      description:
        'Department Team Lead and Resource Approver with operational oversight and reporting privileges for assigned business units.',
    },
  });

  const employeeRole = await prisma.role.upsert({
    where: { name: 'Employee' },
    update: {
      description:
        'Standard Enterprise Employee with baseline self-service directory access and assigned hardware/software visibility.',
    },
    create: {
      name: 'Employee',
      description:
        'Standard Enterprise Employee with baseline self-service directory access and assigned hardware/software visibility.',
    },
  });

  // Seed Granular Enterprise RBAC System Permissions Catalog
  const ALL_PERMISSIONS_CATALOG = [
    // 1. Asset Management Fleet
    {
      subject: 'Asset',
      action: 'create',
      conditions: { approvalRequired: false, auditLevel: 'Standard' },
    },
    { subject: 'Asset', action: 'read', conditions: null },
    { subject: 'Asset', action: 'update', conditions: null },
    {
      subject: 'Asset',
      action: 'delete',
      conditions: { requiresDualAuthorization: true, auditLevel: 'High' },
    },
    { subject: 'Asset', action: 'export', conditions: { dataClassification: 'Internal' } },
    { subject: 'Asset', action: 'manage', conditions: { fullFleetControl: true } },

    // 2. SaaS & Software Licenses
    {
      subject: 'License',
      action: 'create',
      conditions: { procurementCheck: true, auditLevel: 'Standard' },
    },
    { subject: 'License', action: 'read', conditions: null },
    { subject: 'License', action: 'update', conditions: null },
    {
      subject: 'License',
      action: 'delete',
      conditions: { contractRevocationCheck: true, auditLevel: 'High' },
    },
    { subject: 'License', action: 'export', conditions: { dataClassification: 'Confidential' } },
    { subject: 'License', action: 'manage', conditions: { seatReallocation: true } },

    // 3. Enterprise Directory & Users
    {
      subject: 'User',
      action: 'create',
      conditions: { idmProvisioningWorkflow: true, auditLevel: 'High' },
    },
    { subject: 'User', action: 'read', conditions: null },
    { subject: 'User', action: 'update', conditions: null },
    {
      subject: 'User',
      action: 'delete',
      conditions: { deprovisionCheck: true, retainAuditHistory: true },
    },
    { subject: 'User', action: 'export', conditions: { piiComplianceMasking: true } },
    { subject: 'User', action: 'manage', conditions: { accountLockoutAuthority: true } },

    // 4. Active Directory Groups
    { subject: 'Group', action: 'create', conditions: { directoryGovernance: true } },
    { subject: 'Group', action: 'read', conditions: null },
    { subject: 'Group', action: 'update', conditions: null },
    {
      subject: 'Group',
      action: 'delete',
      conditions: { directoryGovernance: true, auditLevel: 'High' },
    },
    { subject: 'Group', action: 'export', conditions: { dataClassification: 'Internal' } },
    { subject: 'Group', action: 'manage', conditions: { membershipModification: true } },

    // 5. RBAC Roles & Security Grants
    {
      subject: 'Role',
      action: 'create',
      conditions: { governanceCommitteeApproval: true, auditLevel: 'Critical' },
    },
    { subject: 'Role', action: 'read', conditions: null },
    {
      subject: 'Role',
      action: 'update',
      conditions: { leastPrivilegePolicy: true, auditLevel: 'Critical' },
    },
    {
      subject: 'Role',
      action: 'delete',
      conditions: { emergencyBreakGlassOnly: true, auditLevel: 'Critical' },
    },
    { subject: 'Role', action: 'export', conditions: { dataClassification: 'Restricted' } },
    { subject: 'Role', action: 'manage', conditions: { rbacMatrixAuthority: true } },

    // 6. Enterprise Organizational Hierarchy
    { subject: 'Organization', action: 'create', conditions: { executiveSignoff: true } },
    { subject: 'Organization', action: 'read', conditions: null },
    { subject: 'Organization', action: 'update', conditions: null },
    { subject: 'Organization', action: 'delete', conditions: { hierarchicalIntegrityCheck: true } },
    { subject: 'Organization', action: 'export', conditions: { dataClassification: 'Internal' } },
    { subject: 'Organization', action: 'manage', conditions: { departmentReorgAuthority: true } },

    // 7. Network IPAM & Infrastructure
    { subject: 'Network', action: 'create', conditions: { ipamSubnetAllocation: true } },
    { subject: 'Network', action: 'read', conditions: null },
    { subject: 'Network', action: 'update', conditions: null },
    {
      subject: 'Network',
      action: 'delete',
      conditions: { gatewayReservationCheck: true, auditLevel: 'High' },
    },
    { subject: 'Network', action: 'export', conditions: { dataClassification: 'Confidential' } },
    { subject: 'Network', action: 'manage', conditions: { routingTopologyControl: true } },

    // 8. Stockroom & Spare Inventory
    { subject: 'Inventory', action: 'create', conditions: null },
    { subject: 'Inventory', action: 'read', conditions: null },
    { subject: 'Inventory', action: 'update', conditions: null },
    { subject: 'Inventory', action: 'delete', conditions: { writeOffThresholdApproval: true } },
    { subject: 'Inventory', action: 'export', conditions: { dataClassification: 'Internal' } },
    { subject: 'Inventory', action: 'manage', conditions: { stockAdjustmentAuthority: true } },

    // 9. Security & Compliance Audit Trails
    { subject: 'Audit', action: 'create', conditions: { appendOnlyImmutableLog: true } },
    { subject: 'Audit', action: 'read', conditions: { complianceOfficerAccess: true } },
    { subject: 'Audit', action: 'update', conditions: { forbiddenTamperProof: true } },
    {
      subject: 'Audit',
      action: 'delete',
      conditions: { retentionPolicyEnforced: true, auditLevel: 'Critical' },
    },
    {
      subject: 'Audit',
      action: 'export',
      conditions: { tamperEvidentSignature: true, dataClassification: 'Restricted' },
    },
    { subject: 'Audit', action: 'manage', conditions: { siemIntegrationAuthority: true } },

    // 10. Executive & Operational Reports
    { subject: 'Report', action: 'create', conditions: null },
    { subject: 'Report', action: 'read', conditions: null },
    { subject: 'Report', action: 'update', conditions: null },
    { subject: 'Report', action: 'delete', conditions: null },
    { subject: 'Report', action: 'export', conditions: { exportFormat: ['PDF', 'CSV', 'XLSX'] } },
    { subject: 'Report', action: 'manage', conditions: { scheduleAutomation: true } },

    // 11. System Configuration & Preferences
    { subject: 'Setting', action: 'create', conditions: { globalConfiguration: true } },
    { subject: 'Setting', action: 'read', conditions: null },
    { subject: 'Setting', action: 'update', conditions: { dualControlVerification: true } },
    {
      subject: 'Setting',
      action: 'delete',
      conditions: { emergencyOverride: true, auditLevel: 'Critical' },
    },
    { subject: 'Setting', action: 'export', conditions: { maskSecrets: true } },
    { subject: 'Setting', action: 'manage', conditions: { systemTelemetryAccess: true } },
  ];

  const seededPermissionsMap = new Map<string, string>();

  for (const perm of ALL_PERMISSIONS_CATALOG) {
    const existing = await prisma.permission.findFirst({
      where: { subject: perm.subject, action: perm.action },
    });
    if (existing) {
      await prisma.permission.update({
        where: { id: existing.id },
        data: { conditions: perm.conditions },
      });
      seededPermissionsMap.set(`${perm.subject}:${perm.action}`, existing.id);
    } else {
      const created = await prisma.permission.create({
        data: {
          subject: perm.subject,
          action: perm.action,
          conditions: perm.conditions,
        },
      });
      seededPermissionsMap.set(`${perm.subject}:${perm.action}`, created.id);
    }
  }

  // Link Permissions to Standard Roles reflecting Enterprise Least-Privilege Governance
  const rolePermissionAssignments: Record<string, string[]> = {
    'Super Admin': Array.from(seededPermissionsMap.keys()),
    Admin: [
      'Asset:create',
      'Asset:read',
      'Asset:update',
      'Asset:delete',
      'Asset:export',
      'Asset:manage',
      'License:create',
      'License:read',
      'License:update',
      'License:delete',
      'License:export',
      'License:manage',
      'User:create',
      'User:read',
      'User:update',
      'User:delete',
      'User:export',
      'User:manage',
      'Group:create',
      'Group:read',
      'Group:update',
      'Group:delete',
      'Group:export',
      'Group:manage',
      'Role:create',
      'Role:read',
      'Role:update',
      'Role:export',
      'Role:manage',
      'Organization:create',
      'Organization:read',
      'Organization:update',
      'Organization:delete',
      'Organization:export',
      'Organization:manage',
      'Network:create',
      'Network:read',
      'Network:update',
      'Network:delete',
      'Network:export',
      'Network:manage',
      'Inventory:create',
      'Inventory:read',
      'Inventory:update',
      'Inventory:delete',
      'Inventory:export',
      'Inventory:manage',
      'Audit:read',
      'Audit:export',
      'Report:create',
      'Report:read',
      'Report:update',
      'Report:delete',
      'Report:export',
      'Report:manage',
      'Setting:create',
      'Setting:read',
      'Setting:update',
      'Setting:delete',
      'Setting:export',
      'Setting:manage',
    ],
    Technician: [
      'Asset:create',
      'Asset:read',
      'Asset:update',
      'Asset:export',
      'Asset:manage',
      'Inventory:create',
      'Inventory:read',
      'Inventory:update',
      'Inventory:export',
      'Inventory:manage',
      'Network:create',
      'Network:read',
      'Network:update',
      'Network:export',
      'Network:manage',
      'License:read',
      'License:export',
      'User:read',
      'User:export',
      'Group:read',
      'Organization:read',
      'Report:read',
      'Report:export',
      'Setting:read',
    ],
    Auditor: [
      'Asset:read',
      'Asset:export',
      'License:read',
      'License:export',
      'User:read',
      'User:export',
      'Group:read',
      'Group:export',
      'Role:read',
      'Role:export',
      'Organization:read',
      'Organization:export',
      'Network:read',
      'Network:export',
      'Inventory:read',
      'Inventory:export',
      'Audit:read',
      'Audit:export',
      'Report:read',
      'Report:export',
      'Setting:read',
      'Setting:export',
    ],
    Manager: [
      'Asset:read',
      'Asset:export',
      'License:read',
      'License:export',
      'User:read',
      'User:export',
      'Group:read',
      'Organization:read',
      'Inventory:read',
      'Inventory:export',
      'Audit:read',
      'Report:create',
      'Report:read',
      'Report:export',
      'Setting:read',
    ],
    Employee: ['Asset:read', 'License:read', 'User:read', 'Organization:read', 'Report:read'],
  };

  const roleEntities = [
    { name: 'Super Admin', role: superAdminRole },
    { name: 'Admin', role: adminRole },
    { name: 'Technician', role: techRole },
    { name: 'Auditor', role: auditorRole },
    { name: 'Manager', role: managerRole },
    { name: 'Employee', role: employeeRole },
  ];

  for (const { name, role } of roleEntities) {
    const targetPermKeys = rolePermissionAssignments[name] || [];
    for (const key of targetPermKeys) {
      const permId = seededPermissionsMap.get(key);
      if (permId) {
        await prisma.rolePermission
          .upsert({
            where: {
              roleId_permissionId: {
                roleId: role.id,
                permissionId: permId,
              },
            },
            update: {},
            create: {
              roleId: role.id,
              permissionId: permId,
            },
          })
          .catch(() => {});
      }
    }
  }

  // 3. Core Enterprise Staff Data with Complete Enterprise Active Directory Attributes
  const coreStaffData = [
    {
      username: 'admin',
      email: 'admin@uims.local',
      employeeCode: 'SYS-001',
      firstName: 'System',
      lastName: 'Administrator',
      displayName: 'System Administrator',
      jobTitle: 'Super Administrator',
      roleId: superAdminRole.id,
      roleName: 'Super Admin',
      status: 'ACTIVE' as const,
      source: 'LOCAL' as const,
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Infrastructure',
      subSection: 'Directory Services',
      computerName: 'DC00-ROOT',
      computerName2: 'DC01-BACKUP',
      adGroup: 'GR_HQ_ExecutiveLeadership',
      telephone: '+1 (555) 100-2000',
      phone: '+1 (555) 100-2000',
      ouPath: 'OU=Administrators,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: adminPasswordHash,
      adInitialPassword: 'Admin@2026',
    },
    {
      username: 'alex.johnson',
      email: 'admin@uims.internal',
      employeeCode: 'EMP-1001',
      firstName: 'Alex',
      lastName: 'Johnson',
      displayName: 'Alex Johnson',
      jobTitle: 'VP of Information Technology',
      roleId: superAdminRole.id,
      roleName: 'Super Admin',
      status: 'ACTIVE' as const,
      source: 'LOCAL' as const,
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Executive',
      subSection: 'IT Leadership',
      computerName: 'WS-NY-1001',
      computerName2: 'MBP-NY-1001',
      adGroup: 'GR_HQ_ExecutiveLeadership',
      telephone: '+1 (555) 234-5678',
      phone: '+1 (555) 234-5678',
      ouPath: 'OU=Management,OU=HQ,DC=uims,DC=internal',
      managerName: 'Executive Board',
      isClosed: false,
      passwordHash: adminPasswordHash,
      adInitialPassword: 'Admin@2026',
    },
    {
      username: 'sarah.chen',
      email: 'sarah.chen@company.com',
      employeeCode: 'EMP-1002',
      firstName: 'Sarah',
      lastName: 'Chen',
      displayName: 'Sarah Chen',
      jobTitle: 'Senior Systems Administrator',
      roleId: techRole.id,
      roleName: 'Technician',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'IT & Infrastructure',
      location: 'SF HQ - Tech Bay',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Tech Bay',
      section: 'Infrastructure',
      subSection: 'Systems Administration',
      computerName: 'DC01-PRIMARY',
      computerName2: 'WS-SF-1002',
      adGroup: 'GR_HQ_ITInfrastructure',
      telephone: '+1 (555) 345-6789',
      phone: '+1 (555) 345-6789',
      ouPath: 'OU=IT,OU=Infrastructure,OU=HQ,DC=uims,DC=internal',
      managerName: 'Robert Torres',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#SarahChen2026!',
    },
    {
      username: 'michael.wong',
      email: 'michael.wong@company.com',
      employeeCode: 'EMP-1003',
      firstName: 'Michael',
      lastName: 'Wong',
      displayName: 'Michael Wong',
      jobTitle: 'Senior Network Architect',
      roleId: adminRole.id,
      roleName: 'Admin',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Infrastructure',
      subSection: 'Network Architecture',
      computerName: 'WS-NY-1003',
      computerName2: 'LT-NY-1003',
      adGroup: 'GR_HQ_ITInfrastructure',
      telephone: '+1 (555) 345-1122',
      phone: '+1 (555) 345-1122',
      ouPath: 'OU=IT,OU=Infrastructure,OU=HQ,DC=uims,DC=internal',
      managerName: 'Robert Torres',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#MichaelWong2026!',
    },
    {
      username: 'marcus.bell',
      email: 'compliance@uims.internal',
      employeeCode: 'EMP-1004',
      firstName: 'Marcus',
      lastName: 'Bell',
      displayName: 'Marcus Bell',
      jobTitle: 'Principal Security Compliance Auditor',
      roleId: auditorRole.id,
      roleName: 'Auditor',
      status: 'ACTIVE' as const,
      source: 'LOCAL' as const,
      department: 'Security & Compliance',
      location: 'London Hub',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'London Campus',
      section: 'Compliance',
      subSection: 'Information Security',
      computerName: 'WS-LON-1004',
      computerName2: 'LT-LON-1004',
      adGroup: 'GR_HQ_SecurityCompliance',
      telephone: '+44 20 7946 0912',
      phone: '+44 20 7946 0912',
      ouPath: 'OU=Security,OU=Compliance,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#MarcusBell2026!',
    },
    {
      username: 'david.kim',
      email: 'david.kim@company.com',
      employeeCode: 'EMP-1005',
      firstName: 'David',
      lastName: 'Kim',
      displayName: 'David Kim',
      jobTitle: 'Lead Cloud Architect',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Engineering',
      location: 'Remote - US East',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Remote US East',
      section: 'Cloud Operations',
      subSection: 'Platform Infrastructure',
      computerName: 'WS-RMT-1005',
      computerName2: 'MBP-RMT-1005',
      adGroup: 'GR_HQ_EngineeringCore',
      telephone: '+1 (555) 567-8901',
      phone: '+1 (555) 567-8901',
      ouPath: 'OU=Engineering,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#DavidKim2026!',
    },
    {
      username: 'sophia.patel',
      email: 'sophia.patel@company.com',
      employeeCode: 'EMP-1006',
      firstName: 'Sophia',
      lastName: 'Patel',
      displayName: 'Sophia Patel',
      jobTitle: 'Senior Staff Fullstack Engineer',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Engineering',
      location: 'SF HQ - Tech Bay',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Tech Bay',
      section: 'Product Engineering',
      subSection: 'Core Applications',
      computerName: 'WS-SF-1006',
      computerName2: 'MBP-SF-1006',
      adGroup: 'GR_HQ_EngineeringCore',
      telephone: '+1 (555) 567-2233',
      phone: '+1 (555) 567-2233',
      ouPath: 'OU=Engineering,OU=HQ,DC=uims,DC=internal',
      managerName: 'David Kim',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#SophiaPatel2026!',
    },
    {
      username: 'liam.nguyen',
      email: 'liam.nguyen@company.com',
      employeeCode: 'EMP-1007',
      firstName: 'Liam',
      lastName: 'Nguyen',
      displayName: 'Liam Nguyen',
      jobTitle: 'Lead DevOps & SRE Architect',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Engineering',
      location: 'Remote - US West',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Remote US West',
      section: 'DevOps',
      subSection: 'Site Reliability Engineering',
      computerName: 'WS-RMT-1007',
      computerName2: 'LT-RMT-1007',
      adGroup: 'GR_HQ_EngineeringCore',
      telephone: '+1 (555) 567-4455',
      phone: '+1 (555) 567-4455',
      ouPath: 'OU=Engineering,OU=HQ,DC=uims,DC=internal',
      managerName: 'David Kim',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#LiamNguyen2026!',
    },
    {
      username: 'carlos.mendez',
      email: 'carlos.mendez@company.com',
      employeeCode: 'EMP-1008',
      firstName: 'Carlos',
      lastName: 'Mendez',
      displayName: 'Carlos Mendez',
      jobTitle: 'Senior Backend Platform Engineer',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Engineering',
      location: 'NY HQ - Floor 4',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Platform Engineering',
      subSection: 'API Services',
      computerName: 'WS-NY-1008',
      computerName2: 'LT-NY-1008',
      adGroup: 'GR_HQ_EngineeringCore',
      telephone: '+1 (555) 567-7788',
      phone: '+1 (555) 567-7788',
      ouPath: 'OU=Engineering,OU=HQ,DC=uims,DC=internal',
      managerName: 'David Kim',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#CarlosMendez2026!',
    },
    {
      username: 'marcus.vance',
      email: 'marcus.vance@company.com',
      employeeCode: 'EMP-1009',
      firstName: 'Marcus',
      lastName: 'Vance',
      displayName: 'Marcus Vance',
      jobTitle: 'Principal Product Designer',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Product & Design',
      location: 'NY HQ - Floor 4',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Design',
      subSection: 'Design Systems',
      computerName: 'WS-NY-1009',
      computerName2: 'MBP-NY-1009',
      adGroup: 'GR_HQ_ProductDesign',
      telephone: '+1 (555) 456-7890',
      phone: '+1 (555) 456-7890',
      ouPath: 'OU=Design,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#MarcusVance2026!',
    },
    {
      username: 'chloe.martin',
      email: 'chloe.martin@company.com',
      employeeCode: 'EMP-1010',
      firstName: 'Chloe',
      lastName: 'Martin',
      displayName: 'Chloe Martin',
      jobTitle: 'Senior UX Researcher',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Product & Design',
      location: 'London Hub',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'London Campus',
      section: 'Design',
      subSection: 'UX Research',
      computerName: 'WS-LON-1010',
      computerName2: 'MBP-LON-1010',
      adGroup: 'GR_HQ_ProductDesign',
      telephone: '+44 20 7946 0881',
      phone: '+44 20 7946 0881',
      ouPath: 'OU=Design,OU=HQ,DC=uims,DC=internal',
      managerName: 'Marcus Vance',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#ChloeMartin2026!',
    },
    {
      username: 'elena.rostova',
      email: 'elena.rostova@company.com',
      employeeCode: 'EMP-1011',
      firstName: 'Elena',
      lastName: 'Rostova',
      displayName: 'Elena Rostova',
      jobTitle: 'Director of Growth Marketing',
      roleId: managerRole.id,
      roleName: 'Manager',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Marketing',
      location: 'London Hub',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'London Campus',
      section: 'Growth',
      subSection: 'Brand & Communications',
      computerName: 'WS-LON-1011',
      computerName2: 'LT-LON-1011',
      adGroup: 'GR_HQ_GrowthMarketing',
      telephone: '+1 (555) 678-9012',
      phone: '+1 (555) 678-9012',
      ouPath: 'OU=Marketing,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#ElenaRostova2026!',
    },
    {
      username: 'robert.torres',
      email: 'robert.torres@company.com',
      employeeCode: 'EMP-1012',
      firstName: 'Robert',
      lastName: 'Torres',
      displayName: 'Robert Torres',
      jobTitle: 'IT Infrastructure Operations Manager',
      roleId: managerRole.id,
      roleName: 'Manager',
      status: 'ACTIVE' as const,
      source: 'LOCAL' as const,
      department: 'IT & Infrastructure',
      location: 'NY HQ - Floor 4',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Infrastructure',
      subSection: 'Data Center Operations',
      computerName: 'WS-NY-1012',
      computerName2: 'LT-NY-1012',
      adGroup: 'GR_HQ_ITInfrastructure',
      telephone: '+1 (555) 678-3344',
      phone: '+1 (555) 678-3344',
      ouPath: 'OU=IT,OU=Infrastructure,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#RobertTorres2026!',
    },
    {
      username: 'lisa.wang',
      email: 'lisa.wang@company.com',
      employeeCode: 'EMP-1013',
      firstName: 'Lisa',
      lastName: 'Wang',
      displayName: 'Lisa Wang',
      jobTitle: 'Financial Controller',
      roleId: managerRole.id,
      roleName: 'Manager',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Finance',
      location: 'Singapore Hub',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Singapore Campus',
      section: 'Finance',
      subSection: 'Financial Planning & Analysis',
      computerName: 'WS-SGP-1013',
      computerName2: 'LT-SGP-1013',
      adGroup: 'GR_HQ_FinanceProcurement',
      telephone: '+65 6789 0123',
      phone: '+65 6789 0123',
      ouPath: 'OU=Finance,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#LisaWang2026!',
    },
    {
      username: 'rachel.adams',
      email: 'rachel.adams@company.com',
      employeeCode: 'EMP-1014',
      firstName: 'Rachel',
      lastName: 'Adams',
      displayName: 'Rachel Adams',
      jobTitle: 'Head of People Operations',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Human Resources',
      location: 'NY HQ - Floor 5',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Human Resources',
      subSection: 'People Operations',
      computerName: 'WS-NY-1014',
      computerName2: 'LT-NY-1014',
      adGroup: 'GR_HQ_ExecutiveLeadership',
      telephone: '+1 (555) 890-1234',
      phone: '+1 (555) 890-1234',
      ouPath: 'OU=HumanResources,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#RachelAdams2026!',
    },
    {
      username: 'james.wilson',
      email: 'james.wilson@company.com',
      employeeCode: 'EMP-1015',
      firstName: 'James',
      lastName: 'Wilson',
      displayName: 'James Wilson',
      jobTitle: 'Senior Corporate Counsel',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Legal & Governance',
      location: 'NY HQ - Floor 5',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'HQ Campus',
      section: 'Legal',
      subSection: 'Corporate Governance',
      computerName: 'WS-NY-1015',
      computerName2: 'LT-NY-1015',
      adGroup: 'GR_HQ_ExecutiveLeadership',
      telephone: '+1 (555) 901-2345',
      phone: '+1 (555) 901-2345',
      ouPath: 'OU=Legal,OU=HQ,DC=uims,DC=internal',
      managerName: 'Alex Johnson',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#JamesWilson2026!',
    },
    {
      username: 'hannah.scott',
      email: 'hannah.scott@company.com',
      employeeCode: 'EMP-1016',
      firstName: 'Hannah',
      lastName: 'Scott',
      displayName: 'Hannah Scott',
      jobTitle: 'Strategic Account Executive',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'ACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Sales',
      location: 'Remote - US Central',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Remote US Central',
      section: 'Sales',
      subSection: 'Enterprise Accounts',
      computerName: 'WS-RMT-1016',
      computerName2: 'LT-RMT-1016',
      adGroup: 'GR_HQ_GrowthMarketing',
      telephone: '+1 (555) 901-6789',
      phone: '+1 (555) 901-6789',
      ouPath: 'OU=Sales,OU=HQ,DC=uims,DC=internal',
      managerName: 'Elena Rostova',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#HannahScott2026!',
    },
    {
      username: 'thomas.wright',
      email: 'thomas.wright@company.com',
      employeeCode: 'EMP-1017',
      firstName: 'Thomas',
      lastName: 'Wright',
      displayName: 'Thomas Wright',
      jobTitle: 'Junior QA Engineer (Contractor)',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'SUSPENDED' as const,
      source: 'LOCAL' as const,
      department: 'Engineering',
      location: 'Remote - EMEA',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'Remote EMEA',
      section: 'Quality Assurance',
      subSection: 'Test Automation',
      computerName: 'WS-RMT-1017',
      computerName2: 'LT-RMT-1017',
      adGroup: 'GR_HQ_EngineeringCore',
      telephone: '+1 (555) 789-0123',
      phone: '+1 (555) 789-0123',
      ouPath: 'OU=Engineering,OU=HQ,DC=uims,DC=internal',
      managerName: 'David Kim',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#ThomasWright2026!',
    },
    {
      username: 'jessica.taylor',
      email: 'jessica.taylor@company.com',
      employeeCode: 'EMP-1018',
      firstName: 'Jessica',
      lastName: 'Taylor',
      displayName: 'Jessica Taylor',
      jobTitle: 'Content Strategist (Leave of Absence)',
      roleId: employeeRole.id,
      roleName: 'Employee',
      status: 'INACTIVE' as const,
      source: 'AZURE_AD' as const,
      department: 'Marketing',
      location: 'London Hub',
      company: 'Acme Enterprise',
      groupCompany: 'Acme Global',
      plant: 'London Campus',
      section: 'Marketing',
      subSection: 'Content Strategy',
      computerName: 'WS-LON-1018',
      computerName2: 'LT-LON-1018',
      adGroup: 'GR_HQ_GrowthMarketing',
      telephone: '+44 20 7946 0999',
      phone: '+44 20 7946 0999',
      ouPath: 'OU=Marketing,OU=HQ,DC=uims,DC=internal',
      managerName: 'Elena Rostova',
      isClosed: false,
      passwordHash: defaultPasswordHash,
      adInitialPassword: 'Ad#JessicaTaylor2026!',
    },
  ];

  // 4. Standardized Enterprise Active Directory & Email Master Dataset (From Sample Sheets)
  const enterpriseAdMasterData = [
    // Image 2 - Comprehensive Active Directory, Hardware Asset & Security Groups Dataset
    {
      employeeCode: '63020037',
      displayName: 'Phung Thi Nhu Y',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing',
      email: 'yptn.st@youngonevn.com',
      telephone: '888152675',
      isClosed: false,
      computerName: 'STOTHPR102',
      adInitialPassword: 'kPm#*Ed8',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '30000930',
      displayName: 'Lam Ngo Ha Vy',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'wylnh.st@youngonevn.com',
      telephone: '984992830',
      isClosed: false,
      computerName: 'STOTHSAM04',
      adInitialPassword: 'QhSt)-w8',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '30100576',
      displayName: 'Le Thi Thanh Hau',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'hauttt.st@youngonevn.com',
      telephone: '939387051',
      isClosed: false,
      computerName: 'STOTHSAM05',
      adInitialPassword: 'zBbFdx?9',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '33030043',
      displayName: 'Le Thi Nhu Y',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'yltn.st@youngonevn.com',
      telephone: '967294880',
      isClosed: false,
      computerName: 'STOTHSAM06',
      adInitialPassword: 'p[MH!&f7',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '40990044',
      displayName: 'Tran Van Trong',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'trongtv.st@youngonevn.com',
      telephone: '919381552',
      isClosed: false,
      computerName: 'STOTHSAM07',
      adInitialPassword: 'pcf9xHu2',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '42030090',
      displayName: 'Khuu Quang Luc',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'luckq.st@youngonevn.com',
      telephone: '971216412',
      isClosed: false,
      computerName: 'STOTHSAM08',
      adInitialPassword: 'mytxc!^2',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '43000021',
      displayName: 'Lam My Ai',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'ailm.st@youngonevn.com',
      telephone: '924705349',
      isClosed: false,
      computerName: 'STOTHSAM09',
      adInitialPassword: "Vy|{fm'z5",
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '65823073',
      displayName: 'Huynh Thi Ngoc Huynh',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'huynhhtn.st@youngonevn.com',
      telephone: '941833083',
      isClosed: false,
      computerName: 'STOTHSAM10',
      adInitialPassword: 'wUlL8U32',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94005006',
      displayName: 'Nguyen Thi Trang',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'trangnt2.st@youngonevn.com',
      telephone: '338167941',
      isClosed: false,
      computerName: 'STOTHSAM11',
      adInitialPassword: 'DEHL%;LF2',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94303327',
      displayName: 'Lieu Tuyet Tram',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'tramlt.st@youngonevn.com',
      telephone: '343810230',
      isClosed: false,
      computerName: 'STOTHSAM12',
      adInitialPassword: "kjwc's%4",
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '99002395',
      displayName: 'Tran La Hong Phuc',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'phuctlh.st@youngonevn.com',
      telephone: '944547231',
      isClosed: false,
      computerName: 'STOTHSAM13',
      adInitialPassword: 'n8WR6R*4',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '65994070',
      displayName: 'Thach Quach Hai',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'haihq.st@youngonevn.com',
      telephone: '343901792',
      isClosed: false,
      computerName: 'STOTHSAM14',
      adInitialPassword: 'w4Dg%7o5',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66103118',
      displayName: 'Tran Trung Tien',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'tientt.st@youngonevn.com',
      telephone: '385303503',
      isClosed: false,
      computerName: 'STOTHSAM15',
      adInitialPassword: 'o2cAL#n7',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66318488',
      displayName: 'Truong Thi Truc Ly',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'lyttt.st@youngonevn.com',
      telephone: '357759875',
      isClosed: false,
      computerName: 'STOTHSAM16',
      adInitialPassword: 'cgQ4zuX8',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '40920077',
      displayName: 'Quach Thanh Hien',
      jobTitle: 'Team Leader',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'hienqt.st@youngonevn.com',
      telephone: '879999489',
      isClosed: false,
      computerName: 'STOTHSAM17',
      adInitialPassword: 'D*7Zww76',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '65681801',
      displayName: 'Huynh Kim Ngan',
      jobTitle: 'Chief Of Section',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Logo Embroidery',
      email: 'nganhk.st@youngonevn.com',
      telephone: '368780568',
      isClosed: false,
      computerName: 'STOTHEMB01',
      adInitialPassword: 'E49dmQV3',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66284331',
      displayName: 'Nguyen Thi Ngoan',
      jobTitle: 'Reporter',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Logo Embroidery',
      email: 'ngoannt.st@youngonevn.com',
      telephone: '365256554',
      isClosed: false,
      computerName: 'STOTHEMB02',
      adInitialPassword: 'yrWZF9n3',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '30143740',
      displayName: 'Bui Thi Anh Thu',
      jobTitle: 'Reporter',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Logo Embroidery',
      email: 'thubta.st@youngonevn.com',
      telephone: '359114154',
      isClosed: false,
      computerName: 'STOTHEMB03',
      adInitialPassword: "Ff'M'R'(4",
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66297223',
      displayName: 'Nguyen Thanh Truc',
      jobTitle: 'Supervisor',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Logo Embroidery',
      email: 'trucnt.st@youngonevn.com',
      telephone: '783181984',
      isClosed: false,
      computerName: 'STOTHEMB04',
      adInitialPassword: 'KUZa%;(L8',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '10900067',
      displayName: 'Huynh Ngoc Anh',
      jobTitle: 'Technician',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'anhhn.st@youngonevn.com',
      telephone: '933075990',
      isClosed: false,
      computerName: 'STOTHSAM18',
      adInitialPassword: 'R2yKTNM9',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '76000062',
      displayName: 'Pham Dinh Chien',
      jobTitle: 'Technician',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing',
      email: 'chienpd.st@youngonevn.com',
      telephone: '909515292',
      isClosed: false,
      computerName: 'STOTHPR104',
      adInitialPassword: 'bd%oTYU3',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '10950045',
      displayName: 'Nguyen Huynh Thanh Tan',
      jobTitle: 'Operator',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing',
      email: 'tanhnht.st@youngonevn.com',
      telephone: '354921195',
      isClosed: false,
      computerName: 'STOTHPR105',
      adInitialPassword: 'gTZNY$M7',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '18000693',
      displayName: 'Tran Thanh Duy',
      jobTitle: 'Operator',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing',
      email: 'duytt1.st@youngonevn.com',
      telephone: '357546079',
      isClosed: false,
      computerName: 'STOTHPR106',
      adInitialPassword: 'A2KKsJr9',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66012365',
      displayName: 'Tran Thuy Son Giang',
      jobTitle: 'Operator',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing',
      email: 'giangtts.st@youngonevn.com',
      telephone: '707207016',
      isClosed: false,
      computerName: 'STOTHPR107',
      adInitialPassword: 'Kmw$z{f5',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '43020098',
      displayName: 'Nguyen Thi Minh Kha',
      jobTitle: 'Junior Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'khantm.st@youngonevn.com',
      telephone: '369494620',
      isClosed: false,
      computerName: 'STOTHSAM19',
      adInitialPassword: 'Mn4j68_6',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66247611',
      displayName: 'Tran Ngoc Hao',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'haotn.st@youngonevn.com',
      telephone: '962017743',
      isClosed: false,
      computerName: 'STOTHSAM20',
      adInitialPassword: 'Dtvu|N?4',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '65648358',
      displayName: 'Lam Thi Thu Hieu',
      jobTitle: 'Junior Supervisor',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'hieultt.st@youngonevn.com',
      telephone: '327951136',
      isClosed: false,
      computerName: 'STOTHSAM21',
      adInitialPassword: 'eugorPN5',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '99013468',
      displayName: 'Nguyen Doan Quang Huy',
      jobTitle: 'Asst. Manager',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample',
      email: 'huyndq.st@youngonevn.com',
      telephone: '354104227',
      isClosed: false,
      computerName: 'STOTHSAM22',
      adInitialPassword: 'KtevaCt2',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66191797',
      displayName: 'Nguyen Tu Giau',
      jobTitle: 'Junior Supervisor',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing',
      email: 'giaunt.st@youngonevn.com',
      telephone: '393880025',
      isClosed: false,
      computerName: 'STOTHPR108',
      adInitialPassword: 'hcXPc725',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '20000460',
      displayName: 'Luu Thanh Phu',
      jobTitle: 'Junior Technician',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Logo Embroidery',
      email: 'phult.st@youngonevn.com',
      telephone: '869123400',
      isClosed: false,
      computerName: 'STOTHEMB05',
      adInitialPassword: 'Je!6VCq3',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66008085',
      displayName: 'Le Thi Kim Chi',
      jobTitle: 'Junior Technician',
      groupCompany: 'BSL',
      company: 'BSL-1',
      plant: '1 BSL-1',
      department: 'Production',
      section: 'Production Office',
      subSection: 'Production Office',
      email: 'chiltk.st@youngonevn.com',
      telephone: '399685797',
      isClosed: false,
      computerName: 'ST1PRO01',
      adInitialPassword: 'mmV*${l4',
      adGroup: 'GR_BSL1Production Office',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '66018448',
      displayName: 'Son Thi Ngoc Huyen',
      jobTitle: 'Junior Supervisor',
      groupCompany: 'BSL',
      company: 'BSL-1',
      plant: '1 BSL-1',
      department: 'Production',
      section: 'Cutting',
      subSection: 'Cutting',
      email: 'huyenstn.st@youngonevn.com',
      telephone: '849797929',
      isClosed: false,
      computerName: 'ST1CUT01',
      adInitialPassword: 'sT5aLq_8',
      adGroup: 'GR_BSL1Cutting',
      status: 'ACTIVE' as const,
    },

    // Image 1 - Extended Corporate Email & Password Master Records
    {
      employeeCode: '66126774',
      displayName: 'Truong Ngoc Thao',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Quality Assurance',
      subSection: 'QA Inspection',
      email: 'thaotn.st@youngonevn.com',
      adInitialPassword: '9oZCu6tgz*E#dSD',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94196912',
      displayName: 'Pham Ngoc Tuyet',
      jobTitle: 'Pattern Specialist',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample Development',
      email: 'tuyetpn.st@youngonevn.com',
      adInitialPassword: 'z%5PT9Fd#E)po7q',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94304825',
      displayName: 'Vo Thi Thanh Ngan',
      jobTitle: 'Technician Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Screen Printing',
      email: 'nganvtt.st@youngonevn.com',
      adInitialPassword: 'F^9Fp5M*WF6Z2(e',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94002011',
      displayName: 'Lam Phuong Du',
      jobTitle: 'Production Supervisor',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Embroidery Ops',
      email: 'dulp.st@youngonevn.com',
      adInitialPassword: 'Za6D7d9))an#y^F',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '95003090',
      displayName: 'Nguyen Thi Ngoc Trinh',
      jobTitle: 'Supervisor Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Cutting',
      subSection: 'Automated Cutting',
      email: 'trinhntn.st@youngonevn.com',
      adInitialPassword: '3^p)GwD*5L7QAcY',
      adGroup: 'GR_BSL1Cutting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94304904',
      displayName: 'Giang Hoang Bao Yen',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Production Office',
      subSection: 'Plant Coordination',
      email: 'yenghb.st@youngonevn.com',
      adInitialPassword: 'r$JUbP(g63*kd*U',
      adGroup: 'GR_BSL1Production Office',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '96010299',
      displayName: 'Truong Thi Thuy Loan',
      jobTitle: 'Sample Coordinator',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample Finishing',
      email: 'loanttt.st@youngonevn.com',
      adInitialPassword: 'dg#Z*9DztGmr9$g',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94191123',
      displayName: 'Ho Thi Bao Ngoc',
      jobTitle: 'Embroidery Specialist',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Logo Embroidery',
      email: 'ngochtb.st@youngonevn.com',
      adInitialPassword: 'Vy^%4)nVZ0E3smd',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '65938784',
      displayName: 'Nguyen Thi Thu Oanh',
      jobTitle: 'Quality Inspector',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Digital Printing',
      email: 'oanhntt1.st@youngonevn.com',
      adInitialPassword: '4(#Eo%St&&5Vqzd',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '13010072',
      displayName: 'Ngo Pham Tuong Vy',
      jobTitle: 'Cutting Operator',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Cutting',
      subSection: 'Fabric Cutting',
      email: 'vynpt@youngonevn.com',
      adInitialPassword: '2ZEo#Kv#9$CA6pd',
      adGroup: 'GR_BSL1Cutting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94303271',
      displayName: 'Le Ha Tuyet Anh',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Production Office',
      subSection: 'Production Office',
      email: 'anhlht.st@youngonevn.com',
      adInitialPassword: 'XP6%u^D)S6X$j7s',
      adGroup: 'GR_BSL1Production Office',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '60980009',
      displayName: 'Nguyen Hoai Thuong',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'CAD Sample',
      email: 'thuongnh@youngonevn.com',
      adInitialPassword: 'Ele9Lb()Cbty#5D',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '21960021',
      displayName: 'Dong Ngoc Tuyet Nhi',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Pattern Maker',
      email: 'nhidnt@youngonevn.com',
      adInitialPassword: '5E9JJS)n3X(y32n',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '11950046',
      displayName: 'Nguyen Thi Doan Trinh',
      jobTitle: 'Quality Inspector',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Screen Printing',
      email: 'trinhntd@youngonevn.com',
      adInitialPassword: 'K&t73M(E9dd5d5z',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '73000148',
      displayName: 'Nguyen Thi Man',
      jobTitle: 'Embroidery Technician',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Embroidery',
      subSection: 'Embroidery Design',
      email: 'mannt1@youngonevn.com',
      adInitialPassword: 'g(2kA3uXVvQG*(t',
      adGroup: 'GR_BSLOTHLogo Embroidery',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '65875108',
      displayName: 'Vo Hong Dieu',
      jobTitle: 'Printing Technician',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Printing Tech',
      email: 'dieuvh.st@youngonevn.com',
      adInitialPassword: '#eNAUa3x)*As6YG',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '21840081',
      displayName: 'Vo Thi Hong Nhung',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Cutting',
      subSection: 'Material Staging',
      email: 'nhungvth1@youngonevn.com',
      adInitialPassword: '7fQ$52NY6^#R%^n',
      adGroup: 'GR_BSL1Cutting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '11910160',
      displayName: 'Le Vo Thuy Trang',
      jobTitle: 'Plant Operator',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Production Office',
      subSection: 'Office Admin',
      email: 'tranglvt@youngonevn.com',
      adInitialPassword: 'r2)dyC5pL9L9FK*',
      adGroup: 'GR_BSL1Production Office',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '91880342',
      displayName: 'Nguyen Thi Bich Tram',
      jobTitle: 'Pattern Marker',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample Line',
      email: 'tramntb@youngonevn.com',
      adInitialPassword: 'Y3cpwgY6(9$HguM',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '94098534',
      displayName: 'Ly Tang Anh Hao',
      jobTitle: 'Asst. Officer',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Printing',
      subSection: 'Heat Transfer',
      email: 'haolta.st@youngonevn.com',
      adInitialPassword: 'c6yKmWT#Fw3)zUz',
      adGroup: 'GR_BSLOTHPrinting',
      status: 'ACTIVE' as const,
    },
    {
      employeeCode: '18001197',
      displayName: 'Nguyen Ngoc Phuong Tram',
      jobTitle: 'Supervisor',
      groupCompany: 'BSL',
      company: 'BSL Others',
      plant: 'BSL Others',
      department: 'Production',
      section: 'Sample',
      subSection: 'Sample Final Inspection',
      email: 'tramnnp.st@youngonevn.com',
      adInitialPassword: 'tD&#Hpzbb2TVto7',
      adGroup: 'GR_BSLOTHSample',
      status: 'ACTIVE' as const,
    },
  ];

  const allSeedUsers = [...coreStaffData];

  for (const ad of enterpriseAdMasterData) {
    const rawUsername = ad.email.split('@')[0];
    const nameParts = ad.displayName.trim().split(' ');
    const firstName = nameParts.length > 1 ? nameParts.slice(0, -1).join(' ') : nameParts[0];
    const lastName = nameParts.length > 1 ? nameParts[nameParts.length - 1] : '';

    let role = employeeRole;
    if (
      ad.jobTitle.includes('Manager') ||
      ad.jobTitle.includes('Chief') ||
      ad.jobTitle.includes('Supervisor')
    ) {
      role = managerRole;
    } else if (ad.jobTitle.includes('Technician')) {
      role = techRole;
    }

    const sectionName = ad.section || 'Operations';
    let defaultOuPath = 'OU=Operations,OU=Plant1,DC=company,DC=internal';
    let defaultManagerName = 'Operations Division Head';

    if (sectionName.toLowerCase().includes('printing')) {
      defaultOuPath = 'OU=Printing,OU=Production,OU=Plant1,DC=company,DC=internal';
      defaultManagerName = 'Phung Thi Nhu Y (Asst. Officer)';
    } else if (sectionName.toLowerCase().includes('sample')) {
      defaultOuPath = 'OU=Sample,OU=Production,OU=Plant1,DC=company,DC=internal';
      defaultManagerName = 'Nguyen Doan Quang Huy (Asst. Manager)';
    } else if (sectionName.toLowerCase().includes('embroidery')) {
      defaultOuPath = 'OU=Embroidery,OU=Production,OU=Plant1,DC=company,DC=internal';
      defaultManagerName = 'Huynh Kim Ngan (Chief of Section)';
    } else if (sectionName.toLowerCase().includes('cutting')) {
      defaultOuPath = 'OU=Cutting,OU=Production,OU=Plant1,DC=company,DC=internal';
      defaultManagerName = 'Son Thi Ngoc Huyen (Junior Supervisor)';
    } else if (
      sectionName.toLowerCase().includes('production') ||
      sectionName.toLowerCase().includes('office')
    ) {
      defaultOuPath = 'OU=Operations,OU=Plant1,DC=company,DC=internal';
      defaultManagerName = 'Le Thi Kim Chi (Junior Technician)';
    }

    allSeedUsers.push({
      username: rawUsername,
      email: ad.email,
      employeeCode: ad.employeeCode,
      firstName,
      lastName,
      displayName: ad.displayName,
      jobTitle: ad.jobTitle,
      roleId: role.id,
      roleName: role.name,
      status: ad.status || ('ACTIVE' as const),
      source: 'LDAP' as const,
      department: ad.department || 'Production',
      location: `${ad.company || 'BSL Others'} - ${ad.plant || 'Plant 1'}`,
      company: ad.company || 'BSL Others',
      groupCompany: ad.groupCompany || 'BSL',
      plant: ad.plant || 'Plant 1',
      section: ad.section || 'Production',
      subSection: ad.subSection || 'General Operations',
      computerName: ad.computerName || `WS-${ad.employeeCode}`,
      computerName2: (ad as { computerName2?: string }).computerName2 || `LT-${ad.employeeCode}`,
      adGroup: ad.adGroup || 'GR_BSL1Production Office',
      telephone:
        (ad as { telephone?: string }).telephone || `+84 28 3810 ${ad.employeeCode.slice(-4)}`,
      phone: (ad as { telephone?: string }).telephone
        ? `+84 ${(ad as { telephone?: string }).telephone}`
        : `+84 28 3810 ${ad.employeeCode.slice(-4)}`,
      ouPath: (ad as { ouPath?: string }).ouPath || defaultOuPath,
      managerName: (ad as { managerName?: string }).managerName || defaultManagerName,
      isClosed: Boolean(ad.isClosed),
      passwordHash: defaultPasswordHash,
      adInitialPassword: ad.adInitialPassword,
    });
  }

  const seededUsers: Record<string, import('@prisma/client').User> = {};

  for (const u of allSeedUsers) {
    const userRecord = await prisma.user.upsert({
      where: { email: u.email },
      update: {
        username: u.username,
        employeeCode: u.employeeCode,
        firstName: u.firstName,
        lastName: u.lastName,
        displayName: u.displayName,
        jobTitle: u.jobTitle,
        roleId: u.roleId,
        roleName: u.roleName,
        status: u.status,
        source: u.source,
        department: u.department,
        location: u.location,
        company: u.company,
        groupCompany: u.groupCompany,
        plant: u.plant,
        section: u.section,
        subSection: u.subSection,
        computerName: u.computerName,
        computerName2: u.computerName2,
        adGroup: u.adGroup,
        telephone: u.telephone || u.phone,
        isClosed: Boolean(u.isClosed),
        phone: u.phone,
        ouPath: u.ouPath,
        managerName: u.managerName,
        passwordHash: u.passwordHash,
        adInitialPassword: u.adInitialPassword,
      },
      create: {
        username: u.username,
        email: u.email,
        employeeCode: u.employeeCode,
        firstName: u.firstName,
        lastName: u.lastName,
        displayName: u.displayName,
        jobTitle: u.jobTitle,
        roleId: u.roleId,
        roleName: u.roleName,
        status: u.status,
        source: u.source,
        department: u.department,
        location: u.location,
        company: u.company,
        groupCompany: u.groupCompany,
        plant: u.plant,
        section: u.section,
        subSection: u.subSection,
        computerName: u.computerName,
        computerName2: u.computerName2,
        adGroup: u.adGroup,
        telephone: u.telephone || u.phone,
        isClosed: Boolean(u.isClosed),
        phone: u.phone,
        ouPath: u.ouPath,
        managerName: u.managerName,
        passwordHash: u.passwordHash,
        adInitialPassword: u.adInitialPassword,
      },
    });
    seededUsers[u.email] = userRecord;
  }

  return {
    roles: { superAdminRole, adminRole, techRole, auditorRole, managerRole, employeeRole },
    users: {
      userAdminLocal: seededUsers['admin@uims.local'],
      userAlex: seededUsers['admin@uims.internal'],
      userSarah: seededUsers['sarah.chen@company.com'],
      userMichael: seededUsers['michael.wong@company.com'],
      userMarcusBell: seededUsers['compliance@uims.internal'],
      userDavidKim: seededUsers['david.kim@company.com'],
      userSophiaPatel: seededUsers['sophia.patel@company.com'],
      userLiamNguyen: seededUsers['liam.nguyen@company.com'],
      userCarlosMendez: seededUsers['carlos.mendez@company.com'],
      userMarcusVance: seededUsers['marcus.vance@company.com'],
      userChloeMartin: seededUsers['chloe.martin@company.com'],
      userElena: seededUsers['elena.rostova@company.com'],
      userRobertTorres: seededUsers['robert.torres@company.com'],
      userLisaWang: seededUsers['lisa.wang@company.com'],
      userRachelAdams: seededUsers['rachel.adams@company.com'],
      userJamesWilson: seededUsers['james.wilson@company.com'],
      userHannahScott: seededUsers['hannah.scott@company.com'],
      userThomas: seededUsers['thomas.wright@company.com'],
      userJessica: seededUsers['jessica.taylor@company.com'],
      ...seededUsers,
    },
  };
}
