import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  NotFoundException,
} from '@nestjs/common';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { encryptDirectoryPassword } from '../../common/crypto/directory-crypto';
import type { PrismaService } from '../../database/prisma.service';
import { DirectoryController } from './directory.controller';
import { DirectoryService } from './directory.service';

describe('Milestone M2: Directory Relational & Credential Service Unit Suite', () => {
  let service: DirectoryService;
  let controller: DirectoryController;

  const mockPrisma = {
    directoryUser: {
      findFirst: vi.fn(),
      findUnique: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      count: vi.fn(),
    },
    asset: {
      findUnique: vi.fn(),
      findMany: vi.fn(),
      update: vi.fn(),
      updateMany: vi.fn(),
    },
    license: {
      findUnique: vi.fn(),
      findMany: vi.fn(),
      update: vi.fn(),
    },
    licenseAssignment: {
      findFirst: vi.fn(),
      findUnique: vi.fn(),
      findMany: vi.fn(),
      create: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
      deleteMany: vi.fn(),
    },
    $transaction: vi.fn(async (cb: (tx: unknown) => Promise<unknown>) => cb(mockPrisma)),
  };

  beforeEach(() => {
    vi.clearAllMocks();
    process.env.DIRECTORY_ENCRYPTION_KEY = 'test-secret-key-32-chars-long!!';
    service = new DirectoryService(mockPrisma as unknown as PrismaService);
    controller = new DirectoryController(service);
  });

  describe('Audited Email Password Operations', () => {
    it('revealEmailPassword: admin can reveal password and receive plaintext', async () => {
      const plaintextPass = 'EnterpriseSecret123!';
      const encrypted = encryptDirectoryPassword(plaintextPass);

      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'alex.chen@corp.uims.internal',
        emailPassword: encrypted,
      });

      const result = await controller.revealEmailPassword(
        'u-1',
        { user: { id: 'admin-1', role: 'Admin', email: 'admin@corp.uims.internal' } },
        '10.0.0.5',
      );

      expect(result.password).toBe(plaintextPass);
      expect(result.userId).toBe('u-1');
      expect(result.email).toBe('alex.chen@corp.uims.internal');
      expect(result.revealedAt).toBeDefined();
    });

    it('revealEmailPassword: non-admin role is rejected with ForbiddenException', async () => {
      await expect(
        service.revealEmailPassword('u-1', {
          id: 'user-2',
          role: 'Employee',
          email: 'emp@corp.uims.internal',
        }),
      ).rejects.toThrow(ForbiddenException);
    });

    it('revealEmailPassword: user without configured password throws NotFoundException', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'alex.chen@corp.uims.internal',
        emailPassword: null,
      });

      await expect(
        controller.revealEmailPassword(
          'u-1',
          { user: { id: 'admin-1', role: 'Super Admin' } },
          '127.0.0.1',
        ),
      ).rejects.toThrow(NotFoundException);
    });

    it('copyEmailPassword: verifies envelope and logs copy audit', async () => {
      const encrypted = encryptDirectoryPassword('ValidPassword123!');
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'alex.chen@corp.uims.internal',
        emailPassword: encrypted,
      });

      const res = await controller.copyEmailPassword(
        'u-1',
        { user: { id: 'admin-1', role: 'Admin' } },
        '127.0.0.1',
      );

      expect(res.success).toBe(true);
      expect(res.copiedAt).toBeDefined();
    });

    it('resetEmailPassword: auto-generates 24-character password when not provided', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'alex.chen@corp.uims.internal',
      });
      mockPrisma.directoryUser.update.mockResolvedValue({ id: 'u-1' });

      const res = await controller.resetEmailPassword(
        'u-1',
        {},
        { user: { id: 'admin-1', role: 'Admin' } },
        '127.0.0.1',
      );

      expect(res.success).toBe(true);
      expect(res.autoGenerated).toBe(true);
      expect(res.password).toBeDefined();
      expect(res.password?.length).toBe(24);
      expect(mockPrisma.directoryUser.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 'u-1' },
          data: expect.objectContaining({
            emailPassword: expect.stringMatching(/^enc:v1:/),
          }),
        }),
      );
    });

    it('resetEmailPassword: sets custom password when provided', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'alex.chen@corp.uims.internal',
      });
      mockPrisma.directoryUser.update.mockResolvedValue({ id: 'u-1' });

      const res = await controller.resetEmailPassword(
        'u-1',
        { newPassword: 'CustomP@ssw0rd2026!' },
        { user: { id: 'admin-1', role: 'Super Admin' } },
        '127.0.0.1',
      );

      expect(res.success).toBe(true);
      expect(res.autoGenerated).toBe(false);
      expect(mockPrisma.directoryUser.update).toHaveBeenCalled();
    });
  });

  describe('Hardware Device (Asset) Management', () => {
    it('getUserAssets: returns assigned assets for directory user', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1', employeeCode: 'EMP1' });
      mockPrisma.asset.findMany.mockResolvedValue([
        { id: 'ast-1', name: 'ThinkPad T14', assetTag: 'AST-01', status: 'IN_USE' },
      ]);

      const assets = await controller.getUserAssets('u-1');
      expect(assets.length).toBe(1);
      expect(assets[0].name).toBe('ThinkPad T14');
    });

    it('assignAsset: assigns available asset to active user and transitions to IN_USE', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        status: 'ACTIVE',
      });
      mockPrisma.asset.findUnique.mockResolvedValue({
        id: 'ast-1',
        assetTag: 'AST-01',
        status: 'AVAILABLE',
        assignedToId: null,
      });
      mockPrisma.asset.update.mockResolvedValue({
        id: 'ast-1',
        assignedToId: 'u-1',
        status: 'IN_USE',
      });

      const res = await controller.assignAsset('u-1', 'ast-1');
      expect(res.status).toBe('IN_USE');
      expect(mockPrisma.asset.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 'ast-1' },
          data: { assignedToId: 'u-1', status: 'IN_USE' },
        }),
      );
    });

    it('assignAsset: rejects assignment if user is SUSPENDED', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        status: 'SUSPENDED',
      });

      await expect(controller.assignAsset('u-1', 'ast-1')).rejects.toThrow(BadRequestException);
    });

    it('assignAsset: rejects assignment if asset already assigned to another user', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        status: 'ACTIVE',
      });
      mockPrisma.asset.findUnique.mockResolvedValue({
        id: 'ast-1',
        assetTag: 'AST-01',
        status: 'IN_USE',
        assignedToId: 'other-user',
      });

      await expect(controller.assignAsset('u-1', 'ast-1')).rejects.toThrow(ConflictException);
    });

    it('assignAsset: rejects assignment if asset status is not AVAILABLE', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        status: 'ACTIVE',
      });
      mockPrisma.asset.findUnique.mockResolvedValue({
        id: 'ast-1',
        assetTag: 'AST-01',
        status: 'MAINTENANCE',
        assignedToId: null,
      });

      await expect(controller.assignAsset('u-1', 'ast-1')).rejects.toThrow(BadRequestException);
    });

    it('unassignAsset: releases asset to AVAILABLE when user holds it', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'user@corp.internal',
      });
      mockPrisma.asset.findUnique.mockResolvedValue({
        id: 'ast-1',
        assetTag: 'AST-01',
        assignedToId: 'u-1',
      });
      mockPrisma.asset.update.mockResolvedValue({
        id: 'ast-1',
        assignedToId: null,
        status: 'AVAILABLE',
      });

      const res = await controller.unassignAsset('u-1', 'ast-1');
      expect(res.success).toBe(true);
      expect(mockPrisma.asset.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 'ast-1' },
          data: { assignedToId: null, status: 'AVAILABLE' },
        }),
      );
    });

    it('unassignAsset: rejects if asset is not assigned to any user', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1' });
      mockPrisma.asset.findUnique.mockResolvedValue({
        id: 'ast-1',
        assetTag: 'AST-01',
        assignedToId: null,
      });

      await expect(controller.unassignAsset('u-1', 'ast-1')).rejects.toThrow(BadRequestException);
    });

    it('unassignAsset: rejects if asset is assigned to a different user', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        email: 'u1@corp.internal',
      });
      mockPrisma.asset.findUnique.mockResolvedValue({
        id: 'ast-1',
        assetTag: 'AST-01',
        assignedToId: 'u-2',
      });

      await expect(controller.unassignAsset('u-1', 'ast-1')).rejects.toThrow(BadRequestException);
    });

    it('getAvailableAssets: queries available unassigned assets', async () => {
      mockPrisma.asset.findMany.mockResolvedValue([{ id: 'ast-avail' }]);
      const assets = await controller.getAvailableAssets();
      expect(assets.length).toBe(1);
      expect(mockPrisma.asset.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { status: 'AVAILABLE', assignedToId: null },
        }),
      );
    });
  });

  describe('Software License Management', () => {
    it('getUserLicenses: returns active license assignments', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1' });
      mockPrisma.licenseAssignment.findMany.mockResolvedValue([
        { id: 'la-1', licenseId: 'lic-1', license: { name: 'Figma' } },
      ]);

      const res = await controller.getUserLicenses('u-1');
      expect(res.length).toBe(1);
      expect(res[0].license.name).toBe('Figma');
    });

    it('assignLicense: allocates license seat and increments usedSeats', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({
        id: 'u-1',
        firstName: 'Alex',
        lastName: 'Chen',
        email: 'alex@corp.internal',
        status: 'ACTIVE',
      });
      mockPrisma.license.findUnique.mockResolvedValue({
        id: 'lic-1',
        name: 'AutoCAD',
        status: 'ACTIVE',
        totalSeats: 10,
        usedSeats: 4,
        expiryDate: new Date(Date.now() + 10000000),
      });
      mockPrisma.licenseAssignment.findFirst.mockResolvedValue(null);
      mockPrisma.licenseAssignment.create.mockResolvedValue({
        id: 'la-new',
        licenseId: 'lic-1',
        userId: 'u-1',
      });

      const res = await controller.assignLicense('u-1', 'lic-1');
      expect(res.id).toBe('la-new');
      expect(mockPrisma.license.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 'lic-1' },
          data: { usedSeats: { increment: 1 } },
        }),
      );
    });

    it('assignLicense: rejects when license capacity is exhausted', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1', status: 'ACTIVE' });
      mockPrisma.license.findUnique.mockResolvedValue({
        id: 'lic-1',
        name: 'AutoCAD',
        status: 'ACTIVE',
        totalSeats: 5,
        usedSeats: 5,
      });
      mockPrisma.licenseAssignment.findFirst.mockResolvedValue(null);

      await expect(controller.assignLicense('u-1', 'lic-1')).rejects.toThrow(ConflictException);
    });

    it('assignLicense: rejects duplicate allocation of same license to same user', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1', status: 'ACTIVE' });
      mockPrisma.license.findUnique.mockResolvedValue({
        id: 'lic-1',
        name: 'AutoCAD',
        status: 'ACTIVE',
        totalSeats: 10,
        usedSeats: 2,
      });
      mockPrisma.licenseAssignment.findFirst.mockResolvedValue({ id: 'existing-la' });

      await expect(controller.assignLicense('u-1', 'lic-1')).rejects.toThrow(ConflictException);
    });

    it('assignLicense: rejects allocating from expired license', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1', status: 'ACTIVE' });
      mockPrisma.license.findUnique.mockResolvedValue({
        id: 'lic-1',
        name: 'Expired Tool',
        status: 'ACTIVE',
        totalSeats: 10,
        usedSeats: 2,
        expiryDate: new Date(Date.now() - 100000),
      });

      await expect(controller.assignLicense('u-1', 'lic-1')).rejects.toThrow(BadRequestException);
    });

    it('unassignLicense: revokes license seat and decrements usedSeats', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1' });
      mockPrisma.licenseAssignment.findUnique.mockResolvedValue({
        id: 'la-1',
        userId: 'u-1',
        licenseId: 'lic-1',
      });
      mockPrisma.license.findUnique.mockResolvedValue({
        id: 'lic-1',
        usedSeats: 3,
      });

      const res = await controller.unassignLicense('u-1', 'la-1');
      expect(res.success).toBe(true);
      expect(mockPrisma.license.update).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { id: 'lic-1' },
          data: { usedSeats: 2 },
        }),
      );
      expect(mockPrisma.licenseAssignment.delete).toHaveBeenCalledWith({
        where: { id: 'la-1' },
      });
    });

    it('unassignLicense: rejects revoking assignment belonging to different user', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-1' });
      mockPrisma.licenseAssignment.findUnique.mockResolvedValue({
        id: 'la-1',
        userId: 'other-user',
        licenseId: 'lic-1',
      });

      await expect(controller.unassignLicense('u-1', 'la-1')).rejects.toThrow(BadRequestException);
    });

    it('getAvailableLicenses: filters out licenses with 0 remaining seats', async () => {
      mockPrisma.license.findMany.mockResolvedValue([
        { id: 'lic-avail', name: 'Slack', totalSeats: 10, usedSeats: 5 },
        { id: 'lic-full', name: 'Zoom', totalSeats: 5, usedSeats: 5 },
      ]);

      const res = await controller.getAvailableLicenses();
      expect(res.length).toBe(1);
      expect(res[0].id).toBe('lic-avail');
    });
  });

  describe('Relational Cascade Cleanup on Deletion', () => {
    it('remove: releases assets, revokes licenses and deletes user record', async () => {
      mockPrisma.directoryUser.findFirst.mockResolvedValue({ id: 'u-delete' });
      mockPrisma.asset.updateMany.mockResolvedValue({ count: 2 });
      mockPrisma.licenseAssignment.findMany.mockResolvedValue([{ id: 'la-1', licenseId: 'lic-1' }]);
      mockPrisma.license.findUnique.mockResolvedValue({ id: 'lic-1', usedSeats: 3 });
      mockPrisma.license.update.mockResolvedValue({});
      mockPrisma.licenseAssignment.deleteMany.mockResolvedValue({ count: 1 });
      mockPrisma.directoryUser.delete.mockResolvedValue({ id: 'u-delete' });

      await controller.remove('u-delete');

      expect(mockPrisma.asset.updateMany).toHaveBeenCalledWith({
        where: { assignedToId: 'u-delete' },
        data: { assignedToId: null, status: 'AVAILABLE' },
      });
      expect(mockPrisma.license.update).toHaveBeenCalledWith({
        where: { id: 'lic-1' },
        data: { usedSeats: 2 },
      });
      expect(mockPrisma.licenseAssignment.deleteMany).toHaveBeenCalledWith({
        where: { userId: 'u-delete' },
      });
      expect(mockPrisma.directoryUser.delete).toHaveBeenCalledWith({
        where: { id: 'u-delete' },
      });
    });
  });
});
